// build-logic.mjs — vendor the REAL pure logic from the source project into the demo.
//
//   node demos/transpo-routes/build-logic.mjs
//
// Why bother: the interesting part of this app is the folds — who is riding, how riders group onto
// stops, and above all the NOT_CHECKED vs zero distinction. Re-implementing those in mock.js would
// make the demo a drawing of the app rather than the app. So the demo runs the project's own
// logic/*.js, concatenated here into browser globals exactly the way Apps Script loads them.
//
// The Node shim at the bottom of each source file is stripped; in the browser `module` is undefined
// so each file's internal fallback path is the live one — the same path GAS takes.
//
// Exits 0 with a SKIP if the source project isn't checked out beside this repo, so the showcase
// still builds on a machine that only has the showcase.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.resolve(HERE, '../../../FACTS/transpo-department/logic');

if (!existsSync(SRC)) {
  console.log('SKIP build-logic: source project not found at', SRC);
  process.exit(0);
}

// Order matters only for readability — GAS hoists function declarations across the whole scope.
const FILES = ['schema.js', 'stops.js', 'manifest.js', 'office.js', 'auth.js'];

const parts = FILES.map((f) => {
  let body = readFileSync(path.join(SRC, f), 'utf8');

  // Drop the Node shim at the bottom.
  const cut = body.indexOf("if (typeof module !== 'undefined'");
  if (cut > 0) body = body.slice(0, cut);

  // Neutralise the guarded require() initialisers. In a browser `module` is undefined so these
  // already take the null branch — but a bundle that still CONTAINS the word `require` breaks the
  // moment anything loads it in a CommonJS context (which is exactly how the first smoke test of
  // this file failed). Cutting them makes the bundle standalone anywhere.
  body = body.replace(
    /\(typeof module !== 'undefined' && module\.exports\)\s*\r?\n?\s*\? require\([^)]*\) : null/g,
    'null');

  return `/* ===== ${f} ===== */\n` + body;
});

const out = [
  '/* GENERATED by demos/transpo-routes/build-logic.mjs — do not edit.',
  '   This is the SOURCE PROJECT\'S OWN logic/, verbatim, so the demo\'s route sheet, stop grouping,',
  '   check-off states and adoption table are the app\'s real behaviour and cannot drift from it.',
  '   Re-run the script after any change to transpo-department/logic/. */',
  '(function (global) {',
  "  'use strict';",
  ...parts,
  '  global.TRANSPO_LOGIC = {',
  '    buildManifest: buildManifest, projectRider: projectRider, foldBoarding: foldBoarding,',
  '    buildStops: buildStops, buildStudentStops: buildStudentStops, resequence: resequence,',
  '    checkState: checkState, boardingTally: boardingTally, checkStateLabel: checkStateLabel,',
  '    driverAdoption: driverAdoption, recentActivity: recentActivity, coverageGaps: coverageGaps,',
  '    CHECK_STATE: CHECK_STATE, DRIVER_RIDER_FIELDS: DRIVER_RIDER_FIELDS,',
  '    FORBIDDEN_RIDER_FIELDS: FORBIDDEN_RIDER_FIELDS',
  '  };',
  '})(window);',
  ''
].join('\n');

writeFileSync(path.join(HERE, 'logic.js'), out);
console.log('built demos/transpo-routes/logic.js (' + out.length + ' bytes) from', FILES.length, 'source files');
