/* GENERATED by demos/transpo-routes/build-logic.mjs — do not edit.
   This is the SOURCE PROJECT'S OWN logic/, verbatim, so the demo's route sheet, stop grouping,
   check-off states and adoption table are the app's real behaviour and cannot drift from it.
   Re-run the script after any change to transpo-department/logic/. */
(function (global) {
  'use strict';
/* ===== schema.js ===== */
'use strict';
/**
 * schema.js — THE single load-bearing definition of the Transpo_WORKING data model.
 *
 * Consumers, all reading these constants (the anti-drift mechanism):
 *   1. SheetGateway bootstrapSheets_() creates tabs/headers from cols[].name order
 *   2. SheetGateway reads build their column-index maps from it
 *   3. driver/office serializers project columns from cols[].tier
 *   4. test/ asserts the published driver slice carries NOTHING outside DRIVER tier
 *
 * Tiers (who a column may be serialized to):
 *   DRIVER — the anonymous driver app, on a personal phone behind a token + PIN.
 *            The narrowest surface in this project. Name, grade, stop. That is all.
 *   OFFICE — DOMAIN staff (Lois + the office) in apps/office.
 *   SYSTEM — never serialized to ANY client; visible only in the raw sheet.
 *
 * Columns are APPEND-ONLY once live (FACTS-export discipline): never insert, never
 * reorder; retired columns keep their slot with a comment.
 */

var TIER = { DRIVER: 0, OFFICE: 1, SYSTEM: 2 };

/**
 * A route runs twice a day and the two halves are genuinely different: 8 students ride a
 * DIFFERENT route AM vs PM (e.g. Dinges, Matthew — Aberdeen/HDG AM, Cecil PM), and 11 students
 * are AM-ONLY (they arrive by bus and leave another way). Everything here is keyed by session.
 */
var SESSIONS = ['AM', 'PM'];

/**
 * AM carries no attendance signal and the UI must say so.
 *
 * The dismissal board is PM-only by design: its whole value is cross-referencing FACTS attendance,
 * mid-day sign-outs and today's overrides, none of which exist yet at 7am. A child absent today is
 * not known until a teacher marks them, which happens after the morning run. So the AM manifest is
 * a roster + stops with NO "don't wait for this one" intelligence, and it says as much on the page.
 *
 * This is the house rule that an unknown always reads as EXPECTED: never invent an absence. A child
 * not waited for who is still standing at the stop is far worse than one waited for who has gone.
 */
var SESSION_HAS_ATTENDANCE = { AM: false, PM: true };

/** Audit-log event types. Written by the driver app, read by the office. */
var ACTIVITY_EVENTS = {
  LOGIN: 'login',
  LOGIN_FAILED: 'login_failed',
  LOCKED: 'locked',            // hit the attempt limiter — a driver stuck at the roadside
  ROUTE_OPEN: 'route_open'
};

/**
 * The three states a route can be in for check-off on a given day, and the reason this enum exists.
 *
 * Adoption WILL be partial — some drivers will use the tick, some never will. The danger is not
 * that; it is an office screen reading "0 boarded" as "nobody got on" when it means "this driver
 * does not use the app". Those are opposite conclusions from identical data.
 *
 * So a count is never shown on its own. Every route carries one of these, and NOT_CHECKED is
 * rendered differently from a real zero. Same doctrine as BOARDING_HONESTY, enforced where the
 * consequence actually lands: the office.
 */
var CHECK_STATE = {
  NOT_CHECKED: 'not_checked',  // no events at all today — we know NOTHING, say so
  IN_PROGRESS: 'in_progress',  // some riders recorded, not all
  COMPLETE: 'complete'         // every expected rider has an event
};

/** What a driver can record against a child at a stop. See BOARDING_HONESTY below. */
var BOARDING_ACTIONS = {
  ON: 'on',            // boarded here
  OFF: 'off',          // got off here
  NO_SHOW: 'no_show'   // driver waited, nobody came
};

/**
 * THE HONESTY RULE, and it is not negotiable.
 *
 * The ABSENCE of a boarding row means "not recorded" — it NEVER means "not on the bus". A driver
 * who is busy, out of signal, or simply forgets produces exactly the same data as an empty seat.
 * Every surface that renders this must say "not recorded", and no count may be presented as a
 * headcount. A check-off system that implies certainty it does not have is more dangerous than
 * no check-off at all, because people stop looking.
 */
var BOARDING_HONESTY = 'An unchecked child is NOT RECORDED — never "not on the bus".';

/**
 * The EXPLICIT allowlist of fields a rider object may carry onto the driver's phone.
 *
 * Build the published object by naming these fields one at a time. NEVER spread a roster row into
 * it — that is precisely how a student id, a phone number or a free-text note reaches an anonymous
 * surface, and it is the mistake the forbidden-field test exists to catch. Same doctrine as
 * ../transportation/Dismissal.gs:1225 (dsRampSlice).
 *
 *   rk        opaque per-day rider key (see RIDER_KEY_NOTE) — NOT the FACTS student id
 *   name      the child's name, as the driver must call it
 *   grade     so a driver knows roughly who they are looking for
 *   stopId    which stop groups them (resolved server-side; empty until Phase 2)
 *   expected  bool — are they riding today
 *   reason    PM only: 'ABSENT' | 'LEFT EARLY' | 'SIGNED OUT' | 'CHANGED' — why not
 *   detail    PM only: the human sentence under the reason
 *   flags     PM only: 'also on <route>', 'added today', 'standing'
 */
var DRIVER_RIDER_FIELDS = ['rk', 'name', 'grade', 'stopId', 'expected', 'reason', 'detail', 'flags'];

/**
 * Asserted absent from every published rider object by test/. This list is deliberately longer
 * than the roster's real field names — it also catches the plausible near-misses a future edit
 * might introduce (cellPhone, guardian, address) before they ever ship.
 */
var FORBIDDEN_RIDER_FIELDS = [
  'id', 'studentId', 'personId', 'sid',
  'phone', 'cellPhone', 'homePhone', 'workPhone', 'email', 'email2',
  'pickups', 'pickupContacts', 'guardian', 'parent', 'emergencyContact',
  'address', 'addressID', 'familyId', 'family',
  'homeroom', 'homeroomTeacher', 'teacher',
  'note', 'overrideNote', 'standingNote', 'by', 'changedBy', 'source',
  'birthdate', 'gender', 'locker'
];

/**
 * Why the driver surface never carries the FACTS student id.
 *
 * Check-off needs a stable handle for each child, but the published JSON sits on ~8 personal
 * phones behind a URL token — a wider blast radius than the single school-owned ramp iPad. So we
 * publish `rk` = the first 16 chars of base64(HMAC-SHA256(studentId + '|' + dayKey, SECRET)).
 * It round-trips office-side through the same map, is inert if the file leaks, and because dayKey
 * is in the digest it ROTATES DAILY — yesterday's capture buys nothing today.
 */
var RIDER_KEY_NOTE = 'rk = trunc16(base64(HMAC-SHA256(studentId + "|" + dayKey, SECRET)))';

var SCHEMA = {
  /**
   * The stop sequence for one route+session. THE genuinely new data in this project — no stop
   * list exists in FACTS, in the dismissal app, or on Lois's master PDF (which is sorted by
   * student surname and carries no stops at all). Office-owned; seeded empty.
   */
  Stops: {
    key: 'Stop ID',
    cols: [
      { name: 'Stop ID', tier: 'OFFICE' },        // stable id; never reused after retirement
      { name: 'Route Code', tier: 'DRIVER' },     // 'J', 'A/HdG', 'CC' — matches Dismissal_WORKING!Routes
      { name: 'Session', tier: 'DRIVER' },        // 'AM' | 'PM'
      { name: 'Seq', tier: 'DRIVER' },            // 10, 20, 30 — gapped so a stop can be inserted
      { name: 'Stop Name', tier: 'DRIVER' },      // what the driver calls it out loud
      { name: 'Landmark', tier: 'DRIVER' },       // 'Jarrettsville firehouse' — how you FIND it
      { name: 'Time', tier: 'DRIVER' },           // optional; a stop order alone is useful
      { name: 'Days', tier: 'OFFICE' },           // blank = every school day; 'Mon,Wed,Fri' limits
      { name: 'Active', tier: 'OFFICE' },         // 'N' retires a stop without deleting its history
      // ABOUT THE PLACE, never about a child. The office UI says so at the input, because this
      // is the one free-text field that reaches the driver's phone.
      { name: 'Driver Note', tier: 'DRIVER' },
      { name: 'Note', tier: 'OFFICE' }            // internal; never published
    ]
  },

  /**
   * Which stop a child uses. This is the answer to Lois's "most students don't get picked up at
   * their address" — the link that exists in no system today.
   */
  StudentStops: {
    key: 'Student ID',
    cols: [
      { name: 'Student ID', tier: 'SYSTEM' },     // NEVER published; `rk` goes out instead
      { name: 'Route Code', tier: 'DRIVER' },
      { name: 'Session', tier: 'DRIVER' },
      { name: 'Stop ID', tier: 'DRIVER' },
      { name: 'Days', tier: 'OFFICE' },           // resolved server-side; only today's riders publish
      { name: 'Note', tier: 'OFFICE' }
    ]
  },

  /**
   * A driver or sub. The PIN is the person; the token (Script Property DRIVER_TOKENS) is the
   * phone. Both are required and both are re-checked server-side on every call.
   */
  Drivers: {
    key: 'Driver ID',
    cols: [
      { name: 'Driver ID', tier: 'OFFICE' },
      { name: 'Name', tier: 'DRIVER' },           // the driver sees their own name, and today's driver
      { name: 'Phone', tier: 'OFFICE' },          // office-side only; drivers do not get each other's
      // '*' = every route. That is the DEFAULT and it is Lois's actual ask: "routes accessible to
      // all drivers and subs". A comma list scopes a regular driver if she ever wants that.
      { name: 'Routes', tier: 'OFFICE' },
      // base64(HMAC-SHA256(pin + '|' + driverId, SECRET)). The PIN itself is never stored,
      // never logged, never written to a sheet, and cannot be read back out of this.
      { name: 'PIN Hash', tier: 'SYSTEM' },
      { name: 'Active', tier: 'OFFICE' },         // 'N' cuts one person without touching their token
      { name: 'Note', tier: 'OFFICE' }
    ]
  },

  /**
   * Enrolled devices. One row per phone; the token is the `?k=` in that phone's link.
   *
   * WHY THE SHEET AND NOT SCRIPT PROPERTIES (where it started): the office app is a SEPARATE script
   * project and cannot read another project's properties, so with the tokens hidden there Lois could
   * never add or revoke a device — she would have to ask Josh for every new driver, which defeats
   * the point of giving her an interface.
   *
   * A token sitting in this sheet is not a credential on its own: opening the app also needs the
   * PIN, which is stored ONLY as an HMAC and cannot be read back out of the Drivers tab. Keep the
   * workbook shared narrowly all the same.
   */
  Devices: {
    key: 'Token',
    cols: [
      { name: 'Token', tier: 'SYSTEM' },      // never serialized to any client
      { name: 'Driver ID', tier: 'OFFICE' },
      { name: 'Device', tier: 'OFFICE' },     // 'Wade — iPhone'
      { name: 'Added', tier: 'OFFICE' },
      { name: 'Active', tier: 'OFFICE' },     // 'N' cuts this one phone, instantly
      { name: 'Note', tier: 'OFFICE' }
    ]
  },

  /**
   * Append-only audit log: who opened the app, when, and what they looked at.
   *
   * Exists to answer Lois's question "who is actually using this?" — which matters because
   * adoption will be partial and the office must be able to SEE that rather than infer it from
   * silence. Also carries failed PINs and lockouts, which is the only way a locked-out driver on
   * the roadside becomes visible to anyone.
   *
   * Driver Name is denormalised on purpose: this is a log, so it should record what was true at the
   * time, not what a later rename would make it.
   */
  Activity: {
    key: 'Event ID',
    cols: [
      { name: 'Event ID', tier: 'OFFICE' },
      { name: 'Timestamp', tier: 'OFFICE' },
      { name: 'Day Key', tier: 'OFFICE' },
      { name: 'Driver ID', tier: 'OFFICE' },
      { name: 'Driver Name', tier: 'OFFICE' },
      { name: 'Event', tier: 'OFFICE' },      // ACTIVITY_EVENTS
      { name: 'Detail', tier: 'OFFICE' }
    ]
  },

  /**
   * Append-only check-off events. The ONLY thing this project writes anywhere.
   * Never rewrite a row: a correction is a new row, and the fold takes the last one per (rk, stop).
   */
  Boarding: {
    key: 'Event ID',
    cols: [
      { name: 'Event ID', tier: 'OFFICE' },
      { name: 'Timestamp', tier: 'OFFICE' },      // ISO string — stringify before it leaves the server
      { name: 'Day Key', tier: 'OFFICE' },        // 'YYYY-MM-DD'; scopes the fold and the rk digest
      { name: 'Driver ID', tier: 'OFFICE' },
      { name: 'Route Code', tier: 'OFFICE' },
      { name: 'Session', tier: 'OFFICE' },
      { name: 'Stop ID', tier: 'OFFICE' },
      { name: 'Rider Key', tier: 'OFFICE' },      // the rk as the phone sent it
      { name: 'Student ID', tier: 'SYSTEM' },     // resolved office-side from the rk; never published
      { name: 'Action', tier: 'OFFICE' },         // BOARDING_ACTIONS
      { name: 'Source', tier: 'OFFICE' },         // 'driver' | 'office'
      { name: 'Note', tier: 'OFFICE' }
    ]
  }
};

/** Every column of a tab that may be serialized to `tier` or narrower. */
function colsForTier(tabName, tierName) {
  var tab = SCHEMA[tabName];
  if (!tab) throw new Error('Unknown tab: ' + tabName);
  var want = TIER[tierName];
  if (want === undefined) throw new Error('Unknown tier: ' + tierName);
  return tab.cols.filter(function (c) { return TIER[c.tier] <= want; })
                 .map(function (c) { return c.name; });
}

/** Header row for a tab, in declared order — what bootstrapSheets_ writes. */
function headerFor(tabName) {
  var tab = SCHEMA[tabName];
  if (!tab) throw new Error('Unknown tab: ' + tabName);
  return tab.cols.map(function (c) { return c.name; });
}

// Node test shim (GAS loads this file as globals; tools/wrap.js copies it into apps/*/server/lib/).

/* ===== stops.js ===== */
'use strict';
/**
 * stops.js — the stop sequence and the student→stop link. PURE.
 *
 * This is the only genuinely new data in the project. Lois's master transportation list carries
 * NO stops (it is Name / Grade / Route / Bus # / Notes, sorted by surname), FACTS has nowhere to
 * put them (/People/PickUpPoint returns 0 rows here), and the dismissal app never needed them.
 *
 * DESIGNED TO BE EMPTY. Phase 1 ships before a single stop exists: with no Stops rows every rider
 * resolves to the null stop and the driver gets a flat route list, which is already better than a
 * surname-sorted PDF. Phase 2 fills the tab and the same code regroups the same riders.
 */

/** Sequence numbers are gapped by 10 so a forgotten stop can be inserted without renumbering. */
var SEQ_GAP = 10;

/**
 * Weekday filter shared by stops and student→stop links.
 *
 * Blank means EVERY school day — the overwhelmingly common case, and the safe default: a stop that
 * silently applies to no days would strand a child. Mirrors dsDaysInclude in
 * ../transportation/Dismissal.gs:208, which the office already understands from the Standing tab
 * ("the Siverds ride SE Mon-Thu and are Car on Friday").
 *
 * @param {string} days   '' | 'Fri' | 'Mon,Wed,Thu,Fri'
 * @param {string} dayName 'Mon'..'Sun'
 */
function daysInclude(days, dayName) {
  var s = String(days == null ? '' : days).trim();
  if (!s) return true;
  var want = String(dayName || '').trim().slice(0, 3).toLowerCase();
  if (!want) return true;
  return s.split(',').some(function (tok) {
    return String(tok).trim().slice(0, 3).toLowerCase() === want;
  });
}

/** Parse Stops rows (already header-mapped objects) into ordered, active stops for route+session. */
function buildStops(rows, routeCode, session, dayName) {
  var code = String(routeCode || '').trim().toLowerCase();
  var sess = String(session || '').trim().toUpperCase();

  return (rows || [])
    .filter(function (r) {
      if (String(r['Active'] || '').trim().toUpperCase() === 'N') return false;
      if (String(r['Route Code'] || '').trim().toLowerCase() !== code) return false;
      if (String(r['Session'] || '').trim().toUpperCase() !== sess) return false;
      return daysInclude(r['Days'], dayName);
    })
    .map(function (r) {
      return {
        stopId: String(r['Stop ID'] || '').trim(),
        seq: Number(r['Seq']) || 0,
        name: String(r['Stop Name'] || '').trim(),
        landmark: String(r['Landmark'] || '').trim(),
        time: String(r['Time'] || '').trim(),
        // ABOUT THE PLACE, never about a child — the office UI says so at the input.
        driverNote: String(r['Driver Note'] || '').trim()
      };
    })
    .filter(function (s) { return !!s.stopId; })
    .sort(function (a, b) { return a.seq - b.seq || a.name.localeCompare(b.name); });
}

/**
 * {studentId: stopId} for one route+session on one weekday.
 *
 * A student with no row, or whose row is filtered out by Days, resolves to NO stop rather than to
 * a guessed one. They still appear on the manifest — under "stop not set" — because a child whose
 * paperwork is incomplete still has to get home. Never drop a rider for want of metadata.
 */
function buildStudentStops(rows, routeCode, session, dayName) {
  var code = String(routeCode || '').trim().toLowerCase();
  var sess = String(session || '').trim().toUpperCase();
  var out = {};

  (rows || []).forEach(function (r) {
    if (String(r['Route Code'] || '').trim().toLowerCase() !== code) return;
    if (String(r['Session'] || '').trim().toUpperCase() !== sess) return;
    if (!daysInclude(r['Days'], dayName)) return;
    var sid = String(r['Student ID'] || '').trim();
    var stopId = String(r['Stop ID'] || '').trim();
    if (sid && stopId) out[sid] = stopId;
  });

  return out;
}

/** The next sequence number for a route+session, leaving the gap. */
function nextSeq(stops) {
  var max = 0;
  (stops || []).forEach(function (s) { if (s.seq > max) max = s.seq; });
  return max + SEQ_GAP;
}

/**
 * Renumber a reordered list back onto clean gapped sequences. The office editor reorders by
 * dragging; this is what it writes back.
 */
function resequence(stops) {
  return (stops || []).map(function (s, i) {
    var copy = {};
    Object.keys(s).forEach(function (k) { copy[k] = s[k]; });
    copy.seq = (i + 1) * SEQ_GAP;
    return copy;
  });
}


/* ===== manifest.js ===== */
'use strict';
/**
 * manifest.js — turn a published route slice + the stop tables into what a driver actually sees.
 * PURE.
 *
 * The classification work is NOT done here and must never be re-implemented here. Who is riding,
 * who is absent, who left early, who was moved by an override, who has a standing answer — all of
 * that is already decided by ../transportation (dsBuildBoard and friends, ~254 assertions of tests)
 * and published as a slice every minute. This file only:
 *
 *   1. groups the slice's riders by stop,
 *   2. projects each rider through the EXPLICIT field allowlist, and
 *   3. refuses to imply certainty the data does not have.
 */

var _schema = null;
var _stops = null;

/**
 * Dependencies are resolved here, in ONE place, and a schema constant is never copied.
 *
 * THE REAL HAZARD IS DRIFT, not load order. This used to read
 *     var SESSION_HAS_ATTENDANCE = _schema ? _schema.SESSION_HAS_ATTENDANCE : { AM:false, PM:true };
 * — a second, hardcoded copy of a schema constant that GAS would silently prefer (there is no
 * module system there, so the fallback is the live path). Change schema.js, and the two disagree
 * with nothing to catch it. There is one definition, in schema.js, and this reads it.
 *
 * Load order is NOT the reason. Apps Script concatenates every file into one global scope and
 * hoists function declarations across all of it, so referencing buildStops from a file evaluated
 * earlier does work — verified by the GAS global-scope test, which passes either way. Resolving in
 * a function is simply tidier; do not claim it fixes a hoisting bug, because it does not.
 */
function _deps() {
  return {
    sessionHasAttendance: _schema ? _schema.SESSION_HAS_ATTENDANCE : SESSION_HAS_ATTENDANCE,
    buildStops: _stops ? _stops.buildStops : buildStops,
    buildStudentStops: _stops ? _stops.buildStudentStops : buildStudentStops
  };
}

/** Rendered where a stop has not been set yet. Phase 1 puts EVERY rider here, by design. */
var NO_STOP = { stopId: '', name: 'Stop not set', landmark: '', time: '', seq: 999999, driverNote: '' };

/**
 * Project one rider onto the driver's phone.
 *
 * NAMED FIELDS, ONE AT A TIME. Never `Object.assign({}, row)`, never a spread — that is exactly how
 * a student id, a phone number or a free-text note reaches an anonymous surface, and the
 * forbidden-field test in test/ exists to catch it. Same doctrine as dsRampSlice
 * (../transportation/Dismissal.gs:1225-1291), which has held this line since 2026-09-09.
 *
 * `rk` is the opaque per-day key, NOT the FACTS student id. See schema.js RIDER_KEY_NOTE.
 */
function projectRider(rider, rk, stopId) {
  return {
    rk: String(rk || ''),
    name: String(rider.name || ''),
    grade: String(rider.grade || ''),
    stopId: String(stopId || ''),
    expected: rider.expected !== false,
    reason: String(rider.reason || ''),
    detail: String(rider.detail || ''),
    flags: (rider.flags || []).map(String)
  };
}

/**
 * Build the manifest for ONE route and ONE session.
 *
 * @param {Object} opts
 *   slice        the published route object: {code, name, colour, vehicle, drivers[], riding[], notRiding[]}
 *   stopRows     raw Stops rows (header-mapped). May be EMPTY — Phase 1 runs this way.
 *   linkRows     raw StudentStops rows. May be EMPTY.
 *   rkOf         function(studentId) -> rk. Injected so the secret never reaches this file.
 *   session      'AM' | 'PM'
 *   dayName      'Mon'..'Fri'
 */
function buildManifest(opts) {
  opts = opts || {};
  var slice = opts.slice || {};
  var session = String(opts.session || 'PM').toUpperCase();
  var dayName = opts.dayName || '';
  var rkOf = opts.rkOf || function (sid) { return String(sid || ''); };
  var routeCode = slice.code || '';
  var dep = _deps();

  var stops = dep.buildStops(opts.stopRows || [], routeCode, session, dayName);
  var stopOf = dep.buildStudentStops(opts.linkRows || [], routeCode, session, dayName);

  // Buckets in stop order, plus the catch-all. The catch-all is LAST so a driver reads the route
  // in sequence and finds the unplaced children at the end rather than interleaved.
  var buckets = {}, order = [];
  stops.forEach(function (s) {
    buckets[s.stopId] = { stop: s, riders: [] };
    order.push(s.stopId);
  });
  buckets[NO_STOP.stopId] = { stop: NO_STOP, riders: [] };

  (slice.riding || []).forEach(function (r) {
    var sid = r.id || r.studentId || '';
    var stopId = stopOf[sid] || '';
    // A rider pointed at a retired or filtered-out stop falls back to the catch-all rather than
    // vanishing into a bucket nobody renders.
    if (!buckets[stopId]) stopId = NO_STOP.stopId;
    buckets[stopId].riders.push(projectRider(r, rkOf(sid), stopId));
  });

  var stopList = order.concat([NO_STOP.stopId])
    .map(function (id) { return buckets[id]; })
    .filter(function (b) { return b.riders.length > 0 || b.stop.stopId; });

  // Not-riding is a FLAT list, deliberately never grouped by stop: its whole purpose is "do not
  // wait", and a driver should be able to read all of it at once without walking the route.
  var notRiding = (slice.notRiding || []).map(function (r) {
    return projectRider(r, rkOf(r.id || r.studentId || ''), '');
  }).map(function (r) { r.expected = false; return r; });

  return {
    code: routeCode,
    name: slice.name || routeCode || 'Route',
    // The colour is a safety mechanism, not decoration: the vehicle shows a colour in its window
    // and each child carries a matching stick. The NAME ships alongside the swatch for colour-blind
    // readers and mono printing (../transportation/Routes.gs:7).
    colour: slice.colour || '',
    vehicle: slice.vehicle || '',
    session: session,
    dayName: dayName,
    drivers: (slice.drivers || []).map(function (d) { return { name: String(d.name || '') }; }),
    stops: stopList,
    notRiding: notRiding,
    ridingCount: (slice.riding || []).length,

    // Tells the page whether it may show "do not wait" at all. FALSE all morning: a child absent
    // today is not known until a teacher marks them, which happens after the AM run. The page
    // says so out loud rather than implying an empty notRiding means everybody is coming.
    hasAttendance: dep.sessionHasAttendance[session] === true,

    // TRUE until Lois has entered stops for this route. The page renders a flat list and explains
    // why, instead of showing an unexplained "Stop not set" header over every child.
    stopsUnset: stops.length === 0
  };
}

/**
 * Fold boarding events into {rk: action} for one route+session+day.
 *
 * Append-only: a correction is a NEW row, and the last row per (rk, stop) wins. Never rewrite.
 *
 * THE HONESTY RULE: an rk absent from this map is NOT RECORDED. It is not "not on the bus". Every
 * caller renders it that way and no count derived from this may be presented as a headcount.
 */
function foldBoarding(rows, routeCode, session, dayKey) {
  var code = String(routeCode || '').trim().toLowerCase();
  var sess = String(session || '').trim().toUpperCase();
  var day = String(dayKey || '').trim();
  var out = {};

  (rows || []).forEach(function (r) {
    if (String(r['Day Key'] || '').trim() !== day) return;
    if (String(r['Route Code'] || '').trim().toLowerCase() !== code) return;
    if (String(r['Session'] || '').trim().toUpperCase() !== sess) return;
    var rk = String(r['Rider Key'] || '').trim();
    if (!rk) return;
    out[rk] = { action: String(r['Action'] || '').trim(), at: String(r['Timestamp'] || '') };
  });

  return out;
}


/* ===== office.js ===== */
'use strict';
/**
 * office.js — the folds behind Lois's view. PURE.
 *
 * The load-bearing idea in this file is CHECK_STATE. Everything else is bookkeeping.
 */

var _oschema = null;

function _oc() {
  return {
    CHECK_STATE: _oschema ? _oschema.CHECK_STATE : CHECK_STATE,
    BOARDING_ACTIONS: _oschema ? _oschema.BOARDING_ACTIONS : BOARDING_ACTIONS,
    ACTIVITY_EVENTS: _oschema ? _oschema.ACTIVITY_EVENTS : ACTIVITY_EVENTS
  };
}

/**
 * Decide what we actually know about one route's check-off today.
 *
 * THE WHOLE POINT: distinguish "nobody has checked this route" from "the children did not board".
 * Those produce identical raw numbers (zero) and opposite conclusions. A route with no events is
 * NOT_CHECKED and must never be rendered as a zero — the office does not know, and the screen has
 * to say it does not know.
 *
 * @param {number} expected  riders the roster expects on this route today
 * @param {Object} fold      foldBoarding output: {rk: {action, at}}
 */
function checkState(expected, fold) {
  var C = _oc();
  var keys = Object.keys(fold || {});
  if (!keys.length) return C.CHECK_STATE.NOT_CHECKED;
  if (expected > 0 && keys.length >= expected) return C.CHECK_STATE.COMPLETE;
  return C.CHECK_STATE.IN_PROGRESS;
}

/** Tally one route's fold by action. Only meaningful when the state is not NOT_CHECKED. */
function boardingTally(fold) {
  var C = _oc();
  var out = { on: 0, off: 0, noShow: 0, recorded: 0 };
  Object.keys(fold || {}).forEach(function (rk) {
    var a = (fold[rk] || {}).action;
    out.recorded++;
    if (a === C.BOARDING_ACTIONS.ON) out.on++;
    else if (a === C.BOARDING_ACTIONS.OFF) out.off++;
    else if (a === C.BOARDING_ACTIONS.NO_SHOW) out.noShow++;
  });
  return out;
}

/**
 * The human sentence for a state. Kept here, next to the enum, so every surface says the same
 * thing — the office UI, a future email digest, and any report.
 */
function checkStateLabel(state, tally, expected) {
  var C = _oc();
  if (state === C.CHECK_STATE.NOT_CHECKED) return 'Not checked — no record either way';
  var n = (tally && tally.recorded) || 0;
  if (state === C.CHECK_STATE.COMPLETE) return 'All ' + n + ' recorded';
  return n + ' of ' + expected + ' recorded so far';
}

/**
 * Per-driver adoption, so Lois can see who is actually getting value out of this rather than
 * guessing from silence.
 *
 * `lastLogin` is the honest measure of use. `boardingDays` counts DISTINCT DAYS a driver recorded
 * anything, not raw events — one driver ticking 30 children on one day is not more adoption than
 * another ticking 12 children on each of five days.
 *
 * @param {Array} drivers      Drivers rows
 * @param {Array} activityRows Activity rows
 * @param {Array} boardingRows Boarding rows
 * @param {Object} tokensByDriver {driverId: deviceCount}
 */
function driverAdoption(drivers, activityRows, boardingRows, tokensByDriver) {
  var C = _oc();
  var byId = {};

  (drivers || []).forEach(function (d) {
    var id = String(d['Driver ID'] || '').trim();
    if (!id) return;
    byId[id] = {
      driverId: id,
      name: String(d['Name'] || ''),
      routes: String(d['Routes'] || '*'),
      active: String(d['Active'] || '').trim().toUpperCase() !== 'N',
      hasPin: !!String(d['PIN Hash'] || '').trim(),
      devices: (tokensByDriver || {})[id] || 0,
      lastLogin: '', logins: 0, failures: 0, lockouts: 0,
      boardingDays: 0, lastBoarding: ''
    };
  });

  (activityRows || []).forEach(function (r) {
    var d = byId[String(r['Driver ID'] || '').trim()];
    if (!d) return;
    var ev = String(r['Event'] || '').trim(), ts = String(r['Timestamp'] || '');
    if (ev === C.ACTIVITY_EVENTS.LOGIN) {
      d.logins++;
      if (ts > d.lastLogin) d.lastLogin = ts;
    } else if (ev === C.ACTIVITY_EVENTS.LOGIN_FAILED) d.failures++;
    else if (ev === C.ACTIVITY_EVENTS.LOCKED) d.lockouts++;
  });

  var days = {};
  (boardingRows || []).forEach(function (r) {
    var id = String(r['Driver ID'] || '').trim();
    var d = byId[id];
    if (!d) return;
    var day = String(r['Day Key'] || '');
    (days[id] = days[id] || {})[day] = true;
    var ts = String(r['Timestamp'] || '');
    if (ts > d.lastBoarding) d.lastBoarding = ts;
  });
  Object.keys(days).forEach(function (id) {
    if (byId[id]) byId[id].boardingDays = Object.keys(days[id]).length;
  });

  return Object.keys(byId).map(function (id) { return byId[id]; })
    .sort(function (a, b) { return a.name.localeCompare(b.name); });
}

/** The most recent activity rows, newest first, for the office log view. */
function recentActivity(activityRows, limit) {
  return (activityRows || [])
    .slice()
    .sort(function (a, b) {
      return String(b['Timestamp'] || '').localeCompare(String(a['Timestamp'] || ''));
    })
    .slice(0, limit || 200)
    .map(function (r) {
      return {
        at: String(r['Timestamp'] || ''),
        dayKey: String(r['Day Key'] || ''),
        driverId: String(r['Driver ID'] || ''),
        name: String(r['Driver Name'] || ''),
        event: String(r['Event'] || ''),
        detail: String(r['Detail'] || '')
      };
    });
}

/**
 * Which routes have nobody driving them on a given weekday.
 *
 * Reports "no driver for <day>" separately from "no Routes row", because they are different
 * problems: the first is a coverage gap to chase, the second is a data gap. Conflating them is
 * how a real Tuesday gap gets dismissed as "oh that's just RL again".
 */
function coverageGaps(routes, dayName) {
  var noColour = [], noDriver = [];
  (routes || []).forEach(function (r) {
    if (!r.colour) noColour.push(r.code);
    if (!(r.drivers || []).length) noDriver.push(r.code);
  });
  var isSchoolDay = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'].indexOf(String(dayName || '')) !== -1;
  return { noColour: noColour, noDriver: noDriver, dayName: dayName || '', isSchoolDay: isSchoolDay };
}


/* ===== auth.js ===== */
'use strict';
/**
 * auth.js — PIN hashing, session minting and the attempt limiter. PURE.
 *
 * Every function here takes its crypto as an injected `hmac` so the identical source runs in GAS
 * (Utilities.computeHmacSha256Signature + base64Encode) and in Node (crypto.createHmac) and is
 * therefore actually testable. Same trick as ../transportation/Dismissal.gs being pure.
 *
 *   hmac(message: string, secret: string) -> base64 string
 *
 * THE MODEL: the token in ?k= says WHICH PHONE. The PIN says WHICH PERSON. Both are required and
 * both are re-checked server-side on every single call, because google.script.run reaches any
 * global in the project regardless of what the page is showing (proven live in talon-hub
 * 2026-07-19). A hidden button is presentation, not a permission check.
 *
 * WHAT THIS DELIBERATELY DOES THAT League Soccer/Public-Code.gs:249 DOES NOT:
 *   - the secret is never the thing compared; only digests are
 *   - sessions carry an expiry and it is enforced
 *   - failed attempts are counted and lock out
 * That file mints a 4-digit OTP with no expiry, no attempt limit, and one Script Property per
 * email address. Do not copy it.
 */

/** A PIN is 4-6 digits. Short enough to type at a bus door in the rain, long enough with a limiter. */
var PIN_MIN_LEN = 4;
var PIN_MAX_LEN = 6;

/** Wrong PINs allowed per device token before lockout, and how long the window/lockout lasts. */
var PIN_MAX_ATTEMPTS = 5;
var PIN_ATTEMPT_WINDOW_SEC = 15 * 60;

/** Sessions die at end of day regardless; this caps a session opened late at night. */
var SESSION_MAX_HOURS = 14;

var SESSION_VERSION = 'v1';

/**
 * Constant-time string compare.
 *
 * A plain `a === b` on a digest leaks, through timing, how many leading characters matched — which
 * over enough tries recovers the digest a byte at a time. The cost of not caring is unbounded; the
 * cost of caring is this function. Always compare digests with it.
 */
function safeEqual(a, b) {
  a = String(a == null ? '' : a);
  b = String(b == null ? '' : b);
  // Compare over a fixed length so an early length mismatch does not short-circuit.
  var len = Math.max(a.length, b.length);
  var diff = a.length ^ b.length;
  for (var i = 0; i < len; i++) {
    diff |= (a.charCodeAt(i) || 0) ^ (b.charCodeAt(i) || 0);
  }
  return diff === 0;
}

/** True for a syntactically acceptable PIN. Says nothing about whether it is the RIGHT pin. */
function isValidPinFormat(pin) {
  var s = String(pin == null ? '' : pin);
  return new RegExp('^[0-9]{' + PIN_MIN_LEN + ',' + PIN_MAX_LEN + '}$').test(s);
}

/**
 * The stored form of a PIN. This is what goes in Drivers!'PIN Hash' — the PIN itself is never
 * stored, never logged, and cannot be recovered from this.
 *
 * driverId is in the digest so the same PIN held by two drivers produces two different hashes:
 * without it, "1234" hashes identically for everyone and the sheet becomes a lookup table.
 */
function pinHash(pin, driverId, secret, hmac) {
  if (!isValidPinFormat(pin)) throw new Error('PIN must be ' + PIN_MIN_LEN + '-' + PIN_MAX_LEN + ' digits.');
  if (!driverId) throw new Error('pinHash needs a driverId.');
  if (!secret) throw new Error('pinHash needs a secret.');
  return hmac(String(pin) + '|' + String(driverId), secret);
}

/** Verify a typed PIN against the stored hash. Never throws on a bad PIN — returns false. */
function verifyPin(pin, driverId, storedHash, secret, hmac) {
  if (!isValidPinFormat(pin) || !driverId || !storedHash) return false;
  var got;
  try { got = pinHash(pin, driverId, secret, hmac); }
  catch (e) { return false; }
  return safeEqual(got, storedHash);
}

/**
 * The attempt limiter, expressed purely: the caller owns the counter (CacheService server-side,
 * keyed by DEVICE TOKEN so one phone cannot brute-force, and so one driver's fat fingers never
 * lock out a different driver's phone).
 *
 * @param {number} attemptsSoFar  failures already recorded in the window, BEFORE this one
 * @return {{allowed:boolean, remaining:number, lockedOut:boolean}}
 */
function attemptVerdict(attemptsSoFar, maxAttempts) {
  var max = maxAttempts || PIN_MAX_ATTEMPTS;
  var used = Math.max(0, Number(attemptsSoFar) || 0);
  var lockedOut = used >= max;
  return {
    allowed: !lockedOut,
    remaining: Math.max(0, max - used),
    lockedOut: lockedOut
  };
}

/**
 * Mint a session after a correct PIN.
 *
 * Format: v1.<driverId>.<expiryMs>.<nonce>.<sig>   — signature covers all of the preceding parts,
 * so a phone cannot extend its own expiry or promote itself to another driver by editing
 * localStorage. There is no server-side session table on purpose: nothing to grow, nothing to
 * clean up, and a rotated SECRET invalidates every outstanding session at once.
 *
 * @param {number} nowMs
 * @param {number} expiresAtMs  caller decides (end of school day), capped at SESSION_MAX_HOURS
 * @param {string} nonce        caller supplies (Utilities.getUuid) — makes two sessions differ
 */
function mintSession(driverId, nowMs, expiresAtMs, nonce, secret, hmac) {
  if (!driverId) throw new Error('mintSession needs a driverId.');
  if (String(driverId).indexOf('.') !== -1) throw new Error('driverId must not contain "."');
  if (!nonce) throw new Error('mintSession needs a nonce.');
  var cap = Number(nowMs) + SESSION_MAX_HOURS * 3600 * 1000;
  var exp = Math.min(Number(expiresAtMs), cap);
  if (!(exp > Number(nowMs))) throw new Error('Session would already be expired.');
  var body = [SESSION_VERSION, driverId, exp, nonce].join('.');
  return body + '.' + hmac(body, secret);
}

/**
 * Verify a session presented by a phone.
 *
 * Order matters: check the SIGNATURE before the expiry. An unsigned token's expiry field is
 * attacker-controlled and reading it first would mean trusting it.
 *
 * @return {{ok:boolean, driverId?:string, reason?:string}}
 */
function verifySession(token, nowMs, secret, hmac) {
  var parts = String(token == null ? '' : token).split('.');
  if (parts.length !== 5) return { ok: false, reason: 'malformed' };
  if (parts[0] !== SESSION_VERSION) return { ok: false, reason: 'version' };

  var body = parts.slice(0, 4).join('.');
  if (!safeEqual(hmac(body, secret), parts[4])) return { ok: false, reason: 'signature' };

  var exp = Number(parts[2]);
  if (!isFinite(exp)) return { ok: false, reason: 'malformed' };
  if (Number(nowMs) >= exp) return { ok: false, reason: 'expired' };

  return { ok: true, driverId: parts[1] };
}

/**
 * The opaque per-day rider key that replaces the FACTS student id on the driver's phone.
 * See schema.js RIDER_KEY_NOTE. dayKey is inside the digest, so these rotate daily.
 */
function riderKey(studentId, dayKey, secret, hmac) {
  if (!studentId) throw new Error('riderKey needs a studentId.');
  if (!dayKey) throw new Error('riderKey needs a dayKey.');
  return hmac(String(studentId) + '|' + String(dayKey), secret).slice(0, 16);
}

/**
 * Reverse a rider key, office-side, by rebuilding the map for the day. There is no maths that
 * inverts an HMAC — that is the point — so the office recomputes rk for every student it already
 * knows and looks the answer up.
 *
 * @param {Array<string>} studentIds  the candidate universe (today's roster)
 * @return {Object} {rk: studentId}
 */
function riderKeyMap(studentIds, dayKey, secret, hmac) {
  var out = {};
  (studentIds || []).forEach(function (sid) {
    if (sid) out[riderKey(sid, dayKey, secret, hmac)] = String(sid);
  });
  return out;
}

/** 'YYYY-MM-DD' from a Date already in the school's timezone. */
function dayKeyFromDate(d) {
  var p = function (n) { return (n < 10 ? '0' : '') + n; };
  return d.getFullYear() + '-' + p(d.getMonth() + 1) + '-' + p(d.getDate());
}


  global.TRANSPO_LOGIC = {
    buildManifest: buildManifest, projectRider: projectRider, foldBoarding: foldBoarding,
    buildStops: buildStops, buildStudentStops: buildStudentStops, resequence: resequence,
    checkState: checkState, boardingTally: boardingTally, checkStateLabel: checkStateLabel,
    driverAdoption: driverAdoption, recentActivity: recentActivity, coverageGaps: coverageGaps,
    CHECK_STATE: CHECK_STATE, DRIVER_RIDER_FIELDS: DRIVER_RIDER_FIELDS,
    FORBIDDEN_RIDER_FIELDS: FORBIDDEN_RIDER_FIELDS
  };
})(window);
