// build-logic.mjs — vendor the REAL server code of the conference scheduler into the demo.
//
//   node demos/conferences/build-logic.mjs
//
// The source project keeps its rules in plain Apps Script files that read and write Google
// Sheets through SpreadsheetApp. Rather than re-implement booking, blocking, the slot grid and
// the grade-tier roster rules in mock.js (a drawing of the app), the demo loads those files
// VERBATIM and hands them an in-memory stand-in for the spreadsheet (mock.js). So a parent's
// booking goes through the app's own bookSlot re-check, a teacher's block through its own
// setTeacherBlock refusal, and each child's conference list through its own syncRoster tiers.
//
// The six files are wrapped in one function so the Apps Script globals they expect
// (SpreadsheetApp, LockService, Session, Utilities, Logger, sendBookingEmail_) can be supplied
// by the demo instead of by Google. Nothing inside the wrapper is edited.
//
// Exits 0 with a SKIP if the source project isn't checked out beside this repo.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { aliasStaffNames, aliasPhrases, PHRASE_ALIASES } from '../../tools/staff-aliases.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const SRC = path.resolve(HERE, '../../../parent-teacher-conference-scheduling');

// Order is cosmetic — GAS hoists function declarations across the whole project, and so does
// the wrapper function below.
export const FILES = ['Settings.js', 'BookingService.js', 'ParentView.js', 'TeacherView.js',
                      'FactsData.js', 'RosterSync.js'];

// The names the wrapper exposes to mock.js. Every one is a function the source declares.
export const EXPORTS = [
  'getSettings', 'getConferenceDates', 'slotLengthForGrade', 'generateSlots_', 'overlaps_',
  'findStudentsByGuardianEmail_', 'getStudentAvailabilityGrid', 'submitBookings', 'cancelBooking',
  'getTeacherGrid', 'getCurrentTeacherGrid', 'saveTeacherBlockChanges', 'setTeacherBlock',
  'syncRoster', 'syncTeachers', 'conferenceTier_', 'sheetRows_'
];

export function buildLogic() {
  const parts = FILES.map((f) => {
    let body = readFileSync(path.join(SRC, f), 'utf8').replace(/\r\n?/g, '\n');
    // Real staff first names in source comments become role aliases — the one deliberate
    // departure from verbatim (verify.mjs applies the same transform before comparing).
    body = aliasStaffNames(aliasPhrases(body, PHRASE_ALIASES).text).text;
    return `/* ===== ${f} ===== */\n` + body;
  });
  return [
    '/* GENERATED by demos/conferences/build-logic.mjs — do not edit.',
    "   This is the SOURCE PROJECT'S OWN server code, verbatim: Settings, BookingService, ParentView,",
    '   TeacherView, FactsData and RosterSync. The demo runs it in the browser against an in-memory',
    '   spreadsheet (mock.js), so every booking, block, slot grid and per-child conference list is the',
    "   app's real behaviour and cannot drift from it. Re-run the script after any change upstream. */",
    '(function (global) {',
    '  // Apps Script globals the source expects — bound by mock.js before the first call.',
    '  var SpreadsheetApp, LockService, Session, Utilities, Logger, sendBookingEmail_;',
    ...parts,
    '  global.PTC_LOGIC = {',
    '    bind: function (env) {',
    '      SpreadsheetApp = env.SpreadsheetApp; LockService = env.LockService; Session = env.Session;',
    '      Utilities = env.Utilities; Logger = env.Logger; sendBookingEmail_ = env.sendBookingEmail_;',
    '    },',
    ...EXPORTS.map((n, i) => `    ${n}: ${n}${i < EXPORTS.length - 1 ? ',' : ''}`),
    '  };',
    '})(typeof window !== "undefined" ? window : globalThis);',
    ''
  ].join('\n');
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  if (!existsSync(SRC)) { console.log('SKIP build-logic: source project not found at', SRC); process.exit(0); }
  const out = buildLogic();
  writeFileSync(path.join(HERE, 'logic.js'), out);
  console.log('built demos/conferences/logic.js (' + out.length + ' bytes) from', FILES.length, 'source files');
}
