/* GENERATED by demos/conferences/build-logic.mjs — do not edit.
   This is the SOURCE PROJECT'S OWN server code, verbatim: Settings, BookingService, ParentView,
   TeacherView, FactsData and RosterSync. The demo runs it in the browser against an in-memory
   spreadsheet (mock.js), so every booking, block, slot grid and per-child conference list is the
   app's real behaviour and cannot drift from it. Re-run the script after any change upstream. */
(function (global) {
  // Apps Script globals the source expects — bound by mock.js before the first call.
  var SpreadsheetApp, LockService, Session, Utilities, Logger, sendBookingEmail_;
/* ===== Settings.js ===== */
/** Settings tab layout: key/value pairs in columns A:B. */

function getSettingsSheet_() {
  return SpreadsheetApp.getActive().getSheetByName('Settings');
}

function getSettings() {
  var sheet = getSettingsSheet_();
  var values = sheet.getDataRange().getValues();
  var settings = {};
  for (var i = 0; i < values.length; i++) {
    var key = values[i][0];
    if (key) settings[key] = values[i][1];
  }
  settings.SlotLengthElementary = Number(settings.SlotLengthElementary) || 20;
  settings.SlotLengthSecondary = Number(settings.SlotLengthSecondary) || 15;
  settings.GradeBandCutoff = Number(settings.GradeBandCutoff) || 6;
  settings.DayStartTime = toTimeKey_(settings.DayStartTime);
  settings.DayEndTime = toTimeKey_(settings.DayEndTime);
  return settings;
}

/**
 * Sheets auto-formats a typed "13:00" as a time-of-day value, which comes
 * back from getValues() as a Date object (epoch 1899-12-30) rather than a
 * string — normalize either form to a plain "HH:mm" string.
 */
function toTimeKey_(value) {
  if (!value) return '';
  if (Object.prototype.toString.call(value) === '[object Date]') {
    return Utilities.formatDate(value, Session.getScriptTimeZone(), 'HH:mm');
  }
  return String(value).trim();
}

/**
 * Accepts either a student grade (number-ish, K4/K5 treated as elementary)
 * or a teacher's literal GradeBand ('Elem' / 'Secondary').
 */
function slotLengthForGrade(grade) {
  var settings = getSettings();
  if (grade === 'Elem') return settings.SlotLengthElementary;
  if (grade === 'Secondary') return settings.SlotLengthSecondary;
  var gradeNum = parseInt(grade, 10);
  if (isNaN(gradeNum)) gradeNum = 0; // treat K / non-numeric as elementary
  return gradeNum > settings.GradeBandCutoff ? settings.SlotLengthSecondary : settings.SlotLengthElementary;
}

function toDateKey_(value) {
  if (!value) return '';
  if (Object.prototype.toString.call(value) === '[object Date]') {
    return Utilities.formatDate(value, Session.getScriptTimeZone(), 'yyyy-MM-dd');
  }
  return String(value).trim();
}

function getConferenceDates() {
  var settings = getSettings();
  return [toDateKey_(settings.ConferenceDate1), toDateKey_(settings.ConferenceDate2)].filter(function (d) { return d; });
}

/* ===== BookingService.js ===== */
function getSheet_(name) {
  return SpreadsheetApp.getActive().getSheetByName(name);
}

function sheetRows_(name) {
  var sheet = getSheet_(name);
  var values = sheet.getDataRange().getValues();
  var headers = values[0];
  var rows = [];
  for (var r = 1; r < values.length; r++) {
    var obj = {};
    headers.forEach(function (h, i) { obj[h] = values[r][i]; });
    obj._row = r + 1;
    rows.push(obj);
  }
  return rows;
}

function getTeacherByEmail_(email) {
  var teachers = sheetRows_('Teachers');
  for (var i = 0; i < teachers.length; i++) {
    if (String(teachers[i].Email).trim().toLowerCase() === String(email).trim().toLowerCase()) {
      return teachers[i];
    }
  }
  return null;
}

/**
 * A sheet cell typed/pasted as a time (e.g. "13:00") can get auto-formatted
 * by Sheets as a time-of-day value, which getValues() then returns as a
 * Date object (epoch 1899-12-30) instead of the original string — accept
 * either form.
 */
function timeToMinutes_(hhmm) {
  if (Object.prototype.toString.call(hhmm) === '[object Date]') {
    return hhmm.getHours() * 60 + hhmm.getMinutes();
  }
  var parts = String(hhmm).split(':');
  return parseInt(parts[0], 10) * 60 + parseInt(parts[1], 10);
}

function minutesToTime_(mins) {
  var h = Math.floor(mins / 60);
  var m = mins % 60;
  return (h < 10 ? '0' + h : h) + ':' + (m < 10 ? '0' + m : m);
}

function generateSlots_(startTime, endTime, slotLengthMinutes) {
  var slots = [];
  var start = timeToMinutes_(startTime);
  var end = timeToMinutes_(endTime);
  for (var t = start; t + slotLengthMinutes <= end; t += slotLengthMinutes) {
    slots.push({ start: minutesToTime_(t), end: minutesToTime_(t + slotLengthMinutes) });
  }
  return slots;
}

function getBlocksForTeacher_(teacherEmail) {
  return sheetRows_('Blocks').filter(function (b) {
    return String(b.TeacherEmail).trim().toLowerCase() === String(teacherEmail).trim().toLowerCase();
  });
}

function getBookingsForTeacher_(teacherEmail) {
  return sheetRows_('Bookings').filter(function (b) {
    return String(b.TeacherEmail).trim().toLowerCase() === String(teacherEmail).trim().toLowerCase();
  });
}

/**
 * Open slots for a teacher across all conference dates, at the slot length
 * appropriate for the given student grade.
 */
function getOpenSlotsForTeacher(teacherEmail, grade) {
  var settings = getSettings();
  var dates = getConferenceDates();
  var slotLength = slotLengthForGrade(grade);
  var blocks = getBlocksForTeacher_(teacherEmail);
  var bookings = getBookingsForTeacher_(teacherEmail);

  var open = [];
  dates.forEach(function (date) {
    var slots = generateSlots_(settings.DayStartTime, settings.DayEndTime, slotLength);
    slots.forEach(function (slot) {
      var taken = blocks.concat(bookings).some(function (b) {
        return toDateKey_(b.Date) === date && overlaps_(slot, b);
      });
      if (!taken) open.push({ date: date, start: slot.start, end: slot.end });
    });
  });
  return open;
}

function overlaps_(slotA, slotB) {
  var aStart = timeToMinutes_(slotA.start);
  var aEnd = timeToMinutes_(slotA.end);
  var bStart = timeToMinutes_(slotB.StartTime || slotB.start);
  var bEnd = timeToMinutes_(slotB.EndTime || slotB.end);
  return aStart < bEnd && bStart < aEnd;
}

/**
 * Books a slot, guarding against a race with LockService and re-checking
 * the slot is still open (not blocked/booked by someone else in the meantime).
 */
function bookSlot(booking) {
  var lock = LockService.getScriptLock();
  lock.waitLock(10000);
  try {
    var stillOpen = getOpenSlotsForTeacher(booking.teacherEmail, booking.grade).some(function (s) {
      return s.date === booking.date && s.start === booking.start && s.end === booking.end;
    });
    if (!stillOpen) {
      return { success: false, message: 'That slot was just taken. Please pick another.' };
    }
    var sheet = getSheet_('Bookings');
    sheet.appendRow([
      booking.date, booking.start, booking.end, booking.teacherEmail, booking.teacherName,
      booking.studentFirst, booking.studentLast, booking.grade, booking.parentName, booking.parentEmail,
      new Date(), booking.subject || '', booking.rosterRow || ''
    ]);
    sendBookingEmail_(booking, 'confirmation');
    return { success: true };
  } finally {
    lock.releaseLock();
  }
}

/**
 * Cancels a booking so the slot (and that teacher, since a parent can only
 * book each teacher once per visit) becomes available again. When the
 * booking row has a RosterRow (set on every booking made since that column
 * was added), the cancel must be for that same student — closes the gap
 * where any client call with the right date/start/teacher could otherwise
 * cancel a different student's booking. Older rows saved before RosterRow
 * existed fall back to the original date+start+teacher-only match.
 */
function cancelBookingByDetails(date, start, teacherEmail, rosterRow) {
  var lock = LockService.getScriptLock();
  lock.waitLock(10000);
  try {
    var bookings = sheetRows_('Bookings');
    var match = bookings.filter(function (b) {
      if (toDateKey_(b.Date) !== date || toTimeKey_(b.StartTime) !== start ||
        String(b.TeacherEmail).trim().toLowerCase() !== String(teacherEmail).trim().toLowerCase()) {
        return false;
      }
      return !b.RosterRow || String(b.RosterRow) === String(rosterRow);
    })[0];
    if (!match) {
      return { success: false, message: 'That booking was not found — it may have already been canceled.' };
    }
    getSheet_('Bookings').deleteRow(match._row);
    return { success: true };
  } finally {
    lock.releaseLock();
  }
}

/**
 * Sets a teacher block to an explicit desired state (idempotent — safe to
 * call with the same desired state twice), rather than an ambiguous toggle
 * that depends on the caller's assumption of current state matching the
 * server. Refuses to block a slot that's already booked by a parent.
 */
function setTeacherBlock(teacherEmail, date, start, end, desiredBlocked) {
  var lock = LockService.getScriptLock();
  lock.waitLock(10000);
  try {
    var bookings = getBookingsForTeacher_(teacherEmail);
    var isBooked = bookings.some(function (b) {
      return toDateKey_(b.Date) === date && toTimeKey_(b.StartTime) === start && toTimeKey_(b.EndTime) === end;
    });
    if (isBooked) {
      return { success: false, message: 'That slot is already booked by a parent and cannot be blocked.' };
    }

    var sheet = getSheet_('Blocks');
    var blocks = sheetRows_('Blocks');
    var existing = blocks.filter(function (b) {
      return String(b.TeacherEmail).trim().toLowerCase() === teacherEmail.trim().toLowerCase() &&
        toDateKey_(b.Date) === date && toTimeKey_(b.StartTime) === start && toTimeKey_(b.EndTime) === end;
    })[0];

    if (desiredBlocked && !existing) {
      sheet.appendRow([teacherEmail, date, start, end]);
    } else if (!desiredBlocked && existing) {
      sheet.deleteRow(existing._row);
    }
    return { success: true, blocked: desiredBlocked };
  } finally {
    lock.releaseLock();
  }
}

/**
 * Full grid for a teacher's own view: every slot across both conference
 * dates, tagged open/blocked/booked.
 */
function getTeacherGrid(teacherEmail) {
  var teacher = getTeacherByEmail_(teacherEmail);
  if (!teacher) return null;

  var settings = getSettings();
  var dates = getConferenceDates();
  var slotLength = slotLengthForGrade(teacher.GradeBand);
  var blocks = getBlocksForTeacher_(teacherEmail);
  var bookings = getBookingsForTeacher_(teacherEmail);

  var grid = dates.map(function (date) {
    var slots = generateSlots_(settings.DayStartTime, settings.DayEndTime, slotLength).map(function (slot) {
      var booking = bookings.filter(function (b) {
        return toDateKey_(b.Date) === date && overlaps_(slot, b);
      })[0];
      var blocked = blocks.some(function (b) {
        return toDateKey_(b.Date) === date && overlaps_(slot, b);
      });
      var status = booking ? 'booked' : (blocked ? 'blocked' : 'open');
      return {
        start: slot.start,
        end: slot.end,
        status: status,
        studentName: booking ? (booking.StudentFirst + ' ' + booking.StudentLast) : ''
      };
    });
    return { date: date, slots: slots };
  });

  return { teacher: { name: teacher.Name, email: teacher.Email, room: teacher.Room }, grid: grid };
}

/* ===== ParentView.js ===== */
function studentSummary_(s) {
  var guardians = s.GuardiansJSON ? JSON.parse(s.GuardiansJSON) : [];
  return {
    rosterRow: s._row,
    studentFirst: s.StudentFirst,
    studentLast: s.StudentLast,
    grade: s.Grade,
    parentName: s.ParentName,
    parentEmail: s.ParentEmail,
    guardians: guardians
  };
}

/**
 * Looks up every student linked to a guardian with this exact email
 * (case-insensitive) — a guardian with multiple kids gets all of them back
 * in one search. Used by the login flow (Auth.js) once an email is verified
 * via emailed code, not called directly from the client.
 */
function findStudentsByGuardianEmail_(email) {
  var target = String(email).trim().toLowerCase();
  if (!target) return [];

  var matches = sheetRows_('Roster').filter(function (s) {
    var guardians = s.GuardiansJSON ? JSON.parse(s.GuardiansJSON) : [];
    return guardians.some(function (g) { return String(g.email).trim().toLowerCase() === target; });
  });

  return matches.map(studentSummary_);
}

/**
 * Unified availability grid for one student: both conference dates as rows
 * of time slots, each slot listing which of the student's own teachers are
 * open then (Option 3 — pick a time first, then which teacher). Blocks and
 * Bookings are each read once and reused across every teacher, instead of
 * a per-teacher sheet read, since a student can have up to 13 teachers.
 */
function getStudentAvailabilityGrid(rosterRow) {
  var student = sheetRows_('Roster').filter(function (s) { return s._row === rosterRow; })[0];
  if (!student) return { grid: [], classes: [], bookings: [] };

  var teacherList = student.TeachersJSON ? JSON.parse(student.TeachersJSON) : [];
  var teachersByName = {};
  sheetRows_('Teachers').forEach(function (t) {
    teachersByName[String(t.Name).trim().toLowerCase()] = t;
  });
  // classKey identifies one specific class, not one teacher — a teacher who
  // teaches this student two different classes (e.g. Homeroom and Math)
  // must stay two separate, independently selectable/bookable entries, not
  // merged into one "teacher" option.
  var resolvedTeachers = teacherList
    .map(function (t, i) {
      var teacher = teachersByName[String(t.teacherName).trim().toLowerCase()];
      return { classKey: 'c' + i, subject: t.subject, teacherName: t.teacherName, teacherEmail: teacher ? teacher.Email : '' };
    })
    .filter(function (t) { return t.teacherEmail; });

  var grade = student.Grade;
  var settings = getSettings();
  var dates = getConferenceDates();
  var slotLength = slotLengthForGrade(grade);
  var timeSlots = generateSlots_(settings.DayStartTime, settings.DayEndTime, slotLength);

  var allBlocks = sheetRows_('Blocks');
  var allBookings = sheetRows_('Bookings');
  var blocksByTeacher = {};
  allBlocks.forEach(function (b) {
    var key = String(b.TeacherEmail).trim().toLowerCase();
    (blocksByTeacher[key] = blocksByTeacher[key] || []).push(b);
  });
  var bookingsByTeacher = {};
  allBookings.forEach(function (b) {
    var key = String(b.TeacherEmail).trim().toLowerCase();
    (bookingsByTeacher[key] = bookingsByTeacher[key] || []).push(b);
  });

  var cellMap = {}; // date|start|end -> [{ classKey, subject, teacherName, teacherEmail }]
  resolvedTeachers.forEach(function (t) {
    var emailKey = String(t.teacherEmail).trim().toLowerCase();
    var taken = (blocksByTeacher[emailKey] || []).concat(bookingsByTeacher[emailKey] || []);
    dates.forEach(function (date) {
      timeSlots.forEach(function (ts) {
        var isTaken = taken.some(function (b) { return toDateKey_(b.Date) === date && overlaps_(ts, b); });
        if (!isTaken) {
          var key = date + '|' + ts.start + '|' + ts.end;
          (cellMap[key] = cellMap[key] || []).push({ classKey: t.classKey, subject: t.subject, teacherName: t.teacherName, teacherEmail: t.teacherEmail });
        }
      });
    });
  });

  var grid = dates.map(function (date) {
    return {
      date: date,
      slots: timeSlots.map(function (ts) {
        var key = date + '|' + ts.start + '|' + ts.end;
        return { start: ts.start, end: ts.end, teachers: cellMap[key] || [] };
      })
    };
  });

  // One picker option per class (not deduped by teacher) — a teacher
  // teaching this student two different classes must show, and be
  // independently selectable, as two separate options.
  var classes = resolvedTeachers.map(function (t) {
    return { classKey: t.classKey, teacherName: t.teacherName, teacherEmail: t.teacherEmail, subject: t.subject };
  });

  return { grid: grid, classes: classes, bookings: getBookingsForStudent_(student) };
}

/**
 * A student's own already-saved bookings, so the parent page can show them
 * as cancelable even after a reload (client-side "booked this visit" state
 * doesn't survive a reload on its own). Matches by RosterRow when the
 * booking row has one; falls back to name+grade for rows saved before that
 * column existed.
 */
function getBookingsForStudent_(student) {
  return sheetRows_('Bookings').filter(function (b) {
    if (b.RosterRow) return String(b.RosterRow) === String(student._row);
    return String(b.StudentFirst) === String(student.StudentFirst) &&
      String(b.StudentLast) === String(student.StudentLast) &&
      String(b.Grade) === String(student.Grade);
  }).map(function (b) {
    return {
      date: toDateKey_(b.Date), start: toTimeKey_(b.StartTime), end: toTimeKey_(b.EndTime),
      teacherEmail: b.TeacherEmail, teacherName: b.TeacherName, subject: b.Subject || ''
    };
  });
}

function getOpenSlotsForStudentTeacher(teacherEmail, grade) {
  return getOpenSlotsForTeacher(teacherEmail, grade);
}

/**
 * Applies a batch of bookings at once — the parent page picks times
 * locally across every child and saves them all in one shot at the end,
 * rather than confirming one at a time. Each booking still goes through
 * the same bookSlot (lock + re-check), so one slot taken by someone else
 * in the meantime fails on its own without failing the whole batch.
 */
function submitBookings(bookings) {
  var results = (bookings || []).map(function (b) {
    var r = bookSlot(b);
    return { rosterRow: b.rosterRow, date: b.date, start: b.start, teacherName: b.teacherName, teacherEmail: b.teacherEmail, subject: b.subject, success: r.success, message: r.message || '' };
  });
  return { success: results.every(function (r) { return r.success; }), results: results };
}

function cancelBooking(date, start, teacherEmail, rosterRow) {
  return cancelBookingByDetails(date, start, teacherEmail, rosterRow);
}

/* ===== TeacherView.js ===== */
function getCurrentUserEmail_() {
  return Session.getActiveUser().getEmail();
}

function getCurrentTeacherGrid() {
  var email = getCurrentUserEmail_();
  if (!email) return { error: 'Could not determine your logged-in Google account.' };
  var grid = getTeacherGrid(email);
  if (!grid) return { error: 'No teacher record found for ' + email + '. Ask an admin to add you to the Teachers tab.' };
  return grid;
}

/**
 * Applies a batch of block/unblock changes at once (the teacher page edits
 * locally and saves everything in one shot, rather than a network call per
 * click). Each change sets an explicit desired state rather than toggling,
 * so an already-booked slot is still safely rejected per-item instead of
 * failing the whole batch. Always returns a `results` array, even on
 * early failure, so the client never dereferences an undefined array.
 */
function saveTeacherBlockChanges(changes) {
  var email = getCurrentUserEmail_();
  if (!email) return { success: false, message: 'Could not determine your logged-in Google account.', results: [] };
  var teacher = getTeacherByEmail_(email);
  if (!teacher) {
    return { success: false, message: 'No teacher record found for ' + email + '.', results: [] };
  }

  var results = (changes || []).map(function (c) {
    var r = setTeacherBlock(email, c.date, c.start, c.end, c.desiredBlocked);
    return { date: c.date, start: c.start, end: c.end, success: r.success, message: r.message || '' };
  });
  return { success: results.every(function (r) { return r.success; }), results: results };
}

/* ===== FactsData.js ===== */
/**
 * Read-only helpers for the FACTS export Google Sheet (settings.RosterSpreadsheetId,
 * auto-converted from FACTS_Export.xlsx by a separate system). Used only by
 * RosterSync.js during a sync — runtime lookups read the local Roster/Teachers
 * copies instead.
 *
 * FACTS tabs used: Sheet1 (student + guardian rows, one row per guardian),
 * Student Schedules (one row per enrolled class), Teachers (Staff ID,
 * Teacher, Active, Level), Staff (Staff ID, Email).
 */

/**
 * RosterSpreadsheetId must point at an already-converted native Google
 * Sheet (File > Save as Google Sheets on the FACTS export), not the raw
 * .xlsx — SpreadsheetApp can't open Office-format files directly.
 */
function getFactsSpreadsheet_() {
  var settings = getSettings();
  if (!settings.RosterSpreadsheetId) {
    throw new Error('Set RosterSpreadsheetId in the Settings tab to the converted FACTS Google Sheet.');
  }
  return SpreadsheetApp.openById(settings.RosterSpreadsheetId);
}

function getFactsRows_(tabName) {
  var sheet = getFactsSpreadsheet_().getSheetByName(tabName);
  if (!sheet) throw new Error('FACTS tab "' + tabName + '" not found.');
  var values = sheet.getDataRange().getValues();
  var headers = values[0];
  var rows = [];
  for (var r = 1; r < values.length; r++) {
    var obj = {};
    headers.forEach(function (h, i) { obj[h] = values[r][i]; });
    rows.push(obj);
  }
  return rows;
}

/** "LastName FirstName" -> {first, last}; splits on the final space. */
function splitStudentName_(fullName) {
  var str = String(fullName || '').trim();
  var idx = str.lastIndexOf(' ');
  if (idx === -1) return { first: str, last: '' };
  return { last: str.substring(0, idx).trim(), first: str.substring(idx + 1).trim() };
}

/* ===== RosterSync.js ===== */
/**
 * Pulls the FACTS export (settings.RosterSpreadsheetId — an already-
 * converted native Google Sheet) into the local Roster and Teachers tabs.
 * Run from the Conference Scheduler menu whenever FACTS data changes.
 */

function rosterHeaders_() {
  return ['StudentFirst', 'StudentLast', 'Grade', 'ParentName', 'ParentEmail', 'GuardiansJSON', 'TeachersJSON'];
}

/** Quarters column looks like "Q1,2,3,4" — true if quarter 1 is among them. */
function includesQ1_(quartersStr) {
  if (!quartersStr) return false;
  return String(quartersStr).split(',').some(function (q) {
    return q.replace(/[^0-9]/g, '') === '1';
  });
}

/** Study Hall isn't a conference-worthy class — never show it as bookable. */
function isStudyHall_(classDescription) {
  return String(classDescription || '').trim().toLowerCase().indexOf('study hall') !== -1;
}

/**
 * Student Schedules sometimes lists a class as "Primary Teacher / Assistant"
 * (e.g. 3rd grade aide, PE assistant coach) — only the primary teacher is a
 * real conference contact, and the raw combined string wouldn't match
 * anything in the Teachers tab anyway.
 */
function primaryTeacherName_(teacherField) {
  return String(teacherField || '').split('/')[0].trim();
}

/**
 * How many conference meetings a grade needs:
 * - elementary (K-3): self-contained classroom, one meeting with the
 *   homeroom teacher covers everything.
 * - upperElementary (4-6): classes split between two teachers, so up to
 *   two meetings.
 * - secondary (7-12): one meeting per class, same as before.
 */
function conferenceTier_(grade) {
  var gradeNum = parseInt(grade, 10);
  if (isNaN(gradeNum)) return 'elementary'; // K4/K5
  if (gradeNum <= 3) return 'elementary';
  if (gradeNum <= 6) return 'upperElementary';
  return 'secondary';
}

/**
 * Dedups a student's Core classes down to each distinct primary teacher —
 * used for 4-6 (classes split between ~2 teachers) and as the elementary
 * fallback for homeschool (HMSCHL) students, who take real Core classes
 * but have no Homeroom row to key off of.
 */
function distinctCoreTeachers_(classRows) {
  var seen = {};
  var teachers = [];
  (classRows || []).forEach(function (row) {
    if (row['Category'] !== 'Core' || !includesQ1_(row['Quarters']) || isStudyHall_(row['Class Description'])) return;
    var primary = primaryTeacherName_(row['Teacher']);
    if (!primary || seen[primary]) return;
    seen[primary] = true;
    teachers.push({ subject: '', teacherName: primary });
  });
  return teachers;
}

/**
 * Groups Sheet1 by student, collects every distinct guardian, and pulls
 * each student's conference-relevant teachers per conferenceTier_.
 */
function syncRoster() {
  var guardianRows = getFactsRows_('Sheet1').filter(function (row) {
    return row['Status'] === 'Enrolled';
  });

  var byStudent = {};
  guardianRows.forEach(function (row) {
    var id = row['Student ID (System)'];
    (byStudent[id] = byStudent[id] || []).push(row);
  });

  var schedulesByStudent = {};
  getFactsRows_('Student Schedules').forEach(function (row) {
    var id = row['Student ID'];
    (schedulesByStudent[id] = schedulesByStudent[id] || []).push(row);
  });

  var outRows = Object.keys(byStudent).map(function (studentId) {
    var rows = byStudent[studentId];
    var name = splitStudentName_(rows[0]['LastName FirstName']);
    var gradeLevel = rows[0]['Grade Level'];

    var guardians = [];
    var seenGuardians = {};
    rows.forEach(function (row) {
      var email = row['Email 1'];
      var guardianName = row['LastName FirstName 1'];
      // Dedup by name+email together, not email alone — two different
      // guardians (e.g. both parents) sometimes share one email address,
      // and both should still show up as separate guardians.
      var key = String(guardianName).trim().toLowerCase() + '|' + String(email).trim().toLowerCase();
      if (email && !seenGuardians[key]) {
        seenGuardians[key] = true;
        guardians.push({ name: guardianName, email: email });
      }
    });

    var tier = conferenceTier_(gradeLevel);
    var studentClasses = schedulesByStudent[studentId] || [];
    var teachers;

    if (tier === 'elementary') {
      var homeroomRow = studentClasses.filter(function (row) {
        return row['Category'] === 'Homeroom' && includesQ1_(row['Quarters']);
      })[0];
      if (homeroomRow) {
        var homeroomTeacher = primaryTeacherName_(homeroomRow['Teacher']);
        teachers = homeroomTeacher ? [{ subject: '', teacherName: homeroomTeacher }] : [];
      } else {
        // Homeschool (HMSCHL) students take real Core classes but have no
        // Homeroom row — fall back to their actual Core teacher(s) instead
        // of leaving them with nothing to book.
        teachers = distinctCoreTeachers_(studentClasses);
      }
    } else if (tier === 'upperElementary') {
      teachers = distinctCoreTeachers_(studentClasses);
    } else {
      // secondary: every scheduled class, shown with its class name. Homeroom
      // isn't a conference-worthy meeting (it's not a subject a parent would
      // book time to discuss) — never list it, even if the homeroom teacher
      // also teaches one of the student's real classes.
      teachers = studentClasses
        .filter(function (row) {
          return includesQ1_(row['Quarters']) && !isStudyHall_(row['Class Description']) && row['Category'] !== 'Homeroom';
        })
        .map(function (row) { return { subject: row['Class Description'], teacherName: primaryTeacherName_(row['Teacher']) }; });
    }

    return [
      name.first,
      name.last,
      gradeLevel,
      guardians.length ? guardians[0].name : '',
      guardians.length ? guardians[0].email : '',
      JSON.stringify(guardians),
      JSON.stringify(teachers)
    ];
  });

  var headers = rosterHeaders_();
  var sheet = SpreadsheetApp.getActive().getSheetByName('Roster');
  sheet.clearContents();
  sheet.getRange(1, 1, 1, headers.length).setValues([headers]);
  if (outRows.length) {
    sheet.getRange(2, 1, outRows.length, headers.length).setValues(outRows);
  }
  return outRows.length;
}

/**
 * Joins FACTS Teachers (name/level) with Staff (email). Preserves any
 * Room already set locally, since FACTS has no room data and Room would
 * otherwise be wiped on every re-sync.
 */
function syncTeachers() {
  var staffById = {};
  getFactsRows_('Staff').forEach(function (s) { staffById[s['Staff ID']] = s; });

  var existingRoomByEmail = {};
  sheetRows_('Teachers').forEach(function (t) {
    if (t.Email) existingRoomByEmail[String(t.Email).trim().toLowerCase()] = t.Room;
  });

  var outRows = getFactsRows_('Teachers')
    .filter(function (t) { return t['Active'] === 'Y'; })
    .map(function (t) {
      var staff = staffById[t['Staff ID']];
      var email = staff ? staff['Email'] : '';
      var room = existingRoomByEmail[String(email).trim().toLowerCase()] || '';
      var gradeBand = t['Level'] === 'Elem' ? 'Elem' : 'Secondary';
      return [t['Teacher'], email, room, gradeBand];
    });

  var headers = ['Name', 'Email', 'Room', 'GradeBand'];
  var sheet = SpreadsheetApp.getActive().getSheetByName('Teachers');
  sheet.clearContents();
  sheet.getRange(1, 1, 1, headers.length).setValues([headers]);
  if (outRows.length) {
    sheet.getRange(2, 1, outRows.length, headers.length).setValues(outRows);
  }
  return outRows.length;
}

  global.PTC_LOGIC = {
    bind: function (env) {
      SpreadsheetApp = env.SpreadsheetApp; LockService = env.LockService; Session = env.Session;
      Utilities = env.Utilities; Logger = env.Logger; sendBookingEmail_ = env.sendBookingEmail_;
    },
    getSettings: getSettings,
    getConferenceDates: getConferenceDates,
    slotLengthForGrade: slotLengthForGrade,
    generateSlots_: generateSlots_,
    overlaps_: overlaps_,
    findStudentsByGuardianEmail_: findStudentsByGuardianEmail_,
    getStudentAvailabilityGrid: getStudentAvailabilityGrid,
    submitBookings: submitBookings,
    cancelBooking: cancelBooking,
    getTeacherGrid: getTeacherGrid,
    getCurrentTeacherGrid: getCurrentTeacherGrid,
    saveTeacherBlockChanges: saveTeacherBlockChanges,
    setTeacherBlock: setTeacherBlock,
    syncRoster: syncRoster,
    syncTeachers: syncTeachers,
    conferenceTier_: conferenceTier_,
    sheetRows_: sheetRows_
  };
})(typeof window !== "undefined" ? window : globalThis);
