// build-logic.mjs — vendor the ELC Student Assessments SERVER into the demo, verbatim.
//
//   node demos/elc-assessments/build-logic.mjs
//
// The page (app.html) is the real Index.html. Everything it asks of google.script.run is answered by the
// project's own .gs files, concatenated here into logic.js inside one IIFE, in the order Apps Script and
// the project's own test harness (tests/helpers/gsFiles.js) load them: the seven Assessments/*.gs benchmark
// tables first (Registry.gs reads their constants at load time), then Registry.gs, then the rest. mock.js
// binds the Google services underneath (an in-memory spreadsheet, Session, Cache, Properties, Lock, Mail,
// ScriptApp) and a pinned Date, so the scoring, the tiers, the access scopes, the risk buckets and the
// dashboards the demo shows are the app's own output, not fixtures.
//
// WHAT IS VENDORED: every server file WHOLE, except EasyCbmHistoricalImport.gs (a one-off importer of real
// historical scores — never shipped in a public copy; verify.mjs fails if its code appears in the bundle).
//
// SCRUBS (verify.mjs re-runs this function and compares): the real domain; the school's name (the brand is
// swapped for the same fictional school the page uses); people named in the source comments, replaced by
// this build's hashed nameAliases table in build.json (the same table the page build applies, so the config
// never spells a name) and the shared staff aliases.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { aliasStaffNames, aliasPhrases, aliasEmailLocals, PHRASE_ALIASES } from '../../tools/staff-aliases.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const SRC = path.resolve(HERE, '../../../elc/elc-student-assessments');

export const FILES = [
  'Assessments/Dibels.gs', 'Assessments/CorePhonics.gs', 'Assessments/Dra.gs', 'Assessments/EasyCbm.gs',
  'Assessments/EasyCbmMath.gs', 'Assessments/Lexile.gs', 'Assessments/Orf.gs',
  'Registry.gs', 'Code.gs', 'Data.gs', 'Growth.gs', 'Dashboard.gs', 'Compliance.gs', 'Coverage.gs', 'Summary.gs',
  'Requests.gs', 'Roster.gs', 'IepGoals.gs', 'AccommodationsChecklist.gs', 'Section504.gs', 'Notifications.gs',
  'GradeAudit.gs'
];
export const NOT_VENDORED = ['EasyCbmHistoricalImport.gs'];
// Google services, plus Date and console: the server's own `new Date()` reads the demo's pinned clock, and its
// ~270 diagnostic console.log lines go to a quiet logger, without touching the page's Date or console.
export const SERVICES = ['SpreadsheetApp', 'CacheService', 'PropertiesService', 'Session', 'Utilities', 'MailApp',
  'ScriptApp', 'HtmlService', 'LockService', 'Logger', 'Date', 'console'];
// Apps Script runs every google.script.run call as a FRESH execution, so these script-level memo caches
// (Data.gs / Code.gs, each documented there as "lifetime of one execution") start empty on every call.
export const EXECUTION_CACHES = { _cachedSpreadsheet_: 'null', _cachedSheets_: '{}', _rowsCache_: '{}', _cachedReferenceTabRows_: '{}' };

export function nameAliases() {
  return JSON.parse(readFileSync(path.join(HERE, 'build.json'), 'utf8')).nameAliases || {};
}

const lf = (s) => s.replace(/\r\n?/g, '\n');

export function scrub(text) {
  const DOMAIN = 'harford' + 'christian';
  let out = text.replace(new RegExp(DOMAIN + '\.org', 'gi'), 'example.edu').replace(new RegExp(DOMAIN, 'gi'), 'example');
  out = out.replace(/https:\/\/script\.google\.com\/macros\/s\/[A-Za-z0-9_-]{20,}\/(exec|dev)/g, 'https://example.invalid/demo-deployment');
  out = out.replace(/\b1[A-Za-z0-9_-]{40,}\b/g, 'DEMO_DRIVE_ID');
  out = out.replace(/Harford Christian/g, 'Example Christian');
  out = aliasPhrases(out, Object.assign({}, PHRASE_ALIASES, nameAliases())).text;
  out = aliasStaffNames(out).text;
  out = aliasEmailLocals(out).text;
  return out;
}

export function buildLogic() {
  let body = '';
  const names = [];
  for (const f of FILES) {
    const src = lf(readFileSync(path.join(SRC, f), 'utf8'));
    body += `\n/* ===== ${f} ===== */\n` + src.replace(/\s+$/, '') + '\n';
    for (const m of src.matchAll(/^(?:function\s+([A-Za-z_$][\w$]*)\s*\(|var\s+([A-Za-z_$][\w$]*)\s*=)/gm)) {
      const n = m[1] || m[2];
      if (!names.includes(n)) names.push(n);
    }
  }
  body = scrub(body);
  const exported = names.filter((n) => !(n in EXECUTION_CACHES));
  return [
    '/* GENERATED by demos/elc-assessments/build-logic.mjs — do not edit.',
    "   The SOURCE PROJECT'S OWN server, verbatim: every .gs file but the historical-score importer, in the",
    '   load order Apps Script and the project\'s test harness use. mock.js binds the Google services, a pinned',
    '   Date and a quiet console underneath; window.ELC_LOGIC exposes every top-level declaration. */',
    '(function (global) {',
    '  var ' + SERVICES.map((s) => s === 'Date' ? 'Date = global.Date' : s === 'console' ? 'console = global.console' : s).join(', ') + ';',
    body,
    '  global.ELC_LOGIC = {',
    '    bind: function (env) { ' + SERVICES.map((s) => `if (env.${s}) ${s} = env.${s};`).join(' ') + ' },',
    '    newExecution: function () { ' + Object.entries(EXECUTION_CACHES).map(([k, v]) => `${k} = ${v};`).join(' ') + ' },',
    ...exported.map((n, i) => `    ${n}: ${n}${i < exported.length - 1 ? ',' : ''}`),
    '  };',
    '})(typeof window !== "undefined" ? window : globalThis);',
    ''
  ].join('\n');
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  if (!existsSync(SRC)) { console.log('SKIP build-logic: source project not found at', SRC); process.exit(0); }
  const out = buildLogic();
  writeFileSync(path.join(HERE, 'logic.js'), out);
  console.log('built demos/elc-assessments/logic.js (' + out.length + ' bytes)');
}
