// build-logic.mjs — vendor the REAL code of the Student Portal into the demo.
//
//   node demos/student-portal/build-logic.mjs
//
// What is vendored, verbatim:
//   Schedule.js  Due.js  Athletics.js  SchoolCal.js   — the project's PURE engines (period join, reverse Friday,
//                                                       due-date parsing of teacher prose, game-day dismissal
//                                                       parsing, school-calendar closures)
//   Code.gs  Sports.gs  Notify.gs  Data.gs  Bells.gs — the endpoints the page calls and the cache/data plumbing
//                                                       behind them, exactly as the server runs them
// What is NOT vendored, and why:
//   Config.gs   carries the school's real calendar ids, Drive folder id and deployment id. The demo supplies its
//               own config (mock.js) with fabricated ids, so none of those can reach a public repo.
//   Auth.gs     resolves the caller through the Workspace directory; the demo answers with its fabricated student.
//   Sync.gs / Admin.gs  the FACTS API sync and operator diagnostics — nothing the page calls.
//
// The files are wrapped in one function so the Apps Script services they expect (SpreadsheetApp, CacheService,
// PropertiesService, DriveApp, UrlFetchApp, …) can be supplied by the demo instead of by Google. Config symbols
// and the caller resolver are looked up as globals, which mock.js defines before the first call. Nothing inside
// the wrapper is edited, except: each pure module's one-line Node export guard is dropped (the browser has no
// `module`; the guard is dead there, and dropping it keeps the bundle loadable from any context), and two
// comments are scrubbed — the school's real domain and one real student's first name.
//
// Exits 0 with a SKIP if the source project isn't checked out beside this repo.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { aliasStaffNames } from '../../tools/staff-aliases.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const SRC = path.resolve(HERE, '../../../FACTS/student-interface');

export const FILES = ['Schedule.js', 'Due.js', 'Athletics.js', 'SchoolCal.js', 'Code.gs', 'Sports.gs', 'Notify.gs', 'Data.gs', 'Bells.gs'];

// Apps Script services the vendored code reaches for. Bound by mock.js (env) before the first call.
export const SERVICES = ['SpreadsheetApp', 'CacheService', 'PropertiesService', 'DriveApp', 'UrlFetchApp', 'LockService',
  'Session', 'Utilities', 'Logger', 'ScriptApp', 'HtmlService', 'MailApp', 'GmailApp', 'BellHub', 'AdminDirectory'];

// What the wrapper exposes: the six endpoints the page calls, plus the internals verify.mjs and mock.js use.
export const EXPORTS = ['bootApi', 'athleticsApi', 'gradesApi', 'savePrefsApi', 'inboxApi', 'attendanceApi', 'prefsApi', 'homeworkApi',
  'buildBootPayload_', 'schedCtx_', 'weekDates_', 'classListFor_', 'loadStagingTabs_', 'loadDataTabs_', 'bellsForDays_',
  'noSchoolDaysCached_', 'calendarClosedDays_', 'athleticsRangeCached_', 'prefsRead_', 'noticesFor_', 'caller_',
  'Sched', 'Due', 'Ath', 'SchoolCal'];

export function buildLogic() {
  const parts = FILES.map((f) => {
    let body = readFileSync(path.join(SRC, f), 'utf8');
    body = body.replace(/^if \(typeof module !== 'undefined' && module\.exports\) module\.exports = \w+;\s*$/m, '');
    // The same always-on privacy scrub build-demo.mjs applies to HTML: the real school domain never lands in
    // the public repo, even inside a source comment. (The domain is split so tools/ itself scans clean.)
    const DOMAIN = 'harford' + 'christian';
    body = body.replace(new RegExp(DOMAIN + '(\\\\?\\.)org', 'gi'), 'example$1edu').replace(new RegExp(DOMAIN, 'gi'), 'example');
    // One comment names a real student (the developer's son) — the only personal name in these files.
    body = body.replace(/\bNoah's\b/g, "a student's");
    // Real staff first names in source comments become role aliases — the one deliberate departure from
    // verbatim (verify.mjs applies the same transform before comparing).
    body = aliasStaffNames(body).text;
    return `/* ===== ${f} ===== */\n` + body;
  });
  return [
    '/* GENERATED by demos/student-portal/build-logic.mjs — do not edit.',
    "   This is the SOURCE PROJECT'S OWN code, verbatim: the pure engines (Schedule, Due, Athletics, SchoolCal) and the",
    '   endpoint + data files (Code, Sports, Notify, Data, Bells). The demo runs it in the browser against in-memory',
    '   stand-ins for Google (mock.js), so the schedule, the due list, the game-day card, the grades and the attendance',
    "   row are the app's real behaviour and cannot drift from it. Re-run the script after any change upstream. */",
    '(function (global) {',
    '  // Apps Script services the source expects — bound by mock.js before the first call.',
    '  var ' + SERVICES.join(', ') + ';',
    ...parts,
    '  global.PORTAL_LOGIC = {',
    '    bind: function (env) { ' + SERVICES.map((s) => `${s} = env.${s};`).join(' ') + ' },',
    ...EXPORTS.map((n, i) => `    ${n}: ${n}${i < EXPORTS.length - 1 ? ',' : ''}`),
    '  };',
    '})(typeof window !== "undefined" ? window : globalThis);',
    ''
  ].join('\n');
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  if (!existsSync(SRC)) { console.log('SKIP build-logic: source project not found at', SRC); process.exit(0); }
  const out = buildLogic();
  writeFileSync(path.join(HERE, 'logic.js'), out);
  console.log('built demos/student-portal/logic.js (' + out.length + ' bytes) from', FILES.length, 'source files');
}
