/* GENERATED by demos/transportation/build-kiosk-logic.mjs — do not edit.
   Part 1: ../transportation/DismissalClient.html (the publisher's pure logic, generated from Dismissal.gs),
   as page globals for the vendored minute publisher in logic.js. Part 2: the Ramp Kiosk's own server,
   Config.gs and Code.gs whole (ids scrubbed), as window.KIOSK_LOGIC; mock.js binds its Google services. */
/* ===== ../transportation/DismissalClient.html ===== */
// GENERATED from Dismissal.gs by tools/build-client.mjs — DO NOT EDIT.
// Edit Dismissal.gs, then re-run the generator. Comments are stripped on the way out; read
// them in Dismissal.gs, which is the source of truth.

function dsCellToString(v) {
  if (v instanceof Date) {
    var y = v.getFullYear(), mo = v.getMonth(), d = v.getDate();
    var hh = ('0' + v.getHours()).slice(-2), mm = ('0' + v.getMinutes()).slice(-2);
    if (y === 1899 && mo === 11 && d === 30) return hh + ':' + mm;
    return y + '-' + ('0' + (mo + 1)).slice(-2) + '-' + ('0' + d).slice(-2) + ' ' + hh + ':' + mm;
  }
  return v == null ? '' : String(v);
}

function dsByName(a, b) {
  return a.name < b.name ? -1 : a.name > b.name ? 1 : 0;
}

function dsGetter(h) {
  return function (row, name) {
    var i = h[name];
    return i === undefined ? '' : dsCellToString(row[i]).trim();
  };
}

function dsHeaderMap(headerRow) {
  var map = {};
  (headerRow || []).forEach(function (h, i) { map[dsCellToString(h).trim()] = i; });
  return map;
}

function dsSerializeTab(values) {
  return (values || []).map(function (row) {
    return (row || []).map(dsCellToString);
  });
}

function dsBuildRoster(values) {
  if (!values || values.length < 2) return [];
  var h = dsHeaderMap(values[0]);
  var get = dsGetter(h);
  var enrichmentKnown = h['Enrichment'] !== undefined;
  var out = [];
  for (var r = 1; r < values.length; r++) {
    var row = values[r];
    var id = get(row, 'Student ID');
    if (!id) continue;
    out.push({
      id: id,
      enrichment: get(row, 'Enrichment') === 'Y',
      enrichmentKnown: enrichmentKnown,
      name: get(row, 'Student Name'),
      grade: dsGradeKey(get(row, 'Grade')),   // canonical from here on — see dsGradeKey
      session: get(row, 'Session'),
      type: get(row, 'Type'),
      routeCode: get(row, 'Route Code'),
      routeName: get(row, 'Route Name'),
      vehicle: get(row, 'Vehicle'),
      split: get(row, 'Split') === 'Y',
      building: get(row, 'Building'),
      pickup: get(row, 'Pickup'),
      walkTo: get(row, 'Walk To'),
      familyId: get(row, 'Family ID'),
      homeroom: get(row, 'Homeroom'),
      homeroomTeacher: get(row, 'Homeroom Teacher'),
      source: get(row, 'Source'),
      note: get(row, 'Note')
    });
  }
  return out;
}

function dsReadDelay(bellSchedule, dayType) {
  var b = String(bellSchedule || '').toUpperCase().replace(/[^A-Z0-9]/g, '');
  var d = String(dayType || '').toUpperCase().replace(/[^A-Z0-9]/g, '');
  var signal = b || d;
  if (!signal) return { known: false, delayMinutes: 0, noSchool: false };
  var out = { known: true, delayMinutes: 0, noSchool: false };
  if (signal.indexOf('3HR') === 0 || signal.indexOf('3HOUR') === 0) out.delayMinutes = 180;
  else if (signal.indexOf('2HR') === 0 || signal.indexOf('2HOUR') === 0) out.delayMinutes = 120;
  if (/NOBELLS|CLOSED/.test(signal)) out.noSchool = true;
  return out;
}

function dsBuildNoSchool(delay, roster) {
  var out = {};
  if (!delay || !delay.known || !delay.delayMinutes) return out;   // closed days are everyone's, not ours
  (roster || []).forEach(function (s) {
    if (dsIsMiddayLeaver(s)) out[s.id] = true;
  });
  return out;
}

function dsIsMiddayLeaver(s) {
  if (!s || !s.enrichmentKnown) return false;
  var g = dsGradeNum(s.grade);
  if (g !== -2 && g !== -1) return false;          // K4 = -2, K5 = -1; nobody else goes home at noon
  return !s.enrichment;
}

function dsBuildAttendance(values, todayKey) {
  var out = {};
  if (!values || values.length < 2) return out;
  var h = dsHeaderMap(values[0]);
  var get = dsGetter(h);
  var today = String(todayKey || '').slice(0, 10);
  var dated = h['Date'] !== undefined;
  for (var r = 1; r < values.length; r++) {
    var id = get(values[r], 'Student ID');
    if (!id) continue;
    if (today && dated && get(values[r], 'Date').slice(0, 10) !== today) continue;
    out[id] = {
      code: get(values[r], 'Code').toUpperCase(),
      status: get(values[r], 'Status'),
      detail: get(values[r], 'Detail'),
      reason: get(values[r], 'Reason'),
      excused: get(values[r], 'Excused')
    };
  }
  return out;
}

function dsAttendanceDates(values) {
  if (!values || values.length < 2) return [];
  var h = dsHeaderMap(values[0]);
  if (h['Date'] === undefined) return [];
  var seen = {};
  for (var r = 1; r < values.length; r++) {
    var d = dsCellToString(values[r][h['Date']]).trim().slice(0, 10);
    if (d) seen[d] = true;
  }
  return Object.keys(seen).sort();
}

var DS_OVERRIDE_TYPES = ['Bus', 'Car', 'Early Bird', 'Staff Kid'];
var DS_OVERRIDE_USUAL = 'Usual';
function dsBuildOverrides(values, todayKey) {
  var out = {};
  if (!values || values.length < 2) return out;
  var h = dsHeaderMap(values[0]);
  var get = dsGetter(h);
  for (var r = 1; r < values.length; r++) {
    var row = values[r];
    var id = get(row, 'Student ID');
    var date = get(row, 'Date').slice(0, 10);
    if (!id || date !== todayKey) continue;
    var oType = get(row, 'Type');
    if (oType === DS_OVERRIDE_USUAL) { delete out[id]; continue; }
    out[id] = {
      type: oType,
      routeCode: get(row, 'Route Code'),
      destination: get(row, 'Destination'),
      note: get(row, 'Note'),
      by: get(row, 'By'),
      at: get(row, 'At')
    };
  }
  return out;
}

var DS_PLAN_MAX_DAYS = 60;      // how far ahead a plan may reach
var DS_PLAN_MAX_DATES = 30;     // how many days one save may cover

function dsAddDays(key, n) {
  var p = String(key).split('-').map(Number);
  return new Date(Date.UTC(p[0], p[1] - 1, p[2] + n)).toISOString().slice(0, 10);
}
function dsDayOfWeek(key) {
  var p = String(key).split('-').map(Number);
  return new Date(Date.UTC(p[0], p[1] - 1, p[2])).getUTCDay();
}

function dsPlanDatesValidate(dates, todayKey) {
  var seen = {}, out = [];
  (Array.isArray(dates) ? dates : [dates]).forEach(function (d) {
    var k = dsIsoDate(d);
    if (k && !seen[k]) { seen[k] = 1; out.push(k); }
  });
  if (!out.length) return { error: 'Pick at least one day.' };
  out.sort();
  if (out[0] < todayKey) return { error: 'A change cannot be planned for a day that has passed (' + out[0] + ').' };
  var limit = dsAddDays(todayKey, DS_PLAN_MAX_DAYS);
  if (out[out.length - 1] > limit) return { error: 'Plans reach at most ' + DS_PLAN_MAX_DAYS + ' days ahead (through ' + limit + ').' };
  if (out.length > DS_PLAN_MAX_DATES) return { error: 'At most ' + DS_PLAN_MAX_DATES + ' days in one save.' };
  for (var i = 0; i < out.length; i++) {
    var dow = dsDayOfWeek(out[i]);
    if (dow === 0 || dow === 6) return { error: out[i] + ' is a weekend.' };
  }
  return { ok: true, dates: out };
}

function dsBuildPlanned(values, todayKey) {
  if (!values || values.length < 2) return [];
  var h = dsHeaderMap(values[0]);
  var get = dsGetter(h);
  var byKey = {}, order = [];
  for (var r = 1; r < values.length; r++) {
    var row = values[r];
    var id = get(row, 'Student ID'), date = get(row, 'Date').slice(0, 10);
    if (!id || !date || date <= todayKey) continue;
    var k = date + '|' + id;
    if (!byKey[k]) order.push(k);
    byKey[k] = { date: date, id: id, name: get(row, 'Student Name'), type: get(row, 'Type'),
                 routeCode: get(row, 'Route Code'), destination: get(row, 'Destination'),
                 note: get(row, 'Note'), by: get(row, 'By'), at: get(row, 'At') };
  }
  return order.map(function (k) { return byKey[k]; })
    .filter(function (p) { return p.type !== DS_OVERRIDE_USUAL; })
    .sort(function (a, b) {
      return a.date < b.date ? -1 : a.date > b.date ? 1 : a.name < b.name ? -1 : a.name > b.name ? 1 : 0;
    });
}

function dsBuildHistory(overrides, auths, studentId, todayKey) {
  studentId = String(studentId == null ? '' : studentId).replace(/\.0+$/, '').trim();
  var changes = [];
  if (studentId && overrides && overrides.length > 1) {
    var h = dsHeaderMap(overrides[0]);
    var get = dsGetter(h);
    for (var r = 1; r < overrides.length; r++) {
      var row = overrides[r];
      if (get(row, 'Student ID').replace(/\.0+$/, '') !== studentId) continue;
      var date = get(row, 'Date').slice(0, 10);
      if (!date) continue;
      var type = get(row, 'Type');
      changes.push({
        row: r + 1, date: date,
        when: date < todayKey ? 'past' : date === todayKey ? 'today' : 'later',
        type: type, routeCode: get(row, 'Route Code'), destination: get(row, 'Destination'),
        note: get(row, 'Note'), by: get(row, 'By'), at: get(row, 'At'), entered: get(row, 'Entered'),
        undo: type === DS_OVERRIDE_USUAL, won: false
      });
    }
  }
  var lastOfDay = {};
  changes.forEach(function (c) { lastOfDay[c.date] = c; });
  changes.forEach(function (c) { c.won = lastOfDay[c.date] === c; });
  changes.sort(function (a, b) {
    return a.date > b.date ? -1 : a.date < b.date ? 1 : b.row - a.row;
  });

  var authList = [], byId = {};
  if (studentId && auths && auths.length > 1) {
    var ah = dsHeaderMap(auths[0]);
    var aget = dsGetter(ah);
    for (var i = 1; i < auths.length; i++) {
      var arow = auths[i];
      if (aget(arow, 'Student ID').replace(/\.0+$/, '') !== studentId) continue;
      var aid = aget(arow, 'Auth ID') || ('row' + (i + 1));
      var a = byId[aid];
      if (!a) {
        a = byId[aid] = {
          id: aid, row: i + 1, people: [],
          start: dsIsoDate(aget(arow, 'Start')) || '', end: dsIsoDate(aget(arow, 'End')) || '',
          method: aget(arow, 'Method'), note: aget(arow, 'Note'),
          status: aget(arow, 'Status') || 'Active',
          by: aget(arow, 'Created By'), at: aget(arow, 'Created At'),
          updatedBy: aget(arow, 'Updated By'), updatedAt: aget(arow, 'Updated At')
        };
        authList.push(a);
      }
      if (aget(arow, 'Person')) a.people.push({ name: aget(arow, 'Person'), rel: aget(arow, 'Relationship') });
    }
  }
  authList.sort(function (a, b) { return b.row - a.row; });   // newest written first

  var days = {};
  changes.forEach(function (c) { days[c.date] = 1; });
  return {
    changes: changes, auths: authList,
    counts: { changes: changes.length, days: Object.keys(days).length, auths: authList.length }
  };
}

var DS_STANDING_TYPES = ['Bus', 'Car', 'Early Bird', 'Staff Kid'];
function dsParseDays(raw) {
  var text = String(raw == null ? '' : raw).trim();
  var days = text.split(/[,\s]+/).map(dsDayToken).filter(String);
  var seen = {}, uniq = [];
  days.forEach(function (d) { if (!seen[d]) { seen[d] = 1; uniq.push(d); } });
  uniq.sort(function (a, b) { return DS_WEEKDAYS.indexOf(a) - DS_WEEKDAYS.indexOf(b); });
  return { days: uniq, invalid: !!text && uniq.length === 0, raw: text };
}

function dsDaysInclude(days, dayName) {
  if (!days || !days.length) return true;
  var d = String(dayName || '').slice(0, 3).toLowerCase();
  if (!d) return true;
  for (var i = 0; i < days.length; i++) {
    if (String(days[i]).slice(0, 3).toLowerCase() === d) return true;
  }
  return false;
}

function dsStandingApplies_(every, from, dayKey) {
  var n = parseInt(every, 10);
  if (!(n > 1)) return true;                       // every week, or a value nobody can read
  var f = String(from || '').slice(0, 10);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(f) || !dayKey) return false;
  var a = Date.UTC(+f.slice(0, 4), +f.slice(5, 7) - 1, +f.slice(8, 10));
  var k = String(dayKey).slice(0, 10);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(k)) return false;
  var b = Date.UTC(+k.slice(0, 4), +k.slice(5, 7) - 1, +k.slice(8, 10));
  var days = Math.round((b - a) / 86400000);
  if (days < 0) return false;                      // the pattern has not started yet
  return Math.floor(days / 7) % n === 0;
}

function dsBuildStanding(values, dayName, dayKey) {
  var out = {};
  if (!values || values.length < 2) return out;
  var h = dsHeaderMap(values[0]);
  var get = dsGetter(h);
  for (var r = 1; r < values.length; r++) {
    var row = values[r];
    var id = get(row, 'Student ID'), type = get(row, 'Type');
    if (!id || DS_STANDING_TYPES.indexOf(type) === -1) continue;
    var parsed = dsParseDays(get(row, 'Days'));
    if (parsed.invalid) continue;
    var days = parsed.days;
    if (dayName && !dsDaysInclude(days, dayName)) continue;   // not one of this child's days
    var every = get(row, 'Every'), from = get(row, 'From');
    if (dayKey && !dsStandingApplies_(every, from, dayKey)) continue;
    out[id] = {
      type: type, routeCode: get(row, 'Route Code'), destination: get(row, 'Destination'),
      note: get(row, 'Note'), by: get(row, 'By'), at: get(row, 'Since'), standing: true,
      days: days, every: every, from: from
    };
  }
  return out;
}

var DS_WEEKDAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'];

function dsDayToken(s) {
  var d = String(s || '').slice(0, 3).toLowerCase();
  for (var i = 0; i < DS_WEEKDAYS.length; i++) if (DS_WEEKDAYS[i].toLowerCase() === d) return DS_WEEKDAYS[i];
  return '';
}

function dsStandingRowsAll(values) {
  var out = {};
  if (!values || values.length < 2) return out;
  var h = dsHeaderMap(values[0]);
  var get = dsGetter(h);
  for (var r = 1; r < values.length; r++) {
    var row = values[r];
    var id = get(row, 'Student ID');
    if (!id) continue;
    (out[id] = out[id] || []).push({
      type: get(row, 'Type'), routeCode: get(row, 'Route Code'), destination: get(row, 'Destination'),
      note: get(row, 'Note'), by: get(row, 'By'), since: get(row, 'Since'),
      days: dsParseDays(get(row, 'Days')).days,
      daysRaw: dsParseDays(get(row, 'Days')).raw,
      daysInvalid: dsParseDays(get(row, 'Days')).invalid,
      every: get(row, 'Every'), from: get(row, 'From').slice(0, 10)
    });
  }
  return out;
}

var DS_STANDING_MAX_ROWS = 10;      // five school days, and a day may alternate between two answers

function dsRouteCodeIndex(knownCodes) {
  if (!knownCodes || typeof knownCodes !== 'object') return null;
  var codes = {};
  (Array.isArray(knownCodes) ? knownCodes : Object.keys(knownCodes)).forEach(function (c) {
    var k = String((c && typeof c === 'object' ? c.code : c) || '').trim();
    if (k) codes[k.toLowerCase()] = k;
  });
  return Object.keys(codes).length ? codes : null;
}

function dsRouteChoices(routes, rows) {
  var byCode = {};
  Object.keys(routes || {}).forEach(function (c) {
    var k = String(c || '').trim();
    if (k) byCode[k] = String((routes[c] && routes[c].name) || '').trim() || byCode[k] || k;
  });
  (rows || []).forEach(function (r) {
    var cs = r.routeCodes || (r.routeCode ? [r.routeCode] : []);
    var ns = r.routes || (r.routeName ? [r.routeName] : []);
    cs.forEach(function (c, i) {
      var k = String(c || '').trim();
      if (k && !byCode[k]) byCode[k] = String(ns[i] || '').trim() || k;
    });
  });
  return Object.keys(byCode).map(function (k) { return { code: k, name: byCode[k] }; })
    .sort(function (a, b) {
      var x = a.name.toLowerCase(), y = b.name.toLowerCase();
      return x < y ? -1 : x > y ? 1 : (a.code < b.code ? -1 : 1);
    });
}

function dsOverrideRoute(type, routeCode, knownCodes) {
  if (String(type || '').trim() !== 'Bus') return { ok: true, routeCode: '' };
  var code = String(routeCode || '').trim();
  if (!code) return { error: 'Pick which bus. (To put them back on their usual bus, choose "Usual" instead.)' };
  var codes = dsRouteCodeIndex(knownCodes);
  if (codes && !codes[code.toLowerCase()]) {
    return { error: '"' + code + '" is not a bus. Pick one from the list.' };
  }
  return { ok: true, routeCode: codes ? codes[code.toLowerCase()] : code };
}

function dsStandingValidate(rows, knownCodes) {
  rows = Array.isArray(rows) ? rows : [];
  var codes = dsRouteCodeIndex(knownCodes);
  if (rows.length > DS_STANDING_MAX_ROWS) {
    return { error: 'At most ' + DS_STANDING_MAX_ROWS + ' rows.' };
  }
  var covered = {}, out = [];
  for (var i = 0; i < rows.length; i++) {
    var r = rows[i] || {};
    var type = String(r.type || '').trim();
    if (DS_STANDING_TYPES.indexOf(type) === -1) {
      return { error: 'Row ' + (i + 1) + ': type must be one of ' + DS_STANDING_TYPES.join(', ') + '.' };
    }
    var routeCode = type === 'Bus' ? String(r.routeCode || '').trim() : '';
    if (type === 'Bus' && !routeCode) return { error: 'Row ' + (i + 1) + ': a bus row needs the route code.' };
    if (codes && type === 'Bus' && !codes[routeCode.toLowerCase()]) {
      return { error: 'Row ' + (i + 1) + ': "' + routeCode + '" is not a route code. Use one of ' +
        Object.keys(codes).map(function (k) { return codes[k]; }).sort().join(', ') +
        '. A bus number, a van number or a stick colour goes in the Note.' };
    }
    if (codes) routeCode = codes[routeCode.toLowerCase()] || routeCode;   // fix the casing while we are here
    var seen = {}, days = [];
    (Array.isArray(r.days) ? r.days : String(r.days || '').split(/[,\s]+/)).forEach(function (d) {
      var t = dsDayToken(d);
      if (t && !seen[t]) { seen[t] = 1; days.push(t); }
    });
    days.sort(function (a, b) { return DS_WEEKDAYS.indexOf(a) - DS_WEEKDAYS.indexOf(b); });

    var every = parseInt(r.every, 10);
    if (isNaN(every) || every < 1) every = 1;
    if (every > 8) return { error: 'Row ' + (i + 1) + ': a cycle longer than 8 weeks is almost ' +
      'certainly a typo — record it as dated changes instead.' };
    var from = String(r.from || '').slice(0, 10);
    if (every > 1) {
      if (!/^\d{4}-\d{2}-\d{2}$/.test(from)) {
        return { error: 'Row ' + (i + 1) + ': a row that repeats every ' + every +
          ' weeks needs a "from" date — a date it DOES apply on. Without it nobody can tell which ' +
          'week is which, and the child would be on the wrong bus half the time.' };
      }
      var dow = dsDayOfWeek(from);
      var anchorDay = (dow >= 1 && dow <= 5) ? DS_WEEKDAYS[dow - 1] : '';
      var spanDays = days.length ? days : DS_WEEKDAYS;
      if (!anchorDay || spanDays.indexOf(anchorDay) === -1) {
        return { error: 'Row ' + (i + 1) + ': ' + from + ' is a ' +
          (anchorDay || 'weekend day') + ' — the "from" date has to be one of the days this row ' +
          'covers (' + spanDays.join(', ') + '), because that is what sets which week is which.' };
      }
    } else {
      from = '';                                   // a weekly row has no phase to anchor
    }

    var span2 = days.length ? days : DS_WEEKDAYS;
    for (var j = 0; j < span2.length; j++) {
      var d = span2[j], priors = covered[d] || [];
      for (var q = 0; q < priors.length; q++) {
        var prev = priors[q];
        if (every < 2 || prev.every < 2) {
          return { error: d + ' is covered by two rows — each school day may have one answer, ' +
            'unless both rows repeat and take turns.' };
        }
        if (prev.every !== every) {
          return { error: d + ' has two rows on different cycles (' + prev.every + ' weeks and ' +
            every + ' weeks). Rows that share a day must repeat over the same number of weeks.' };
        }
        var gap = dsIsoDays_(from) - dsIsoDays_(prev.from);
        if (((gap % (every * 7)) + every * 7) % (every * 7) === 0) {
          return { error: d + ' has two rows that land on the SAME ' + d + 's — ' + prev.from +
            ' and ' + from + ' are ' + Math.abs(gap) / 7 + ' week(s) apart, which is a whole ' +
            'number of cycles. Move one by a week.' };
        }
      }
      (covered[d] = covered[d] || []).push({ every: every, from: from });
    }
    out.push({ type: type, routeCode: routeCode, destination: String(r.destination || '').trim(),
               note: String(r.note || '').trim(), days: days, every: every, from: from });
  }
  return { ok: true, rows: out };
}

function dsIsoDays_(key) {
  var k = String(key || '').slice(0, 10);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(k)) return 0;
  return Math.round(Date.UTC(+k.slice(0, 4), +k.slice(5, 7) - 1, +k.slice(8, 10)) / 86400000);
}

function dsKgChanges(board, routes) {
  routes = routes || {};
  var norm = dsGradeKey;
  var pop = dsFlatList(board).filter(function (r) {
    return dsIsK4K5(r.grade) && !r.midday;
  });

  function lineOf(r) {
    var people = r.expected ? dsAuthPickupsFor(r.pickupAuth) : [];
    if (!r.expected) {
      return { kind: 'NOT COMING', what: r.reason || 'NOT EXPECTED', detail: r.detail || '',
               note: '', by: '', people: [] };
    }
    if (r.overridden || (r.fromRouteCode && !r.standing)) {
      var fromList = (r.fromRoutes && r.fromRoutes.length) ? r.fromRoutes
        : ((r.fromRouteCode || r.fromRouteName) ? [{ code: r.fromRouteCode, name: r.fromRouteName }] : []);
      var from = fromList.length
        ? 'Bus — ' + fromList.map(function (fr) {
            return (dsRouteFor(routes, fr.code, fr.name) || {}).name || fr.name || fr.code;
          }).join(' / ')
        : (r.type === 'Bus' ? 'not the bus' : 'usual');
      var to = r.type === 'Bus'
        ? 'Bus — ' + (r.routes || []).map(function (label, i) {
            var rt = dsRouteFor(routes, (r.routeCodes || [])[i] || '', label);
            return (rt && rt.name) || label;
          }).join(' / ')
        : r.type + (r.overrideDestination ? ' → ' + r.overrideDestination : '');
      return { kind: 'DIFFERENT', what: from + ' → ' + to, detail: '',
               note: r.overrideNote || '', by: r.overrideBy || '', people: people };
    }
    if (r.reason === 'PICKUP PLANNED' || r.reason === 'GAME DAY') {
      return { kind: 'CONFIRM', what: r.reason, detail: r.detail || '', note: '', by: '', people: people };
    }
    if (people.length) {
      return { kind: 'AUTH', what: 'not on the FACTS list', detail: '', note: '', by: '', people: people };
    }
    return null;   // nothing is different about this child today, so they are not on the page
  }

  function rowOf(r, line, lane, kind, what) {
    return {
      name: r.name, grade: norm(r.grade), teacher: r.homeroomTeacher || '', lane: lane,
      kind: kind || line.kind, what: what === undefined ? line.what : what,
      detail: kind ? '' : (line.detail || ''),
      note: kind ? '' : (line.note || ''), by: kind ? '' : (line.by || ''),
      people: kind ? [] : (line.people || [])
    };
  }

  var buses = {}, ramp = [], n = 0;
  function bus(code, label) {
    var rt = dsRouteFor(routes, code, label);
    var name = (rt && rt.name) || label || code || 'Bus';
    var key = String(code || name).trim().toLowerCase();
    if (!buses[key]) {
      buses[key] = { code: code || '', name: name, colour: (rt && rt.colour) || '',
                     vehicle: (rt && rt.vehicle) || '', rows: [] };
    }
    return buses[key];
  }

  pop.forEach(function (r) {
    var line = lineOf(r);
    if (!line) return;
    n++;
    if (r.routes && r.routes.length) {
      r.routes.forEach(function (label, i) { bus((r.routeCodes || [])[i] || '', label).rows.push(rowOf(r, line, 'Bus')); });
    } else {
      ramp.push(rowOf(r, line, r.type || 'Car'));
    }
    if (line.kind === 'DIFFERENT') {
      var offs = (r.fromRoutes && r.fromRoutes.length) ? r.fromRoutes
        : ((r.fromRouteCode || r.fromRouteName) ? [{ code: r.fromRouteCode, name: r.fromRouteName }] : []);
      offs.forEach(function (fr) {
        bus(fr.code, fr.name).rows.push(rowOf(r, line, 'Bus', 'OFF THIS BUS',
          r.type === 'Bus' ? 'on another bus today' : (r.type + ' today')));
      });
    }
  });

  var byName = dsByName;   // was a twelfth copy of the same three-way compare
  var busList = Object.keys(buses).map(function (k) { buses[k].rows.sort(byName); return buses[k]; })
    .sort(dsByName);
  ramp.sort(function (a, b) {
    var d = dsGradeNum(a.grade) - dsGradeNum(b.grade);
    return d ? d : byName(a, b);
  });

  return {
    buses: busList, ramp: ramp,
    counts: {
      population: pop.length, changes: n,
      buses: busList.reduce(function (t, b) { return t + b.rows.length; }, 0),
      ramp: ramp.length
    }
  };
}

function dsWalkUpSheet(walkUp) {
  var rows = (walkUp && walkUp.rows) || [];
  var norm = dsGradeKey;
  var by = function (a, b) {
    var d = dsGradeNum(a.grade) - dsGradeNum(b.grade);   // was a verbatim re-type of this
    if (d) return d;
    if (a.teacher !== b.teacher) return a.teacher < b.teacher ? -1 : 1;
    return a.name < b.name ? -1 : a.name > b.name ? 1 : 0;
  };
  var pick = function (r) {
    return {
      name: r.name, grade: norm(r.grade), teacher: r.teacher || '', destination: r.destination || '',
      kind: r.kind || '', why: r.why || '', changed: !!r.overridden,
      note: [r.frequency === 'Occasional' ? 'occasional' : '', r.note || '',
             (r.notes || []).map(function (n) { return n.text; }).join(' · '),
             r.overrideNote ? 'TODAY: ' + r.overrideNote : '',
             r.onRoster === false ? 'NOT on the current roster' : ''].filter(String).join(' · ')
    };
  };
  var walking = rows.filter(function (r) { return r.walking; }).map(pick).sort(by);
  var notWalking = rows.filter(function (r) { return !r.walking; }).map(pick).sort(by);
  return { walking: walking, notWalking: notWalking,
           counts: { onList: rows.length, walking: walking.length, notWalking: notWalking.length },
           dayName: (walkUp && walkUp.dayName) || '' };
}

function dsMergeOverrides(standing, today) {
  var out = {};
  Object.keys(standing || {}).forEach(function (id) { out[id] = standing[id]; });
  Object.keys(today || {}).forEach(function (id) { out[id] = today[id]; });
  return out;
}

function dsApplyWalkUps(board, walkUp) {
  var byId = {};
  ((walkUp && walkUp.rows) || []).forEach(function (w) { byId[w.id] = w; });
  ((board && board.groups) || []).forEach(function (g) {
    g.rows.forEach(function (r) {
      var w = byId[r.id];
      if (!w) return;
      r.walkUp = true;
      r.walkUpWalking = !!w.walking;
      r.walkUpTo = w.destination || '';
      r.walkUpWhy = w.walking ? '' : (w.why || w.kind || '');
    });
  });
  return board;
}

function dsBuildSignedOut(values, dayKey) {
  var out = {};
  if (!values || values.length < 2) return out;
  var h = dsHeaderMap(values[0]);
  var get = dsGetter(h);
  for (var r = 1; r < values.length; r++) {
    var row = values[r];
    if (get(row, 'Date').slice(0, 10) !== dayKey) continue;
    var type = get(row, 'Type');
    var sid = get(row, 'PersonKey');
    if (!sid) continue;
    if (type === 'student_early_out') {
      if (get(row, 'PickupMatch') === 'mismatch') continue;
      out[sid] = { at: get(row, 'Timestamp').slice(11, 16), withWhom: get(row, 'GuardianName') };
    } else if (type === 'student_return_in') {
      delete out[sid];
    }
  }
  return out;
}

function dsBuildCalledAhead(values, dayKey) {
  var plans = {};
  if (!values || values.length < 2) return plans;
  var h = dsHeaderMap(values[0]);
  var get = dsGetter(h);
  var claimed = {};
  for (var c = 1; c < values.length; c++) {
    if (get(values[c], 'Date').slice(0, 10) !== dayKey) continue;
    var ct = get(values[c], 'Type'), cid = get(values[c], 'PersonKey');
    if (!cid) continue;
    if (ct === 'student_early_out' && get(values[c], 'PickupMatch') === 'mismatch') continue;
    if (ct === 'student_early_out' || ct === 'pickup_flag') claimed[cid] = true;
  }
  for (var r = 1; r < values.length; r++) {
    var row = values[r];
    if (get(row, 'Date').slice(0, 10) !== dayKey) continue;
    if (get(row, 'Type') !== 'dismissal_planned') continue;
    if (get(row, 'FlagStatus').toLowerCase() === 'cancelled') continue;
    var sid = get(row, 'PersonKey');
    if (!sid || claimed[sid]) continue;
    plans[sid] = { at: get(row, 'ExpectedBack').slice(0, 5),
                   reason: get(row, 'Reason'),
                   guardian: get(row, 'GuardianName') };
  }
  return plans;
}

function dsBuildReturned(values, dayKey) {
  var back = {};
  if (!values || values.length < 2) return back;
  var h = dsHeaderMap(values[0]);
  var get = dsGetter(h);
  for (var r = 1; r < values.length; r++) {
    var row = values[r];
    if (get(row, 'Date').slice(0, 10) !== dayKey) continue;
    var type = get(row, 'Type');
    var sid = get(row, 'PersonKey');
    if (!sid) continue;
    if (type === 'student_early_out') {
      if (get(row, 'PickupMatch') === 'mismatch') continue;
      delete back[sid];
    } else if (type === 'student_return_in') {
      back[sid] = { at: get(row, 'Timestamp').slice(11, 16) };
    }
  }
  return back;
}

function dsBuildPickups(values) {
  var out = {};
  if (!values || values.length < 2) return out;
  var h = dsHeaderMap(values[0]);
  var get = dsGetter(h);
  for (var r = 1; r < values.length; r++) {
    var row = values[r];
    var sid = get(row, 'studentId');
    if (!sid) continue;
    var last = get(row, 'lastName'), first = get(row, 'firstName');
    var nm = (last + (last && first ? ', ' : '') + first).trim();
    if (!nm) continue;
    (out[sid] = out[sid] || []).push({
      name: nm,
      rel: get(row, 'relationship'),
      cell: get(row, 'cellPhone'),
      home: get(row, 'homePhone'),
      work: get(row, 'workPhone'),
      email: get(row, 'email'),
      note: get(row, 'note'),
      order: Number(get(row, 'portalSortOrder') || 99)
    });
  }
  Object.keys(out).forEach(function (sid) {
    out[sid].sort(function (a, b) {
      if (a.order !== b.order) return a.order - b.order;
      return a.name < b.name ? -1 : a.name > b.name ? 1 : 0;
    });
  });
  return out;
}

function dsFlatList(board) {
  var by = {}, order = [];
  (board.groups || []).forEach(function (g) {
    g.rows.forEach(function (r) {
      var e = by[r.id];
      if (!e) {
        e = by[r.id] = {
          id: r.id, name: r.name, grade: r.grade, type: r.type,
          routes: [], routeCodes: [], vehicle: r.vehicle, split: r.split,
          building: r.building, pickup: r.pickup, walkTo: r.walkTo, familyId: r.familyId,
          homeroom: r.homeroom, homeroomTeacher: r.homeroomTeacher,
          overridden: r.overridden, overrideNote: r.overrideNote,
          overrideBy: r.overrideBy || '', overrideAt: r.overrideAt || '',
          overrideDestination: r.overrideDestination || '',
          standing: !!r.standing, standingNote: r.standingNote || '',
          fromRouteCode: r.fromRouteCode || '', fromRouteName: r.fromRouteName || '',
          fromRoutes: r.fromRoutes || [],
          pickupAuth: r.pickupAuth || [],
          notes: r.notes || [],
          special: r.special || null,
          enrichment: !!r.enrichment, midday: !!r.midday,
          walkUp: !!r.walkUp, walkUpWalking: !!r.walkUpWalking,
          walkUpTo: r.walkUpTo || '', walkUpWhy: r.walkUpWhy || '',
          expected: r.expected, reason: r.reason, detail: r.detail, note: r.note
        };
        order.push(e);
      }
      var label = r.routeName || r.routeCode;
      if (label && e.routes.indexOf(label) === -1) {
        e.routes.push(label);
        e.routeCodes.push(r.routeCode || '');     // keep the two arrays index-aligned
      }
      if (!r.expected && e.expected) {
        e.expected = false; e.reason = r.reason; e.detail = r.detail;
      }
    });
  });
  order.sort(dsByName);
  return order;
}

function dsStudentCard(id, flat, pickups) {
  var me = null;
  for (var i = 0; i < (flat || []).length; i++) {
    if (flat[i].id === id) { me = flat[i]; break; }
  }
  if (!me) return null;

  var sibs = (flat || []).filter(function (r) {
    return me.familyId && r.familyId === me.familyId && r.id !== id;
  }).map(function (r) {
    return { id: r.id, name: r.name, grade: r.grade, type: r.type,
             routes: r.routes || [], routeCodes: r.routeCodes || [],
             pickup: r.pickup, expected: r.expected, reason: r.reason };
  });
  sibs.sort(dsByName);

  var pk = (pickups || {})[id];
  return {
    student: me,
    familyId: me.familyId || '',
    siblings: sibs,
    pickups: pk || [],
    hasPickups: !!(pk && pk.length),
    pickupsLoaded: !!pickups            // false while the second phase is still in flight
  };
}

function dsBuildWalkers(values) {
  var out = {};
  if (!values || values.length < 2) return out;
  var h = dsHeaderMap(values[0]);
  var get = dsGetter(h);
  for (var r = 1; r < values.length; r++) {
    var row = values[r];
    var id = get(row, 'Student ID');
    if (!id) continue;
    if (get(row, 'Status') === 'Removed') { delete out[id]; continue; }
    out[id] = {
      id: id,
      name: get(row, 'Student Name'),
      grade: dsGradeKey(get(row, 'Grade')),   // same canonical token as the roster
      teacher: get(row, 'Teacher'),
      frequency: get(row, 'Frequency') || 'Daily',
      onlyDays: get(row, 'Only Days').split(/[,\s]+/).map(dsDayToken).filter(String),
      destination: get(row, 'Destination'),
      exceptDay: get(row, 'Except Day'),
      exceptDays: dsParseDays(get(row, 'Except Day')).days,
      exceptReason: get(row, 'Except Reason'),
      exceptDestination: get(row, 'Except Destination'),
      note: get(row, 'Note'),
      by: get(row, 'By'), at: get(row, 'At')
    };
  }
  return out;
}

var DS_WALKER_FREQ = ['Daily', 'Occasional'];

function dsWalkerValidate(patch) {
  patch = patch || {};
  var s = function (v, cap) { return String(v == null ? '' : v).trim().slice(0, cap); };
  var freq = s(patch.frequency, 20) || 'Daily';
  if (DS_WALKER_FREQ.indexOf(freq) === -1) {
    return { error: 'Frequency must be Daily or Occasional.', patch: null };
  }
  var ex = dsParseDays(patch.exceptDay);
  if (ex.invalid) {
    return { error: 'I could not read "' + ex.raw + '" as weekdays. Use days like Mon, Tue, Fri.',
             patch: null };
  }
  var only = dsParseDays(patch.onlyDays);
  if (only.invalid) {
    return { error: 'I could not read "' + only.raw + '" as weekdays. Use days like Mon, Tue, Fri.',
             patch: null };
  }
  if (only.days.length && ex.days.length &&
      only.days.every(function (d) { return ex.days.indexOf(d) !== -1; })) {
    return { error: 'That leaves no day at all: she would only walk on ' + only.days.join(', ') +
                    ', and those are the days she is excepted from.', patch: null };
  }
  return { error: '', patch: {
    frequency: freq,
    destination: s(patch.destination, 120),
    exceptDay: ex.days.join(','),
    exceptReason: s(patch.exceptReason, 60),
    exceptDestination: s(patch.exceptDestination, 120),
    onlyDays: only.days.join(','),
    note: s(patch.note, 300)
  } };
}

function dsWalkUpList(flat, walkers, att, outs, dayName, occasionalToday, overrides, returned, feeds) {
  feeds = feeds || {};
  var noSchool = feeds.noSchool || {}, calledAhead = feeds.calledAhead || {};
  var standing = feeds.standing || {};
  var byId = {};
  (flat || []).forEach(function (r) { byId[r.id] = r; });
  var rows = [];
  Object.keys(walkers || {}).forEach(function (id) {
    var w = walkers[id];
    var st = byId[id] || null;
    var ov = (overrides || {})[id] || null;
    var sd = standing[id] || null;            // her every-week arrangement for today, if she has one
    var v = dsClassify(st || {}, (att || {})[id], (outs || {})[id], null, (returned || {})[id],
                       noSchool[id], calledAhead[id]);

    var isExceptDay = !!(dayName && (w.exceptDays || []).length &&
      dsDaysInclude(w.exceptDays, dayName));
    var offDay = !!(dayName && (w.onlyDays || []).length && !dsDaysInclude(w.onlyDays, dayName));

    var confirmedToday = !!(occasionalToday || {})[id];

    var moved = null;
    if (ov && ov.type && ov.type !== 'Staff Kid') moved = { o: ov, standing: false };
    else if (!ov && sd && sd.type && sd.type !== 'Staff Kid') moved = { o: sd, standing: true };

    var dest = (ov && ov.destination) ? ov.destination
             : (isExceptDay && w.exceptDestination && !confirmedToday) ? w.exceptDestination
             : w.destination;

    var walking = true, why = '', kind = '';
    if (!v.expected) {
      walking = false; kind = v.reason; why = v.detail;
    } else if (v.reason === 'PICKUP PLANNED' || v.reason === 'GAME DAY') {
      walking = false; kind = v.reason; why = v.detail || '';
    } else if (moved) {
      walking = false;
      kind = moved.o.type === 'Bus' ? 'RIDING THE BUS'
           : moved.o.type === 'Car' ? 'GOING BY CAR'
           : moved.o.type === 'Early Bird' ? 'EARLY BIRD'
           : String(moved.o.type).toUpperCase();
      var lane = (st && st.routes && st.routes.length) ? st.routes.join(' / ')
               : (moved.o.routeCode ? 'route ' + moved.o.routeCode : '');
      why = moved.standing
        ? [lane, moved.o.note || '', 'every week'].filter(String).join(' — ')
        : lane;
    } else if (confirmedToday) {
      walking = true; kind = ''; why = '';
    } else if (offDay) {
      walking = false; kind = 'NOT TODAY';
      why = 'walks on ' + w.onlyDays.join(', ') + ' only';
    } else if (isExceptDay) {
      walking = false; kind = 'IN A SPECIAL';
      why = (w.exceptReason ? 'in ' + w.exceptReason : 'not walked today') +
        (w.exceptDestination ? ' — goes ' + w.exceptDestination : ' — already up by the HS');
    } else if (w.frequency === 'Occasional') {          // confirmedToday already returned above
      walking = false; kind = 'NOT TODAY';
      why = 'occasional — only when the office confirms';
    }
    rows.push({
      id: id, name: w.name || (st ? st.name : id), grade: w.grade || (st ? st.grade : ''),
      teacher: w.teacher, frequency: w.frequency, onlyDays: w.onlyDays || [],
      destination: dest, standingDestination: w.destination, note: w.note,
      by: w.by || '', at: w.at || '',
      exceptDay: w.exceptDay, exceptReason: w.exceptReason,
      exceptDestination: w.exceptDestination,
      walking: walking, kind: kind, why: why,
      movedType: moved ? moved.o.type : '', movedStanding: !!(moved && moved.standing),
      notes: (st && st.notes) || [],
      overridden: !!ov, overrideNote: ov ? (ov.note || '') : '',
      overrideBy: ov ? (ov.by || '') : '', overrideAt: ov ? (ov.at || '') : '',
      onRoster: !!st
    });
  });
  rows.sort(dsByName);
  var walkingN = rows.filter(function (r) { return r.walking; }).length;
  return {
    dayName: dayName || '', rows: rows,
    counts: { onList: rows.length, walking: walkingN, notWalking: rows.length - walkingN }
  };
}

function dsBuildRoutes(values, dayKey) {
  var out = {};
  if (!values || values.length < 2) return out;
  var h = dsHeaderMap(values[0]);
  var get = dsGetter(h);
  var today = String(dayKey || '').slice(0, 10);
  var subs = [];
  for (var r = 1; r < values.length; r++) {
    var row = values[r];
    var code = get(row, 'Route Code');
    if (!code) continue;
    var from = dsIsoDate(get(row, 'From')), thru = dsIsoDate(get(row, 'Through')) || from;
    if (from) {
      if (today && today >= from && today <= thru) subs.push({ code: code, row: row, from: from, thru: thru });
      continue;
    }
    var e = out[code] || (out[code] = {
      code: code, name: get(row, 'Route Name'), colour: get(row, 'Colour'),
      vehicle: get(row, 'Vehicle'), drivers: []
    });
    if (!e.name) e.name = get(row, 'Route Name');
    if (!e.colour) e.colour = get(row, 'Colour');
    if (!e.vehicle) e.vehicle = get(row, 'Vehicle');
    var drv = get(row, 'Driver');
    if (drv) {
      e.drivers.push({
        session: get(row, 'Session') || 'PM',
        name: drv,
        phone: get(row, 'Phone'),
        days: get(row, 'Days').split(/[,\s]+/).filter(String),
        note: get(row, 'Note')
      });
    }
  }

  subs.forEach(function (sub) {
    var e = out[sub.code];
    if (!e) return;                       // a substitution for a route nobody rides is not a route
    var g = function (name) { return dsGetter(h)(sub.row, name); };
    var veh = g('Vehicle'), col = g('Colour'), drv = g('Driver');
    if (veh) e.vehicle = veh;
    if (col) e.colour = col;
    if (drv) {
      e.drivers.push({ session: g('Session') || 'PM', name: drv, phone: g('Phone'),
                       days: g('Days').split(/[,\s]+/).filter(String), note: g('Note') });
    }
    e.substituted = true;
    e.subNote = g('Note') || (veh ? 'running as ' + veh + ' today' : 'changed for today');
    e.subFrom = sub.from;
    e.subThrough = sub.thru;
  });
  return out;
}

function dsRouteFor(routes, code, label) {
  routes = routes || {};
  var c = String(code || '').trim();
  if (c && routes[c]) return routes[c];
  var l = String(label || '').trim().toLowerCase();
  if (!l) return null;
  if (routes[label]) return routes[label];                 // a label that IS a code
  var keys = Object.keys(routes);
  for (var i = 0; i < keys.length; i++) {
    var rt = routes[keys[i]];
    var n = String(rt.name || '').trim().toLowerCase();
    if (n && (l === n || l.indexOf(n) === 0)) return rt;
  }
  return null;
}

function dsDriversFor(route, session, dayName) {
  if (!route) return [];
  return (route.drivers || []).filter(function (x) {
    if (String(x.session).toUpperCase() !== String(session).toUpperCase()) return false;
    return dsDaysInclude(x.days, dayName);
  });
}

var DS_ROLES = ['Admin', 'Office', 'Ramp', 'Walk-Up', 'Teacher', 'Transportation', 'Specials'];

function dsBuildRoles(values) {
  var out = [];
  if (!values || values.length < 2) return out;
  var h = dsHeaderMap(values[0]);
  var get = dsGetter(h);
  for (var r = 1; r < values.length; r++) {
    var email = get(values[r], 'Email').toLowerCase();
    var role = get(values[r], 'Role');
    if (!email || !role) continue;
    out.push({
      role: role, email: email,
      admin: /^(y|yes|true)$/i.test(get(values[r], 'Admin')),
      note: get(values[r], 'Note')
    });
  }
  return out;
}

function dsPermissions(email, roleRows, teacherName, homeroomTeachers) {
  var e = String(email || '').toLowerCase();
  var mine = (roleRows || []).filter(function (r) { return r.email === e; });
  var roles = {}, adminOf = {};
  mine.forEach(function (r) {
    roles[r.role] = true;
    if (r.admin) adminOf[r.role] = true;
  });

  var teacherImplicit = false;
  if (teacherName && homeroomTeachers &&
      homeroomTeachers[dsNameKey(teacherName)] === true) {
    teacherImplicit = true;
    roles['Teacher'] = true;
  }

  var isAdmin = !!roles['Admin'];
  if (isAdmin) DS_ROLES.forEach(function (r) { adminOf[r] = true; });

  return {
    email: e,
    roles: Object.keys(roles).sort(),
    adminOf: Object.keys(adminOf).sort(),
    teacherName: teacherName || '',
    canChangeAnyone: isAdmin || !!roles['Office'] || !!roles['Ramp'],
    canChangeWalkUp: isAdmin || !!roles['Office'] || !!roles['Ramp'] || !!roles['Walk-Up'],
    canChangeOwnClass: isAdmin || !!roles['Office'] || !!roles['Ramp'],
    canEditRoutes: isAdmin || !!roles['Transportation'],
    canAuthorizePickup: isAdmin || !!roles['Office'],
    canEditStanding: isAdmin || !!roles['Office'],
    canEditWalkUp: isAdmin || !!roles['Office'] || !!roles['Walk-Up'],
    canManageRoles: Object.keys(adminOf).length > 0,
    isAdmin: isAdmin,
    teacherImplicit: teacherImplicit
  };
}

function dsHomeroomTeacherSet(roster) {
  var out = {};
  (roster || []).forEach(function (r) {
    var t = dsNameKey(r.homeroomTeacher || '');
    if (t) out[t] = true;
  });
  return out;
}

function dsCanChange(perm, student, isWalkUp) {
  if (perm && perm.canChangeAnyone) return { ok: true, why: '' };
  if (isWalkUp && perm && perm.canChangeWalkUp) return { ok: true, why: '' };
  if (perm && perm.canChangeWalkUp) {
    return { ok: false, why: 'You can change children on the approved walk-up list. For anyone ' +
      'else, tell the office and they\'ll record it.' };
  }
  return { ok: false, why: 'Changes are recorded by the office or the ramp — tell them and ' +
    'they\'ll record it.' };
}

function dsIsK4K5(grade) {
  var t = String(grade == null ? '' : grade).trim().toUpperCase().replace(/\.0+$/, '');
  return t === 'K4' || t === 'K5';
}

function dsIsKgGrade(grade) {
  var g = dsGradeNum(grade);
  return g === -2 || g === -1;
}

function dsScopeRows(rows, teacherName, scope) {
  if (scope === 'kg') {
    return (rows || []).filter(function (r) { return dsIsKgGrade(r.grade); });
  }
  rows = rows || [];
  if (scope === 'school') return rows.slice();
  var t = dsNameKey(teacherName || '');
  if (!t) return [];                       // no match is NOT everyone — fail closed and say so
  var mine = rows.filter(function (r) {
    return dsNameKey(r.homeroomTeacher || '') === t;
  });
  if (scope !== 'grade') return mine;
  var grades = {};
  mine.forEach(function (r) { grades[dsGradeKey(r.grade)] = true; });
  return rows.filter(function (r) { return grades[dsGradeKey(r.grade)] === true; });
}

function dsBuildNotes(values) {
  var out = {};
  if (!values || values.length < 2) return out;
  var h = dsHeaderMap(values[0]);
  var get = dsGetter(h);
  for (var r = 1; r < values.length; r++) {
    var row = values[r];
    var sid = get(row, 'Student ID').replace(/\.0+$/, '');
    var text = get(row, 'Note');
    if (!sid || !text) continue;
    var status = get(row, 'Status').toLowerCase();
    if (status && status !== 'active') continue;
    (out[sid] = out[sid] || []).push({
      id: get(row, 'Note ID'), text: text, by: get(row, 'By'), at: get(row, 'At')
    });
  }
  return out;
}

function dsNoteValidate(text) {
  var t = String(text == null ? '' : text).replace(/\s+/g, ' ').trim();
  if (!t) return { error: 'Type the note first.' };
  if (t.length > 300) return { error: 'That note is too long — keep it under 300 characters.' };
  return { ok: true, text: t };
}

function dsDefaultView(perm) {
  var roles = (perm && perm.roles) || [];
  var only = function (allowed) {
    return roles.length > 0 && roles.every(function (r) { return allowed.indexOf(r) !== -1; });
  };
  if (roles.indexOf('Specials') !== -1 && only(['Specials', 'Teacher'])) {
    return { mode: 'class', scope: 'school', route: '', types: [], grades: [], excludeTypes: [] };
  }
  if (roles.length === 1 && roles[0] === 'Teacher') {
    return { mode: 'class', scope: 'class', route: '', types: [], grades: [], excludeTypes: [] };
  }
  return null;
}

function dsGradeKey(g) {
  var s = String(g == null ? '' : g).trim().toUpperCase().replace(/\.0+$/, '');
  s = s.replace(/^(\d+)(ST|ND|RD|TH)$/, '$1');      // '6TH' -> '6'
  return /^0\d$/.test(s) ? s.replace(/^0+/, '') : s;
}

function dsGradeNum(g) {
  var t = String(g == null ? '' : g).trim().toUpperCase().replace(/\.0+$/, '');
  if (t === 'K4') return -2;
  if (t === 'K5' || t === 'K') return -1;
  var n = parseInt(t, 10);
  return isNaN(n) ? 99 : n;
}

function dsClassSections(rows) {
  var changed = [], rest = [];
  (rows || []).forEach(function (r) {
    var isChange = !r.expected || !!r.reason || !!r.overridden || !!(r.walkUp && !r.walkUpWalking);
    (isChange ? changed : rest).push(r);
  });
  var byName = dsByName;   // was a twelfth copy of the same three-way compare
  changed.sort(function (a, b) {
    if (a.expected !== b.expected) return a.expected ? 1 : -1;   // not coming out first
    return byName(a, b);
  });
  rest.sort(byName);
  return { changed: changed, rest: rest };
}

function dsPeerTeachers(rows, lo, hi) {
  var by = {};
  (rows || []).forEach(function (r) {
    var t = String(r.homeroomTeacher || '').trim();
    if (!t) return;
    var gn = dsGradeNum(r.grade);
    if (gn < lo || gn > hi) return;
    var k = dsNameKey(t);
    if (!k) return;
    if (!by[k]) by[k] = { name: t, grade: r.grade, gradeNum: gn, count: 0 };
    if (gn < by[k].gradeNum) { by[k].grade = r.grade; by[k].gradeNum = gn; }
    by[k].count++;
  });
  return Object.keys(by).map(function (k) { return by[k]; })
    .sort(function (a, b) {
      return a.gradeNum !== b.gradeNum ? a.gradeNum - b.gradeNum
           : a.name < b.name ? -1 : a.name > b.name ? 1 : 0;
    });
}

function dsResolveStaff(staff, typed) {
  var t = String(typed || '').trim().toLowerCase();
  if (!t) return { error: 'Type a name or an email.' };
  if (t.indexOf('@') !== -1) {
    var exact = (staff || []).filter(function (s) { return String(s.email).toLowerCase() === t; })[0];
    return exact ? { email: exact.email, name: exact.name } : { email: t };
  }
  var toks = t.split(/\s+/).filter(String);
  var hits = (staff || []).filter(function (s) {
    var n = String(s.name || '').toLowerCase();
    return toks.every(function (k) { return n.indexOf(k) !== -1; });
  });
  if (hits.length === 1) return { email: hits[0].email, name: hits[0].name };
  if (!hits.length) return { error: 'Nobody on staff matches "' + typed + '". Type the email instead.' };
  return { error: hits.length + ' people match "' + typed + '": ' +
    hits.slice(0, 6).map(function (s) { return s.name; }).join(', ') +
    (hits.length > 6 ? '…' : '') + ' — keep typing.' };
}

function dsBuildStaffDirectory(values, domain) {
  var out = [];
  if (!values || values.length < 2) return out;
  var h = dsHeaderMap(values[0]);
  var get = dsGetter(h);
  var d = String(domain || '').toLowerCase();
  var seen = {};
  for (var r = 1; r < values.length; r++) {
    var row = values[r];
    if (h['Active'] !== undefined && !/^(y|yes|true)$/i.test(get(row, 'Active'))) continue;
    var nm = (get(row, 'Last Name') + ' ' + get(row, 'First Name')).trim();
    if (!nm) continue;
    ['Email', 'Email2'].forEach(function (c) {
      var e = get(row, c).toLowerCase();
      if (!e || seen[e]) return;
      if (d && e.split('@')[1] !== d) return;              // a personal address can never sign in
      seen[e] = 1;
      out.push({ email: e, name: nm });
    });
  }
  out.sort(function (a, b) {
    return a.name < b.name ? -1 : a.name > b.name ? 1 : (a.email < b.email ? -1 : 1);
  });
  return out;
}

function dsBuildStaffNames(values) {
  var out = {};
  if (!values || values.length < 2) return out;
  var h = dsHeaderMap(values[0]);
  var get = dsGetter(h);
  for (var r = 1; r < values.length; r++) {
    var row = values[r];
    var nm = (get(row, 'Last Name') + ' ' + get(row, 'First Name')).trim();
    if (!nm) continue;
    ['Email', 'Email2'].forEach(function (c) {
      var e = get(row, c).toLowerCase();
      if (e) out[e] = nm;
    });
  }
  return out;
}

function dsClock12(hhmm) {
  var m = /^(\d{1,2}):(\d{2})$/.exec(String(hhmm || '').trim());
  if (!m) return String(hhmm || '');
  var h = Number(m[1]), ap = h >= 12 ? 'PM' : 'AM';
  h = h % 12; if (h === 0) h = 12;
  return h + ':' + m[2] + ' ' + ap;
}

function dsBuildSports(feed, dayKey) {
  if (!feed || typeof feed !== 'object') return { available: false, why: 'no feed', students: {}, teamsFailed: [] };
  if (String(feed.date || '').slice(0, 10) !== String(dayKey || '')) {
    return { available: false, why: 'feed is for ' + (feed.date || 'an unknown day') + ', not ' + dayKey, students: {}, teamsFailed: [] };
  }
  if (feed.ok === false) return { available: false, why: 'producer reported a failure', students: {}, teamsFailed: [] };
  if (!feed.students || typeof feed.students !== 'object' || Array.isArray(feed.students)) {
    return { available: false, why: 'feed has no students object', students: {}, teamsFailed: [] };
  }
  var students = {}, n = 0;
  Object.keys(feed.students).forEach(function (sid) {
    var list = Array.isArray(feed.students[sid]) ? feed.students[sid] : [];
    var keep = list.filter(function (e) { return e && (e.dismiss || e.depart); }).map(function (e) {
      return { team: String(e.team || e.sport || 'team'), title: String(e.title || ''),
               dismiss: String(e.dismiss || ''), depart: String(e.depart || ''), location: String(e.location || '') };
    });
    if (keep.length) { students[String(sid).trim()] = keep; n++; }
  });
  return { available: true, why: '', date: String(feed.date), generatedAt: String(feed.generatedAt || ''),
           teamsFailed: (feed.teamsFailed || []).map(String), students: students, count: n };
}

function dsSportsDetail(list) {
  var best = null;
  (list || []).forEach(function (e) {
    var t = e.dismiss || e.depart;
    if (!best || t < (best.dismiss || best.depart)) best = e;
  });
  if (!best) return '';
  return best.team + ' — posted ' + (best.dismiss ? 'dismissal ' : 'departure ') +
         dsClock12(best.dismiss || best.depart) + ' · confirm with the office';
}

function dsClassify(student, att, out, sports, back, noSchool, plan) {
  var v = dsClassifyRecorded_(student, att, out, back, noSchool);
  if (!v.expected || v.reason === 'BACK') return v;
  if (plan) {
    var when = plan.at ? dsClock12(plan.at) : '';
    var why = plan.reason || 'office took the call';
    return { expected: true, reason: 'PICKUP PLANNED',
             detail: (when ? when + ' — ' : '') + why + (plan.guardian ? ' (' + plan.guardian + ')' : '') };
  }
  if (sports && sports.length) {
    return { expected: true, reason: 'GAME DAY', detail: dsSportsDetail(sports) };
  }
  return v;
}

function dsClassifyRecorded_(student, att, out, back, noSchool) {
  if (out) {
    return {
      expected: false, reason: 'SIGNED OUT',
      detail: (out.at ? out.at + ' ' : '') + (out.withWhom ? 'with ' + out.withWhom : '')
    };
  }
  if (back) {
    return { expected: true, reason: 'BACK', detail: back.at ? 'returned ' + back.at : 'returned' };
  }
  if (noSchool) {
    return { expected: false, reason: 'NO SCHOOL', detail: 'K4/K5 morning cancelled — weather delay' };
  }
  var a = att || null;
  if (a) {
    if (a.code === 'ED' || /left early|early dismissal/i.test(a.status || '')) {
      return { expected: false, reason: 'LEFT EARLY', detail: a.reason || a.detail || '' };
    }
    if (a.code === 'AE' || a.code === 'AU' || /absent/i.test(a.status || '')) {
      return {
        expected: false, reason: 'ABSENT',
        detail: (a.excused === 'Y' ? 'excused' : a.excused === 'N' ? 'unexcused' : '') +
                (a.reason ? (a.excused ? ' — ' : '') + a.reason : '')
      };
    }
    if (a.code === 'LA' || a.code === 'TE' || a.code === 'TU' || /late|tardy/i.test(a.status || '')) {
      return { expected: true, reason: 'LATE', detail: a.reason || '' };
    }
  }
  return { expected: true, reason: '', detail: '' };
}

function dsBuildBoard(d, opts) {
  d = d || {}; opts = opts || {};
  var session = opts.session || 'PM';
  var att = d.attendance || {};
  var outs = d.signedOut || {};
  var backs = d.returned || {};             // left and came back today, keyed by student id
  var noSchool = d.noSchool || {};          // K4/K5 on a delayed morning — see dsBuildNoSchool
  var plans = d.calledAhead || {};          // a parent rang ahead — see dsBuildCalledAhead
  var notes = d.notes || {};               // standing facts about the child — see dsBuildNotes
  var sports = d.sports || {};              // posted sports dismissals, keyed by student id
  var ovr = d.overrides || {};
  var routes = opts.routes || {};
  var auth = opts.pickupAuth || {};          // temporary pickup authorizations, per student
  var specials = opts.specials || null;      // today's 8th-period specials, by homeroom / grade

  var wantMidday = !!opts.midday;
  var rows = (d.roster || []).filter(function (s) {
    if (s.session !== session) return false;
    return wantMidday ? dsIsMiddayLeaver(s) : true;
  });
  var byGroup = {}, notExpected = [], seen = {}, laneSeen = {};
  var nameByCode = {};
  rows.forEach(function (s) { if (s.routeCode && s.routeName && !nameByCode[s.routeCode]) nameByCode[s.routeCode] = s.routeName; });
  var counts = { total: 0, expected: 0, notExpected: 0, byType: {} };

  rows.forEach(function (s) {
    var o = ovr[s.id] || null;
    var type = o && o.type ? o.type : s.type;
    var routeCode = o && o.routeCode ? o.routeCode : s.routeCode;
    var v = dsClassify(s, att[s.id], outs[s.id], sports[s.id], backs[s.id], noSchool[s.id], plans[s.id]);

    var routeName = s.routeName, vehicle = s.vehicle, split = s.split;
    if (type !== 'Bus') {
      routeCode = ''; routeName = ''; vehicle = ''; split = false;
    } else if (routeCode !== s.routeCode) {
      var rt = routes[routeCode];
      routeName = nameByCode[routeCode] || (rt ? (rt.name || routeCode) : '');
      vehicle = rt ? (rt.vehicle || '') : '';
      split = false;                        // one route was chosen for today; nothing to confirm
    }

    var moved = !!o && s.type === 'Bus' && !!s.routeCode && (type !== 'Bus' || routeCode !== s.routeCode);

    var key = type === 'Bus' ? (routeName || routeCode || 'Bus') : type;
    var lk = s.id + '|' + key;
    if (laneSeen[lk]) {
      if (moved) laneSeen[lk].fromRoutes.push({ code: s.routeCode, name: s.routeName });
      return;
    }

    var entry = {
      id: s.id, name: s.name, grade: s.grade, type: type,
      routeCode: routeCode, routeName: routeName, vehicle: vehicle,
      split: split, building: s.building, pickup: s.pickup, walkTo: s.walkTo,
      familyId: s.familyId, homeroom: s.homeroom, homeroomTeacher: s.homeroomTeacher,
      note: s.note,

      overridden: !!(o && !o.standing), overrideNote: (o && !o.standing) ? (o.note || '') : '',
      overrideBy: (o && !o.standing) ? (o.by || '') : '', overrideAt: (o && !o.standing) ? (o.at || '') : '',
      overrideDestination: o ? (o.destination || '') : '',
      standing: !!(o && o.standing), standingNote: (o && o.standing) ? (o.note || '') : '',
      fromRouteCode: moved ? s.routeCode : '', fromRouteName: moved ? s.routeName : '',
      fromRoutes: moved ? [{ code: s.routeCode, name: s.routeName }] : [],   // every bus this row left
      pickupAuth: auth[s.id] || [],
      notes: notes[s.id] || [],
      special: specials ? dsSpecialFor(specials, s) : null,
      enrichment: !!s.enrichment,
      midday: dsIsMiddayLeaver(s),
      expected: v.expected, reason: v.reason, detail: v.detail
    };

    if (!seen[s.id]) { seen[s.id] = 1; counts.total++; }
    counts.byType[type] = (counts.byType[type] || 0) + 1;
    if (v.expected) counts.expected++; else { counts.notExpected++; notExpected.push(entry); }

    laneSeen[lk] = entry;
    (byGroup[key] = byGroup[key] || { key: key, type: type, rows: [] }).rows.push(entry);
  });

  var rank = { 'Bus': 0, 'Early Bird': 1, 'Staff Kid': 2, 'Car': 3 };
  var groups = Object.keys(byGroup).map(function (k) { return byGroup[k]; });
  groups.forEach(function (g) {
    g.rows.sort(dsByName);
    g.expected = g.rows.filter(function (r) { return r.expected; }).length;
    g.notExpected = g.rows.length - g.expected;
  });
  groups.sort(function (a, b) {
    var ra = rank[a.type] === undefined ? 9 : rank[a.type];
    var rb = rank[b.type] === undefined ? 9 : rank[b.type];
    return ra !== rb ? ra - rb : (a.key < b.key ? -1 : a.key > b.key ? 1 : 0);
  });
  notExpected.sort(dsByName);

  return {
    session: session, counts: counts, groups: groups, notExpected: notExpected,
    types: groups.map(function (g) { return g.type; }).filter(function (t, i, arr) {
      return arr.indexOf(t) === i;
    }),
    routes: groups.filter(function (g) { return g.type === 'Bus'; }).map(function (g) { return g.key; })
  };
}

function dsFilterBoard(board, f) {
  f = f || {};
  var q = String(f.q || '').trim().toLowerCase();
  var grades = f.grades && f.grades.length ? f.grades.map(dsGradeKey) : null;
  var notTypes = f.excludeTypes && f.excludeTypes.length ? f.excludeTypes : null;
  var types = f.types && f.types.length ? f.types : (f.type ? [f.type] : null);
  var keep = function (r) {
    if (types && types.indexOf(r.type) === -1) return false;
    if (notTypes && notTypes.indexOf(r.type) !== -1) return false;
    if (grades && grades.indexOf(dsGradeKey(r.grade)) === -1) return false;
    if (f.route && (r.routeName || r.routeCode) !== f.route) return false;
    if (f.pickup && r.pickup !== f.pickup) return false;
    if (f.expected === true && !r.expected) return false;
    if (f.expected === false && r.expected) return false;
    if (q) {
      var hay = (r.name + ' ' + r.id + ' ' + (r.routeName || '') + ' ' + (r.routeCode || '')).toLowerCase();
      if (hay.indexOf(q) === -1) return false;
    }
    return true;
  };
  var groups = [], counts = { total: 0, expected: 0, notExpected: 0, byType: {} }, seen = {};
  (board.groups || []).forEach(function (g) {
    var rows = g.rows.filter(keep);
    if (!rows.length) return;
    var exp = rows.filter(function (r) { return r.expected; }).length;
    rows.forEach(function (r) {
      if (!seen[r.id]) { seen[r.id] = 1; counts.total++; }
      counts.byType[r.type] = (counts.byType[r.type] || 0) + 1;
    });
    counts.expected += exp;
    counts.notExpected += rows.length - exp;
    groups.push({ key: g.key, type: g.type, rows: rows, expected: exp, notExpected: rows.length - exp });
  });
  return {
    session: board.session, counts: counts, groups: groups,
    notExpected: (board.notExpected || []).filter(keep),
    types: board.types, routes: board.routes
  };
}

function dsNameKey(s) {
  var t = String(s == null ? '' : s);
  if (typeof t.normalize === 'function') t = t.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  t = t.replace(/[\u00e9\u00e8\u00ea\u00eb]/g, 'e').replace(/[\u00e1\u00e0\u00e2\u00e4]/g, 'a')
       .replace(/[\u00ed\u00ee\u00ef]/g, 'i').replace(/[\u00f3\u00f4\u00f6]/g, 'o').replace(/[\u00fa\u00fb\u00fc]/g, 'u')
       .replace(/[\u00f1]/g, 'n').replace(/\uFFFD/g, '');
  var toks = t.toLowerCase().replace(/[^a-z0-9\s]/g, ' ').split(/\s+/).filter(String);
  return toks.slice(0, 2).join(' ');
}

function dsBuildSpecials(values, dayName) {
  var out = { byTeacher: {}, bySurname: {}, byGrade: {}, rows: 0 };
  if (!values || values.length < 2) return out;
  var h = dsHeaderMap(values[0]);
  var get = dsGetter(h);
  var normGrade = dsGradeKey;
  for (var r = 1; r < values.length; r++) {
    var row = values[r];
    var subject = get(row, 'Special');
    if (!subject) continue;
    var days = get(row, 'Day').split(/[,\s]+/).filter(String);
    if (!dsDaysInclude(days, dayName)) continue;
    var spec = { subject: subject, teacher: get(row, 'Teacher'), from: get(row, 'From'), note: get(row, 'Note'),
                 homeroomTeacher: get(row, 'Homeroom Teacher'), grade: normGrade(get(row, 'Grade')) };
    out.rows++;
    if (spec.homeroomTeacher) {
      var key = dsNameKey(spec.homeroomTeacher);
      out.byTeacher[key] = spec;
      if (key.indexOf(' ') === -1 && spec.grade) out.bySurname[key + '|' + spec.grade] = spec;
    } else if (spec.grade) out.byGrade[spec.grade] = spec;
  }
  return out;
}

function dsSpecialFor(specials, s) {
  if (!specials) return null;
  var k = dsNameKey(s.homeroomTeacher || '');
  if (k && specials.byTeacher[k]) return specials.byTeacher[k];
  var g = String(s.grade || '').trim().toUpperCase().replace(/\.0+$/, '');
  if (/^0\d$/.test(g)) g = g.replace(/^0+/, '');
  if (k && g && specials.bySurname) {
    var sur = specials.bySurname[k.split(' ')[0] + '|' + g];
    if (sur) return sur;
  }
  return specials.byGrade[g] || null;
}

var DS_RAMP_GRADES = ['K4', 'K5', '1', '2', '3', '4', '5'];
var DS_RAMP_TYPES = ['Bus', 'Car', 'Early Bird'];

function dsRampPopulation(r, opts) {
  opts = opts || {};
  var types = opts.types || DS_RAMP_TYPES;
  if (types.indexOf(r.type) === -1) return false;
  var g = dsGradeKey(r.grade);
  var grades = (opts.grades || DS_RAMP_GRADES).map(dsGradeKey);
  if (grades.indexOf(g) !== -1) return true;
  return !!opts.sixthAtEl && g === '6' && String(r.pickup || '').toUpperCase() === 'EL';
}

function dsRampChanges(board, routes, dayName) {
  routes = routes || {};
  var flat = dsFlatList(board);
  var norm = dsGradeKey;
  var pop = flat.filter(function (r) { return dsRampPopulation(r, { sixthAtEl: true }); });
  var lane = function (r) {
    if (r.routes && r.routes.length) {
      return r.routes.map(function (label, i) {
        var rt = dsRouteFor(routes, (r.routeCodes || [])[i] || '', label);
        return ((rt && rt.name) || label) + (rt && rt.substituted ? ' (' + (rt.subNote || 'different vehicle today') + ')' : '');
      }).join(' / ');
    }
    return r.type;
  };
  var byName = dsByName;   // was a twelfth copy of the same three-way compare

  var notExpected = pop.filter(function (r) { return !r.expected; }).map(function (r) {
    return { name: r.name, grade: norm(r.grade), lane: lane(r), reason: r.reason || 'NOT EXPECTED', detail: r.detail || '' };
  }).sort(byName);

  var groups = {};
  pop.forEach(function (r) {
    if (!r.special || !r.expected) return;
    var key = r.special.subject + '|' + (r.special.from || '') + '|' + (r.special.teacher || '');
    var g = groups[key] = groups[key] || { subject: r.special.subject, from: r.special.from || '', teacher: r.special.teacher || '', kids: [] };
    g.kids.push({ name: r.name, grade: norm(r.grade), lane: lane(r) });
  });
  var specials = Object.keys(groups).map(function (k) { groups[k].kids.sort(byName); return groups[k]; })
    .sort(function (a, b) { return a.subject < b.subject ? -1 : a.subject > b.subject ? 1 : 0; });

  var changes = pop.filter(function (r) { return r.expected && (r.overridden || r.fromRouteCode); }).map(function (r) {
    var fromList = (r.fromRoutes && r.fromRoutes.length) ? r.fromRoutes
      : ((r.fromRouteCode || r.fromRouteName) ? [{ code: r.fromRouteCode, name: r.fromRouteName }] : []);
    var from = fromList.length
      ? 'Bus — ' + fromList.map(function (fr) {
          return (dsRouteFor(routes, fr.code, fr.name) || {}).name || fr.name || fr.code;
        }).join(' / ')
      : (r.type === 'Bus' ? 'not the bus' : 'usual');
    var to = r.type === 'Bus' ? 'Bus — ' + lane(r) : r.type + (r.overrideDestination ? ' → ' + r.overrideDestination : '');
    return { name: r.name, grade: norm(r.grade), from: from, to: to, note: r.overrideNote || '', by: r.overrideBy || '' };
  }).sort(byName);

  var auth = pop.filter(function (r) { return r.expected && dsAuthPickupsFor(r.pickupAuth).length; }).map(function (r) {
    return { name: r.name, grade: norm(r.grade), lane: lane(r), people: dsAuthPickupsFor(r.pickupAuth) };
  }).sort(byName);

  var check = pop.filter(function (r) {
    return r.expected && (r.reason === 'GAME DAY' || r.reason === 'PICKUP PLANNED');
  }).map(function (r) {
    return { name: r.name, grade: norm(r.grade), lane: lane(r),
             note: (r.reason === 'PICKUP PLANNED' ? 'PICKUP PLANNED — ' : '') + (r.detail || '') };
  }).sort(byName);

  return { notExpected: notExpected, specials: specials, changes: changes, auth: auth, check: check,
           counts: { population: pop.length, notExpected: notExpected.length,
                     specials: specials.reduce(function (n, g) { return n + g.kids.length; }, 0),
                     changes: changes.length, auth: auth.length, check: check.length } };
}

var DS_PICKUP_AUTH_METHODS = ['Email', 'Phone call', 'In person', 'Written note'];

function dsIsoDate(v) {
  var s = dsCellToString(v).trim();
  var iso = /^(\d{4})-(\d{2})-(\d{2})/.exec(s);
  if (iso) return iso[1] + '-' + iso[2] + '-' + iso[3];
  var us = /^(\d{1,2})\/(\d{1,2})\/(\d{4})/.exec(s);
  if (us) return us[3] + '-' + (us[1].length < 2 ? '0' : '') + us[1] + '-' + (us[2].length < 2 ? '0' : '') + us[2];
  return '';
}

function dsBuildPickupAuth(values, dayKey, opts) {
  opts = opts || {};
  var out = {};
  if (!values || values.length < 2) return out;
  var h = dsHeaderMap(values[0]);
  var get = dsGetter(h);
  var byAuth = {}, order = [];
  for (var r = 1; r < values.length; r++) {
    var row = values[r];
    var aid = get(row, 'Auth ID'), sid = get(row, 'Student ID');
    if (!aid || !sid) continue;
    var status = get(row, 'Status').toLowerCase();
    if (status && status !== 'active') continue;                 // Superseded / Deleted rows are history
    var start = dsIsoDate(get(row, 'Start')) || dayKey;
    var end = dsIsoDate(get(row, 'End')) || start;
    if (end < dayKey && !opts.includeExpired) continue;
    var a = byAuth[aid];
    if (!a) {
      a = byAuth[aid] = {
        id: aid, studentId: sid, studentName: get(row, 'Student Name'), people: [],
        start: start, end: end, method: get(row, 'Method'), note: get(row, 'Note'),
        requestedBy: get(row, 'Requested By'), requestedEmail: get(row, 'Requested Email'),
        by: get(row, 'Created By'), at: get(row, 'Created At'),
        updatedBy: get(row, 'Updated By'), updatedAt: get(row, 'Updated At'),
        active: start <= dayKey && dayKey <= end, upcoming: start > dayKey
      };
      order.push(a);
    }
    if (get(row, 'Person')) a.people.push({ name: get(row, 'Person'), rel: get(row, 'Relationship') });
  }
  order.forEach(function (a) { (out[a.studentId] = out[a.studentId] || []).push(a); });
  Object.keys(out).forEach(function (sid) {
    out[sid].sort(function (x, y) { return x.start < y.start ? -1 : x.start > y.start ? 1 : 0; });
  });
  return out;
}

function dsAuthPickupsFor(list) {
  var out = [];
  (list || []).forEach(function (a) {
    if (!a || !a.active) return;
    (a.people || []).forEach(function (p) { out.push([p.name, p.rel || '', a.end]); });
  });
  return out;
}

function dsPickupAuthValidate(p, dayKey) {
  p = p || {};
  var people = [];
  (p.people || []).forEach(function (x) {
    var name = String((x && x.name) || '').trim(), rel = String((x && x.rel) || '').trim();
    if (name) people.push({ name: name.slice(0, 80), rel: rel.slice(0, 40) });
  });
  if (!people.length) return { error: 'At least one name is required.' };
  var start = dsIsoDate(p.start) || dayKey, end = dsIsoDate(p.end) || start;
  if (!/^\d{4}-\d{2}-\d{2}$/.test(start) || !/^\d{4}-\d{2}-\d{2}$/.test(end)) return { error: 'Dates must be yyyy-mm-dd.' };
  if (end < start) return { error: 'The end date is before the start date.' };
  if (end < dayKey) return { error: 'That authorization would already be over — check the end date.' };
  var method = String(p.method || '').trim();
  if (DS_PICKUP_AUTH_METHODS.indexOf(method) === -1) {
    return { error: 'Say how the parent told you: ' + DS_PICKUP_AUTH_METHODS.join(', ') + '.' };
  }
  return { ok: true, people: people, start: start, end: end, method: method,
           note: String(p.note || '').trim().slice(0, 300) };
}

function dsAuthRequesters(pickups, guardianEmails) {
  var out = [], seen = {};
  var ok = function (e) { return /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(e); };
  (pickups || []).forEach(function (p) {
    var e = String((p && p.email) || '').trim().toLowerCase();
    if (!ok(e) || seen[e]) return;
    seen[e] = 1;
    var name = String((p && p.name) || '').trim();
    var rel = String((p && p.rel) || '').trim();
    out.push({ name: name, rel: rel, email: e,
               label: (name || e) + (rel ? ' (' + rel + ')' : '') + ' — ' + e });
  });
  (guardianEmails || []).forEach(function (raw) {
    var e = String(raw || '').trim().toLowerCase();
    if (!ok(e) || seen[e]) return;
    seen[e] = 1;
    out.push({ name: '', rel: '', email: e, label: e + ' — guardian address on file' });
  });
  return out;
}

function dsPickupAuthEmail(kind, auth, studentName, actor) {
  var who = (auth.people || []).map(function (p) { return p.name + (p.rel ? ' (' + p.rel + ')' : ''); }).join(', ');
  var when = auth.start === auth.end ? 'on ' + auth.start : 'from ' + auth.start + ' through ' + auth.end;
  var asked = String(auth.requestedBy || '').trim();
  var titles = { created: 'Pickup authorization added', updated: 'Pickup authorization updated',
                 deleted: 'Pickup authorization removed' };
  var subject = (titles[kind] || titles.created) + ' — ' + studentName;
  var body;
  if (kind === 'deleted') {
    body = 'The temporary pickup authorization for ' + studentName + ' has been REMOVED.\n\n' +
           'It had allowed: ' + who + '\nValid ' + when + '.';
  } else {
    body = 'A temporary pickup authorization for ' + studentName + ' has been ' +
           (kind === 'updated' ? 'updated' : 'added') + '.\n\n' +
           'Authorized to pick up: ' + who + '\nValid ' + when + '.\n' +
           'Received by: ' + (auth.method || '') + (auth.note ? '\nNote: ' + auth.note : '');
  }
  body += '\n\nRecorded by ' + actor + ' at the Harford Christian School elementary office. If this is ' +
          'not what you asked for, reply to this email or call the office.\n\n' +
          'This is an automated confirmation from the HCS Dismissal app.';
  if (asked) {
    body += '\n\nThis was recorded from ' + asked + '. If that is not right, or if anything above ' +
      'is wrong, reply to this email and the office will correct it.';
  }
  return { subject: subject, body: body };
}

function dsDriverLists(board, routes, dayName, only) {
  routes = routes || {};
  var lists = {}, aliases = {}, routesOf = {}, rows = [];
  ((board && board.groups) || []).forEach(function (g) {
    (g.rows || []).forEach(function (r) { rows.push(r); });
  });
  var onBus = function (r) { return r.type === 'Bus' && !!(r.routeCode || r.routeName); };
  var labelOf = function (r) { return r.routeName || r.routeCode; };

  function listFor(code, label) {
    var rt = dsRouteFor(routes, code, label);
    var key = (rt && rt.code) || code || label;
    if (!lists[key]) {
      lists[key] = {
        code: (rt && rt.code) || code || '',
        name: (rt && rt.name) || label || code || 'Bus',
        colour: (rt && rt.colour) || '', vehicle: (rt && rt.vehicle) || '',
        drivers: dsDriversFor(rt, (board && board.session) || 'PM', dayName).map(function (d) {
          return { name: d.name, phone: d.phone || '' };
        }),
        riding: [], notRiding: []
      };
      aliases[key] = {};
    }
    if (code) aliases[key][String(code).trim().toLowerCase()] = true;
    if (label) aliases[key][String(label).trim().toLowerCase()] = true;
    return lists[key];
  }

  rows.forEach(function (r) {
    if (onBus(r)) (routesOf[r.id] = routesOf[r.id] || []).push(labelOf(r));
  });
  rows.forEach(function (r) {
    if (onBus(r)) {
      var L = listFor(r.routeCode, r.routeName);
      if (r.expected) {
        var flags = [];
        (routesOf[r.id] || []).forEach(function (n) { if (n !== labelOf(r)) flags.push('also on ' + n); });
        if (r.overridden) flags.push('added today' + (r.overrideNote ? ' — ' + r.overrideNote : ''));
        if (r.reason === 'GAME DAY') flags.push('GAME DAY — ' + (r.detail || 'posted early dismissal'));
        else if (r.reason === 'PICKUP PLANNED') flags.push('PICKUP PLANNED — ' + (r.detail || 'the office took a call'));
        else if (r.standing) flags.push('standing' + (r.standingNote ? ' — ' + r.standingNote : ''));
        L.riding.push({ id: r.id, name: r.name, grade: r.grade, building: r.building || '', flags: flags });
      } else {
        L.notRiding.push({ id: r.id, name: r.name, grade: r.grade, reason: r.reason || 'NOT EXPECTED',
                           detail: r.detail || '' });
      }
    }
    var froms = (r.fromRoutes && r.fromRoutes.length) ? r.fromRoutes
      : ((r.fromRouteCode || r.fromRouteName) ? [{ code: r.fromRouteCode, name: r.fromRouteName }] : []);
    froms.forEach(function (fr) {
      var F = listFor(fr.code, fr.name);
      if (!r.expected) {
        F.notRiding.push({ id: r.id, name: r.name, grade: r.grade, reason: r.reason || 'NOT EXPECTED',
                           detail: r.detail || '' });
      } else {
        var to = r.type === 'Bus' ? dsRouteFor(routes, r.routeCode, r.routeName) : null;
        var where = r.type === 'Bus'
          ? 'ON ' + String((to && to.name) || r.routeName || r.routeCode || 'ANOTHER BUS').toUpperCase()
          : String(r.type || 'CHANGED').toUpperCase();
        var note = r.standing ? r.standingNote : r.overrideNote;
        F.notRiding.push({
          id: r.id, name: r.name, grade: r.grade,
          reason: where + (r.standing ? ' (STANDING)' : ' TODAY'),
          detail: [r.overrideDestination || '', note || ''].filter(String).join(' — ')
        });
      }
    });
  });

  var byName = dsByName;   // was a twelfth copy of the same three-way compare
  var keys = Object.keys(lists);
  if (only) {
    var o = String(only).trim().toLowerCase();
    keys = keys.filter(function (k) {
      var L = lists[k];
      return L.code.toLowerCase() === o || L.name.toLowerCase() === o || aliases[k][o] === true;
    });
  }
  var out = keys.map(function (k) { return lists[k]; });
  out.forEach(function (L) { L.riding.sort(byName); L.notRiding.sort(byName); });
  out.sort(byName);
  return out;
}

function dsChangeSheet(board, routes, dayName) {
  var lists = dsDriverLists(board, routes, dayName, '');
  var buses = [], clean = 0, nOff = 0, nOn = 0, nCheck = 0;

  lists.forEach(function (L) {
    var off = L.notRiding.map(function (r) {
      return { name: r.name, grade: r.grade, reason: r.reason || 'NOT EXPECTED', detail: r.detail || '' };
    });

    var on = [];
    L.riding.forEach(function (r) {
      var note = (r.flags || []).filter(function (f) {
        return /^added today/.test(f) || /^also on /.test(f);
      }).join('; ');
      if (note) on.push({ name: r.name, grade: r.grade, note: note });
    });

    var check = [];
    L.riding.forEach(function (r) {
      var g = (r.flags || []).filter(function (f) { return /^GAME DAY/.test(f); })[0];
      if (g) { check.push({ name: r.name, grade: r.grade, note: g.replace(/^GAME DAY — /, '') }); return; }
      var p = (r.flags || []).filter(function (f) { return /^PICKUP PLANNED/.test(f); })[0];
      if (p) check.push({ name: r.name, grade: r.grade, note: p });
    });

    if (!off.length && !on.length && !check.length) { clean++; return; }
    nOff += off.length;
    nOn += on.length;
    nCheck += check.length;
    buses.push({
      code: L.code, name: L.name, colour: L.colour, vehicle: L.vehicle,
      drivers: L.drivers, riding: L.riding.length, off: off, on: on, check: check
    });
  });

  return { buses: buses, counts: { buses: buses.length, clean: clean, off: nOff, on: nOn, check: nCheck } };
}

function dsRampSlice(board, routes, opts, pickups) {
  opts = opts || {};
  routes = routes || {};
  pickups = pickups || {};
  var norm = dsGradeKey;
  return dsFlatList(board).filter(function (r) {
    return dsRampPopulation(r, { grades: opts.grades, types: opts.types, sixthAtEl: true });
  }).map(function (r) {
    var lanes;
    if (r.routes && r.routes.length) {
      lanes = r.routes.map(function (label, i) {
        var rt = dsRouteFor(routes, (r.routeCodes || [])[i] || '', label);
        var lane = { label: (rt && rt.name) || label,
                     colour: (rt && rt.colour) || '',
                     vehicle: (rt && rt.vehicle) || r.vehicle || '' };
        if (rt && rt.substituted) lane.sub = rt.subNote || 'different vehicle today';
        return lane;
      });
    } else {
      lanes = [{ label: r.type, colour: '', vehicle: '' }];    // Car, and any non-bus residual
    }
    return {
      name: r.name, grade: norm(r.grade), type: r.type, lanes: lanes,
      expected: r.expected, reason: r.reason || '', detail: r.detail || '',
      split: !!r.split, today: !!r.overridden, handedTo: r.overrideDestination || '',
      walkUp: !!r.walkUp, pickups: pickups[r.id] || [],
      special: r.special ? { subject: r.special.subject, from: r.special.from || '' } : null,
      authPickups: dsAuthPickupsFor(r.pickupAuth)
    };
  });
}

function dsDriverScrub_(lists) {
  (lists || []).forEach(function (L) {
    (L.notRiding || []).forEach(function (r) { r.detail = ''; });
    (L.riding || []).forEach(function (r) {
      r.flags = (r.flags || []).map(function (f) {
        var s = String(f);
        if (s.indexOf('also on ') === 0) return s;
        var cut = s.indexOf(' — ');
        return cut === -1 ? s : s.slice(0, cut);
      });
    });
  });
  return lists;
}

function dsDriverSlice(board, routes, dayName, pickups) {
  var lists = dsDriverScrub_(dsDriverLists(board, routes, dayName, null));
  pickups = pickups || {};
  lists.forEach(function (L) {
    (L.riding || []).concat(L.notRiding || []).forEach(function (r) {
      r.contacts = pickups[r.id] || [];
    });
  });
  return {
    session: (board && board.session) || 'PM',
    dayName: dayName || '',
    routes: lists
  };
}

(function (global) {
  var DriveApp, PropertiesService, HtmlService, ScriptApp, Session, Utilities, Logger;

/* ===== transportation-kiosk/Config.gs ===== */
/**
 * Config.gs — constants, the ramp-board file reader, and the device-token gate.
 *
 * READ-ONLY. This project writes nothing anywhere except its own Script Properties (the enrolled
 * device tokens and the resolved file id). It reads ONE file: Dismissal_RAMP_BOARD.json, which the
 * ../transportation app publishes into the shared folder. It never touches FACTS, the roster, the
 * overrides, or any sheet.
 */

/** The shared Drive folder facts-api-sync and the dismissal app write into — SAME id as the main
 *  app's Config.gs. The ramp-board file lives here; this kiosk resolves it by name. */
var SHARED_FOLDER_ID = 'DEMO_DRIVE_ID';
var RAMP_BOARD_FILE = 'Dismissal_RAMP_BOARD.json';
var PROP_RAMP_FILE_ID = 'RAMP_BOARD_FILE_ID';

/** Enrolled devices: a JSON map {token: {device, added}}. A device opens the app with ?k=<token>;
 *  doGet AND rampApi both re-check it, because the URL param is presentation, not the gate. */
var PROP_KIOSK_TOKENS = 'KIOSK_TOKENS';
/** Kill switch. Set to 'N' (RUN_setKioskEnabled(false)) and every device shows "Temporarily
 *  unavailable" within its next poll — the panic button if a URL ever leaks. */
var PROP_KIOSK_ENABLED = 'KIOSK_ENABLED';

var TZ = 'America/New_York';

/* ------------------------------- the ramp board file ------------------------------- */

/**
 * Resolve Dismissal_RAMP_BOARD.json by NAME in the shared folder, caching its id. Same self-healing
 * pattern the main app uses for the staging sheet: Script Properties are per-project, so this kiosk
 * cannot read the id the dismissal app stored — it looks the file up itself and remembers it.
 */
function getRampFileId_() {
  var props = PropertiesService.getScriptProperties();
  var cached = props.getProperty(PROP_RAMP_FILE_ID);
  if (cached) { try { DriveApp.getFileById(cached); return cached; } catch (e) { /* re-resolve */ } }
  var it = DriveApp.getFolderById(SHARED_FOLDER_ID).getFilesByName(RAMP_BOARD_FILE);
  if (!it.hasNext()) {
    throw new Error('Ramp board file "' + RAMP_BOARD_FILE + '" is not in the shared folder yet. In ' +
      '../transportation run RUN_publishBoardNow (Code.gs), and make sure THIS project deploys as an ' +
      'account that can read that folder.');
  }
  var id = it.next().getId();
  props.setProperty(PROP_RAMP_FILE_ID, id);
  return id;
}

/** Read and parse the ramp board. Throws if the file is missing or unreadable — the caller decides
 *  what the page does about it (keep the last good board, show a banner). */
function readRampBoard_() {
  var txt = DriveApp.getFileById(getRampFileId_()).getBlob().getDataAsString();
  return JSON.parse(txt);
}

/* ------------------------------- the device token gate ------------------------------- */

function isKioskEnabled_() {
  return PropertiesService.getScriptProperties().getProperty(PROP_KIOSK_ENABLED) !== 'N';
}

/**
 * ScriptApp.getService().getUrl() returns the PUBLISHED /exec URL inside a served request, but the
 * editor-only /dev URL when called from the Run menu — so a token enrolled from the editor logged a
 * link the anonymous iPad cannot open (found 2026-09-10). doGet calls this on every serve to record
 * the real /exec address, and the editor functions read it back.
 */
var PROP_WEBAPP_EXEC_URL = 'WEBAPP_EXEC_URL';
function rememberExecUrl_() {
  try {
    var u = ScriptApp.getService().getUrl();
    var p = PropertiesService.getScriptProperties();
    if (u && u.indexOf('/exec') !== -1 && p.getProperty(PROP_WEBAPP_EXEC_URL) !== u) {
      p.setProperty(PROP_WEBAPP_EXEC_URL, u);
    }
  } catch (e) { /* never let this break a page load */ }
}
/** The published /exec URL if we have recorded one, else getUrl() (the /dev URL from the editor). */
function getWebAppUrl_() {
  return PropertiesService.getScriptProperties().getProperty(PROP_WEBAPP_EXEC_URL) ||
    ScriptApp.getService().getUrl();
}

/**
 * The FULL transportation app (../transportation), for the "Full app" button. Defaults to its known
 * /exec URL and can be overridden with Script Property FULL_APP_URL. That app is DOMAIN-gated, so
 * the button prompts a Google login on the anonymous iPad (correct — the full app can change a
 * child's dismissal) and opens straight through on a signed-in staff phone.
 */
var PROP_FULL_APP_URL = 'FULL_APP_URL';
var FULL_APP_URL_DEFAULT =
  'https://example.invalid/demo-deployment';
function getFullAppUrl_() {
  return PropertiesService.getScriptProperties().getProperty(PROP_FULL_APP_URL) || FULL_APP_URL_DEFAULT;
}

function kioskTokens_() {
  try { return JSON.parse(PropertiesService.getScriptProperties().getProperty(PROP_KIOSK_TOKENS) || '{}'); }
  catch (e) { return {}; }
}

/** Is this token one we enrolled? The whole access model — there is no Google sign-in on the iPad. */
function isValidToken_(tok) {
  tok = String(tok || '').trim();
  if (!tok) return false;
  return Object.prototype.hasOwnProperty.call(kioskTokens_(), tok);
}

/**
 * Throw unless this runs from the SCRIPT EDITOR (or as the deploying account itself). The RUN_
 * functions below MINT and REVOKE access tokens; google.script.run reaches every global, so they
 * must never be callable from a web visitor. In an ANYONE_ANONYMOUS web app the active user is ''
 * (nobody) and the effective user is the deployer, so they differ — that gap is the gate. In the
 * editor they are the same person. Copied in spirit from ../transportation/Config.gs requireEditor_.
 */
function requireEditor_() {
  var active = (Session.getActiveUser().getEmail() || '').toLowerCase();
  var effective = (Session.getEffectiveUser().getEmail() || '').toLowerCase();
  if (!active || active !== effective) {
    throw new Error('This function can only be run from the script editor.');
  }
  return active;
}

/* ------------------------------- device management (editor Run menu) ------------------------------- */

/**
 * ENROL a device. THE EDITOR RUN MENU PASSES NO ARGUMENTS, so there are two no-arg ways in:
 *   - RUN_addRampIpad()  — the common case, enrols "Ramp iPad".
 *   - set Script Property KIOSK_NEW_DEVICE to the name, then run RUN_addKioskToken.
 * Either way it logs the full URL to open on that iPad (Safari -> Share -> Add to Home Screen).
 */
function RUN_addKioskToken(deviceName) {
  requireEditor_();
  deviceName = String(deviceName || '').trim() ||
    String(PropertiesService.getScriptProperties().getProperty('KIOSK_NEW_DEVICE') || '').trim();
  if (!deviceName) {
    throw new Error('No device name. Run RUN_addRampIpad(), or set Script Property KIOSK_NEW_DEVICE ' +
      'to the device name and run RUN_addKioskToken again (the Run menu cannot pass an argument).');
  }
  return addKioskToken_(deviceName);
}

/** Enrol the ramp iPad — a no-argument wrapper for the editor Run menu. */
function RUN_addRampIpad() { requireEditor_(); return addKioskToken_('Ramp iPad'); }

/** Enrol ONE shared token for the staff iPhones (the ramp lead + the office manager, via a Safari shortcut). Its own
 *  token, so it can be revoked without touching the dedicated iPad. */
function RUN_addRampPhones() { requireEditor_(); return addKioskToken_('Ramp Personal iPhones'); }

/** Mint + store a token for a device and log its URL. Callers MUST have gated with requireEditor_. */
function addKioskToken_(deviceName) {
  var tok = Utilities.getUuid().replace(/-/g, '').slice(0, 20);
  var toks = kioskTokens_();
  toks[tok] = { device: deviceName, added: Utilities.formatDate(new Date(), TZ, 'yyyy-MM-dd HH:mm') };
  PropertiesService.getScriptProperties().setProperty(PROP_KIOSK_TOKENS, JSON.stringify(toks));
  var url = getWebAppUrl_();
  var isDev = url.indexOf('/exec') === -1;
  Logger.log('ENROLLED "%s".', deviceName);
  if (isDev) {
    Logger.log('!! The published /exec URL is not recorded yet. OPEN THE WEB APP ONCE from any device');
    Logger.log('   so it records its address, then run RUN_listKioskTokens for the working link. The');
    Logger.log('   URL below is the editor-only /dev URL and will NOT work on the iPad:');
  } else {
    Logger.log('Open THIS on that iPad (Safari, then Share -> Add to Home Screen):');
  }
  Logger.log('  %s?k=%s', url, tok);
  Logger.log('Keep it private — anyone with this link sees the ramp board. RUN_revokeKioskToken to undo.');
  return { device: deviceName, token: tok, url: url + '?k=' + tok };
}

/** LIST enrolled devices. In Config.gs, editor Run menu. */
function RUN_listKioskTokens() {
  requireEditor_();
  var t = kioskTokens_(), keys = Object.keys(t), url = getWebAppUrl_();
  if (!keys.length) { Logger.log('No devices enrolled yet. Run RUN_addRampIpad().'); return t; }
  if (url.indexOf('/exec') === -1) {
    Logger.log('!! Open the web app ONCE from any device first, so it records its /exec address —');
    Logger.log('   the links below are the editor-only /dev URL and will NOT work on the iPad.');
  }
  keys.forEach(function (k) {
    Logger.log('%s   (added %s)', t[k].device, t[k].added);
    Logger.log('   %s?k=%s', url, k);
  });
  Logger.log('kiosk is %s', isKioskEnabled_() ? 'ENABLED' : 'DISABLED');
  return t;
}

/** REVOKE a device token. In Config.gs, editor Run menu. That device then sees "Not enrolled". */
function RUN_revokeKioskToken(tok) {
  requireEditor_();
  tok = String(tok || '').trim();
  var t = kioskTokens_();
  if (!t[tok]) { Logger.log('No such token. Run RUN_listKioskTokens to see them.'); return; }
  var d = t[tok].device;
  delete t[tok];
  PropertiesService.getScriptProperties().setProperty(PROP_KIOSK_TOKENS, JSON.stringify(t));
  Logger.log('REVOKED "%s". That device now sees Not enrolled on its next load.', d);
}

/** Turn the whole kiosk on or off. In Config.gs, editor Run menu. RUN_setKioskEnabled(false) is
 *  the panic button; every device shows "Temporarily unavailable" within a minute. */
function RUN_setKioskEnabled(on) {
  requireEditor_();
  PropertiesService.getScriptProperties().setProperty(PROP_KIOSK_ENABLED, on ? 'Y' : 'N');
  Logger.log('Kiosk %s.', on ? 'ENABLED' : 'DISABLED — all devices see Temporarily unavailable');
}

/** Prove this project can READ the ramp board file and see who is enrolled. Read-only. Editor. */
function RUN_verifyKiosk() {
  requireEditor_();
  var b = readRampBoard_();
  Logger.log('Ramp board readable: built %s for %s; %s children (%s flagged); attendance as of %s',
    b.builtAt, b.dayName + ' ' + b.dayKey, String((b.students || []).length),
    String((b.students || []).filter(function (s) { return !s.expected; }).length),
    b.attendanceAsOf || '?');
  Logger.log('%s device(s) enrolled; kiosk %s',
    String(Object.keys(kioskTokens_()).length), isKioskEnabled_() ? 'ENABLED' : 'DISABLED');
  return { builtAt: b.builtAt, students: (b.students || []).length,
           devices: Object.keys(kioskTokens_()).length, enabled: isKioskEnabled_() };
}

/* ===== transportation-kiosk/Code.gs ===== */
/**
 * Code.gs — the web-app entry point and the single API call.
 *
 * This app has ONE job: show the ramp its precomputed board on a device with no Google sign-in, and
 * never go blank. So doGet inlines the board into the page (first paint needs no round trip), and
 * rampApi is the 60-second poll that keeps it current. Both re-check the device token — the URL
 * param is presentation, not the gate (google.script.run reaches every global whatever the page
 * shows, proven live in ../transportation).
 */

/** Include a generated partial (KioskClient) into the template. */
function include(name) {
  return HtmlService.createHtmlOutputFromFile(name).getContent();
}

function doGet(e) {
  var tok = String((e && e.parameter && e.parameter.k) || '');
  if (!isKioskEnabled_()) {
    return kioskMessage_('Temporarily unavailable',
      'The ramp board has been turned off. Ask Josh to switch it back on.');
  }
  if (!isValidToken_(tok)) {
    return kioskMessage_('Not enrolled',
      'This device is not set up for the ramp board. Ask Josh to add it (RUN_addKioskToken).');
  }
  // Inline the board so the very first paint needs zero google.script.run calls — the exact failure
  // that blanked the phones on 2026-09-08. If the file cannot be read right now, the page still
  // loads and its poll retries; it shows the reason rather than a blank screen.
  // Record our OWN published /exec address (this call returns it in a served request, but the
  // editor-only /dev URL from the Run menu) so RUN_addRampIpad can print a link the iPad can use.
  rememberExecUrl_();
  var board = null, err = '';
  try { board = readRampBoard_(); } catch (ex) { err = String(ex && ex.message ? ex.message : ex); }
  var t = HtmlService.createTemplateFromFile('Kiosk');
  t.token = tok;
  t.dataJson = board ? JSON.stringify(board) : 'null';
  t.errJson = JSON.stringify(err);
  t.nowMs = String(Date.now());
  t.fullAppUrl = getFullAppUrl_();
  // addMetaTag accepts only a short whitelist; viewport is on it, the apple-mobile-web-app-* tags
  // are NOT — adding them threw "meta tag not allowed" and broke the board (2026-09-10). Add to
  // Home Screen still works without them; MDM Single App Mode is the real full-screen mechanism.
  return t.evaluate()
    .setTitle('HCS Ramp')
    .addMetaTag('viewport', 'width=device-width, initial-scale=1, maximum-scale=1');
}

/** A plain full-page message for the two gated states, styled like the board. */
function kioskMessage_(title, body) {
  return HtmlService.createHtmlOutput(
    '<div style="font:18px/1.6 -apple-system,Segoe UI,Roboto,sans-serif;background:#8E1420;' +
    'color:#fff;min-height:100vh;margin:0;display:flex;align-items:center;justify-content:center;' +
    'text-align:center"><div style="max-width:28rem;padding:2rem">' +
    '<h1 style="font-size:1.5rem;margin:0 0 .5rem">' + title + '</h1>' +
    '<p style="color:#e9c2c7;margin:0">' + body + '</p></div></div>')
    .setTitle('HCS Ramp')
    .addMetaTag('viewport', 'width=device-width, initial-scale=1');
}

/**
 * The 60-second poll. Re-checks the token server-side, then returns the current ramp board. Throws
 * on a bad token or a disabled kiosk (the page keeps its last board and shows a banner), and lets a
 * read error propagate for the same reason.
 */
function rampApi(token) {
  if (!isKioskEnabled_()) throw new Error('The ramp board has been turned off.');
  if (!isValidToken_(String(token || ''))) throw new Error('This device is no longer enrolled.');
  var board = readRampBoard_();
  board.serverMs = Date.now();     // the device's clock may be wrong; trust the server's for age
  return board;
}

  global.KIOSK_LOGIC = {
    bind: function (env) { DriveApp = env.DriveApp; PropertiesService = env.PropertiesService; HtmlService = env.HtmlService; ScriptApp = env.ScriptApp; Session = env.Session; Utilities = env.Utilities; Logger = env.Logger; },
    doGet: doGet,
    rampApi: rampApi,
    readRampBoard_: readRampBoard_,
    getRampFileId_: getRampFileId_,
    isKioskEnabled_: isKioskEnabled_,
    isValidToken_: isValidToken_,
    kioskTokens_: kioskTokens_,
    getFullAppUrl_: getFullAppUrl_,
    RAMP_BOARD_FILE: RAMP_BOARD_FILE,
    PROP_RAMP_FILE_ID: PROP_RAMP_FILE_ID,
    PROP_KIOSK_TOKENS: PROP_KIOSK_TOKENS,
    PROP_KIOSK_ENABLED: PROP_KIOSK_ENABLED,
    PROP_FULL_APP_URL: PROP_FULL_APP_URL
  };
})(typeof window !== "undefined" ? window : globalThis);
