/* GENERATED by demos/macs/build-logic.mjs — do not edit.
   This is the MACS Creative Writing project's OWN server code, verbatim (Config.js, Code.js, YearRollover.js) with
   its published Drive links, archive folder id and real school roster scrubbed. The demo runs it in the browser
   over in-memory Google services (mock-competitions.js), so the per-group caps, the validation messages, the
   entry ids and the one-submission-per-school rule are the app's real behaviour. */
(function (global) {
  var SpreadsheetApp, DriveApp, Utilities, Session, Logger, HtmlService;
/* ===== Config.js ===== */
/**
 * Sheet tab names and default seed data. All read/write logic reads live
 * values from these sheets at runtime — nothing here is authoritative
 * once the sheet exists; this is only used to seed a fresh spreadsheet.
 */

var SHEETS = {
  REGISTRATIONS: 'Registrations',
  ENTRIES: 'Entries',
  SCHOOLS: 'Schools',
  SETTINGS: 'Settings',
  JUDGING_SHEETS: 'Judging Sheets',
  ADMIN_EDITS_LOG: 'Admin Edit Log'
};

var REGISTRATIONS_HEADERS = [
  'Timestamp', 'School Code', 'School Name', 'Contact First Name', 'Contact Last Name',
  'Phone', 'Email', 'Levels Selected', 'Rules Accepted'
];

var ENTRIES_HEADERS = [
  'Entry ID', 'Timestamp', 'School Code', 'School Name', 'Level', 'Category',
  'Student First Name', 'Student Last Name', 'Title', 'Entry PDF URL', 'Judging Sheet PDF URL'
];

var SCHOOLS_HEADERS = ['School Code', 'School Name'];

var DEFAULT_SCHOOLS = [
  // (demo) the real member-school roster is not shipped; Schools is seeded from data.js
];

// One judging-sheet-template PDF link per Level+Category, shared across
// every school entering that level/category — editable afterward on the
// Judging Sheets tab. Seeded from the links published on the JotForm.
var JUDGING_SHEETS_HEADERS = ['Level', 'Category', 'Url'];
var DEFAULT_JUDGING_SHEETS = [
  ['L1A', 'Poetry', 'https://example.invalid/drive/DEMO_DRIVE_ID'],
  ['L1A', 'Short Story', 'https://example.invalid/drive/DEMO_DRIVE_ID'],
  ['L1B', 'Poetry', 'https://example.invalid/drive/DEMO_DRIVE_ID'],
  ['L1B', 'Short Story', 'https://example.invalid/drive/DEMO_DRIVE_ID'],
  ['L2', 'Poetry', 'https://example.invalid/drive/DEMO_DRIVE_ID'],
  ['L2', 'Short Story', 'https://example.invalid/drive/DEMO_DRIVE_ID'],
  ['L3', 'Poetry', 'https://example.invalid/drive/DEMO_DRIVE_ID'],
  ['L3', 'Essay', 'https://example.invalid/drive/DEMO_DRIVE_ID']
];

// Default general settings — key/value pairs, seeded once, editable after.
var DEFAULT_SETTINGS = [
  ['Competition Year', ''],
  ['Admin Emails', ''],
  ['Payment PDF Link (MACS Schools)', 'https://example.invalid/drive/DEMO_DRIVE_ID'],
  ['Payment PDF Link (Non-MACS Schools)', 'https://example.invalid/drive/DEMO_DRIVE_ID'],
  ['Judge Names Deadline', '5:00 PM on October 31, 2025'],
  ['Topics Emailed By', 'November 5, 2025'],
  ['Entry & Judging Sheet Deadline', '5:00 PM on December 5, 2025'],
  ['Judges Receive Entries By', 'December 9, 2025'],
  ['Judging Complete By', 'Tuesday, January 15, 2026']
];

// Statement of Originality text — Level 1a/1b/II all share the shorter
// form; Level III uses the longer AI-disclosure form.
var SOA_STANDARD = 'I certify that this project is my own original and authentic work and that I received no help in completing this project other than general instruction and supervision.';
var SOA_LEVEL_III = 'I certify that this submission is entirely my original work and that I received no help in completing this project other than general instruction and supervision. Except for pre-writing research, I did not use any AI tools or software to create my writing submission. I did not enter the writing prompt in AI software to assist me. When writing, I followed conscientiously the instructions regarding Prohibition of AI Writing Tools in the general rules.';

var GENERAL_RULES = [
  'Each school may only enter one entry per creative writing category. No substitutions can be made. If a school does not enter a particular creative writing level, they may not enter additional entries in another level.',
  'Each school that participates in the Creative Writing competition must provide at least one Creative Writing judge. Names and email addresses of these judges must be emailed to the competition coordinator no later than 5:00 PM on October 31, 2025.',
  'A student may only enter one creative writing category.',
  'Creative writing topics will be emailed to School Coordinators by November 5, 2025.',
  'A PDF copy of each entry must be sent via the Creative Writing online registration form along with a judging sheet (with the top portion filled out) no later than 5:00 PM on December 5, 2025.',
  'It is imperative that each entry include a signed Statement of Originality.',
  'All results will be given with the Fine Arts competition results.',
  'The completed Creative Writing Fee Form and payment must be mailed no later than December 5, 2025. Checks should be made out to MACS and mailed to the address on the Fee Form.'
];

var LEVEL_1A_RULES = [
  'A student may enter only one creative writing category-either short story or poetry. If a school does not enter in a particular level, it may not enter additional entries in another level.',
  'Student should be told the topics at least one week prior to writing so they have time to think through what they wish to communicate.',
  "Teachers: a. Our goal with this contest is to award excellence. Writing may begin with free writing. But excellent writing on any level requires writing and re-writing. Use this as a teaching opportunity. Tell your students the topic at least one week in advance. Brainstorm with your class. Follow your curriculum's procedure for pre-writing, writing, peer editing, teacher review, and re-writing. b. Review the judging forms for judging criteria. c. Student entries are not required to be spiritual in nature or application. Content should be wholesome and within the boundaries of appropriate Christian thought and behavior (Phil.4:8). Vulgarity, sexual innuendoes, crass humor, dark subject matter, distasteful, and biblically objectionable content are not appropriate. d. Absolutely no plagiarism or AI-generated work is acceptable. e. Within the guidelines above in 3.a., the entry must be the student's own work",
  "Students must submit a typed (or handwritten) entry. The following information must be listed at the top of the first page of the student's entry: Student's name and grade; school name, city, and state; category entered; title; and statement of originality. STATEMENT OF ORIGINALITY: I certify that this project is my own original and authentic work and that I received no help in completing this project other than general instruction and supervision. (Type or sign name after statement.) Failure to include statement of originality will result in disqualification.",
  'Entries do not have to be written at school or under the supervision of a proctor. Make sure that students understand the AI rules and the fact that they must affirm the Statement of Originality.',
  'If entries are typed, the final copy must be printed on one side of the paper. If handwritten, please us pencil or black ink and only write on the front side of the final copy. Handwriting must be legible.',
  "The following information must be listed at the top of the first page of the student's entry: student's name and title of entry.",
  'Previously written poems or short stories will not be acceptable.',
  'Each year the topics will be supplied by the MACS Fine Arts Director. An entire class may write on the topic but only one will be accepted for judging.',
  "Papers will be written at the individual schools, and a PDF copy will be sent to the appointed school for judging. Each entry needs its judging sheet.",
  'Keep the original copy at your school.',
  'The creative writing host will distribute the selections to the judges. The creative writing host will return the selections with the judging sheets to the host school which will tabulate the results. Winners will be announced along with the other elementary results.',
  'Because of the time needed to do accurate judging, all deadlines must be observed.',
  'Each entry will be judged according to the criteria on the creative writing judging forms. The student must provide one judging form with the top portion filled out (name, school, etc.).'
];

var LEVEL_1B_RULES = [
  'Entries shall meet the specific length requirements listed below: ELEMENTARY LEVEL (Grades 4-6) — Poetry: maximum 200 words, Short Story: maximum 750 words. JUNIOR HIGH LEVEL (Grades 7-8) — Poetry: maximum 300 words, Short Story: maximum 1000 words.',
  'A student may enter only one category – either short story or poetry.',
  "Teachers a. Our goal with this contest is to award excellence. Writing may begin with free writing. But excellent writing on any level requires writing and re-writing. Use this as a teaching opportunity. Tell your students the topic at least one week in advance. Brainstorm with your class. Follow your curriculum's procedure for pre-writing, writing, peer editing, teacher review, and re-writing. b. Review the judging forms for judging criteria. c. Student entries are not required to be spiritual in nature or application. Content should be wholesome and within the boundaries of appropriate Christian thought and behavior (Phil.4:8). Vulgarity, sexual innuendoes, crass humor, dark subject matter, distasteful, and biblically objectionable content are not appropriate. d. Absolutely no plagiarism or AI-generated work is acceptable. e. Within the guidelines above in 3.a., the entry must be the student's own work.",
  "Students must submit a typed (or handwritten) entry. The following information must be listed at the top of the first page of the student's entry: Student's name and grade; school name, city, and state; category entered; title; and statement of originality. STATEMENT OF ORIGINALITY: I certify that this project is my own original and authentic work and that I received no help in completing this project other than general instruction and supervision. (Type or sign name after statement.) Failure to include statement of originality will result in disqualification.",
  'Entries do not have to be written at school or under the supervision of a proctor. Make sure that students understand the AI rules and the fact that they must affirm the Statement of Originality.',
  'If entries are typed, the final copy must be printed on one side of the paper. If handwritten, please us pencil or black ink and only write on the front side of the final copy. Handwriting must be legible.',
  "The following information must be listed at the top of the first page of the student's entry: student's name and title of entry.",
  'Previously written poems or short stories will not be acceptable.',
  'Each year the topics will be supplied by the MACS Fine Arts Director. An entire class may write on the topic but only one will be accepted for judging.',
  "Papers will be written at the individual schools, and a PDF copy will be sent to the appointed school for judging. Each entry needs its judging sheet.",
  'Keep the original copy at your school.',
  'The creative writing host will distribute the selections to the judges. The creative writing host will return the selections with the judging sheets to the host school which will tabulate the results. Winners will be announced along with the other elementary results.',
  'Because of the time needed to do accurate judging, all deadlines must be observed.',
  'Each entry will be judged according to the criteria on the creative writing judging forms. The student must provide one judging form with the top portion filled out (name, school, etc.).'
];

var LEVEL_2_RULES = [
  'Entries shall meet the specific length requirements listed below: ELEMENTARY LEVEL (Grades 4-6) — Poetry: maximum 200 words, Short Story: maximum 750 words. JUNIOR HIGH LEVEL (Grades 7-8) — Poetry: maximum 300 words, Short Story: maximum 1000 words.',
  'A student may enter only one category – either short story or poetry.',
  "Teachers a. Our goal with this contest is to award excellence. Writing may begin with free writing. But excellent writing on any level requires writing and re-writing. Use this as a teaching opportunity. Tell your students the topic at least one week in advance. Brainstorm with your class. Follow your curriculum's procedure for pre-writing, writing, peer editing, teacher review, and re-writing. b. Review the judging forms for judging criteria. c. Student entries are not required to be spiritual in nature or application. Content should be wholesome and within the boundaries of appropriate Christian thought and behavior (Phil.4:8). Vulgarity, sexual innuendoes, crass humor, dark subject matter, distasteful, and biblically objectionable content are not appropriate. d. Absolutely no plagiarism or AI-generated work is acceptable. e. Within the guidelines above in 3.a., the entry must be the student's own work.",
  'Preparing the Entry a. Typed entries are preferred, but handwritten entries will be accepted. The student should type or write a clean copy to submit for judging. If the hand-written entry has been scanned for digital submission, ensure that the scanned copy is clear enough for judges to read easily. b. Entries to state and national competition must be free of written comments and corrections. c. The following information must be listed at the top of the first page of the student\'s entry: Student\'s name and grade; school name, city, and state; category entered; title; word count; and statement of originality. STATEMENT OF ORIGINALITY: I certify that this project is my own original and authentic work and that I received no help in completing this project other than general instruction and supervision. (Type or sign name after statement.) Failure to include statement of originality will result in disqualification. d. A "fancy" cover page or title page is not allowed. e. Entries and judging forms must be submitted as digital files. Label files in the following format: i. Entry: ST_School_LastName_FirstInitial_Category Sample: AL_Calvary_Smith_J_ElemPoetry Sample: TN_Grace_Jones_D_JHStory ii. Judging Form: ST_School_LastName_FirstInitial_Category_Judge Sample: AL_Calvary_Smith_J_ElemPoetry_Judge',
  'Review the judging forms for judging criteria. Before submitting the entry, on the judging form fill in the level, name, school, city, state, grade, title, and number of words. The student will be penalized if the judging form is incomplete.',
  'Entries do not have to be written at school. Make sure that students understand the AI rules and the fact that they must affirm the Statement of Originality.',
  'Keep the original at your school. A copy of each entry and judging sheet must be sent via the Creative Writing JotForm Registration no later than 5:00 PM on December 5, 2025. MACS judges will select one winner in each category to go on to the AACS National competition. National winners will be announced in April 2026.',
  'MACS judges will receive the entries by December 9th and will need to do their judging and return them no later than Tuesday, January 15, 2026.'
];

var LEVEL_3_RULES = [
  'At AACS nationals each student may enter a total of two academic categories. However, he may enter only one category from Division 3 and one category from Division 4. (He may not enter both composition categories or both science fair categories.) Example: He may take two academic tests; or he may take one academic test and enter a science fair project; or he may enter one writing category and one science fair project. These rules do not apply at MACS.',
  'Creative writing students must supply the appropriate judging form with the top portion completed (name, school, etc.).',
  'A student may enter only one category – either Poetry or Essay. Each school may only have one SH Poetry entry and one SH Essay entry. If a school does not enter in a paricular level, it may not enter additional entries in another level.',
  'Students should be told the topic at least one week prior to writing so that they have time to think through what they wish to communicate.',
  'After writing a draft and making corrections, the student should type a clean copy to submit for judging. Students may reference a dictionary and a thesaurus.',
  'Entries do not have to be written in school. A student may write without a proctor present, but he must affirm the Statement of Originality (#16b). Please make sure that students understand the AI rules (#15).',
  'The final copy must be typed on one side of the paper, leaving a one-inch margin on all sides.',
  'Previously written poems or essays will not be accepted.',
  'Each year the topics will be supplied by the MACS Fine Arts Director. An entire class may write on the topic, but only one will be accepted for judging.',
  'Writing will be done at the individual schools and a PDF copy will be submitted via the Creative Writing Jotform registration form and then sent to the appointed school for judging. Each entry needs its own judging sheet.',
  'Keep the original copy at your school.',
  'The creative writing host will distribute the selections to the judges. The creative writing host will return the selections with the judging sheets to the host school which will tabulate the results. Winners will be announced along with the other secondary results.',
  'Because of the time needed to do accurate judging, all deadlines must be observed.',
  'Each entry will be judged according to the criteria on the creative writing judging forms. The student must provide one judging form with the top portion filled out (name, school, etc.).',
  'Artificial intelligence tools or software may not be used at any stage of the process except for pre-writing research. In pre-writing research, the writing prompt may not be entered into AI software for any purpose. AI tools or software may not be used to generate ideas in writing to suggest edits or revisions, or for any other purpose. From beginning to end, except for pre-writing research, the submission must be entirely the original work of the student. In categories 18 and 19, the competitor and the school proctor will both be required to sign this statement as part of the statement of originality: "I certify that this submission is entirely my original work and that I received no help in completing this project other than general instruction and supervision. Except for pre-writing research, I did not use any AI tools or software to create my writing submission. I did not enter the writing prompt in AI software to assist me. When writing, I followed conscientiously the instructions regarding \'Prohibition of AI writing tools\' in the general rules."',
  "The entry must follow the prescribed format. a. Page 1 must include the student's name, school, city, state. It must include a signed Statement of Originality. b. Statement of Originality: I certify that this submission is entirely my original work and that I received no help in completing this project other than general instruction and supervision. Except for pre-writing research, I did not use any AI tools or software to create my writing submission. I did not enter the writing prompt in AI software to assist me. When writing, I followed conscientiously the instructions regarding Prohibition of AI Writing Tools in the general rules. c. Page 2 and following will include the student's entry."
];

var LEVEL_3_POETRY_RULES = [
  'The prompt (topic) will be announced at least one week prior to writing.',
  'Previously written poems will not be acceptable.',
  'The student may create and refine his entry within the limits of the allotted contest period, but the work must be strictly his own.',
  'No reference materials, except for a dictionary and thesaurus, will be permissible.',
  'Each entry will be judged according to the criteria on the Creative Writing Poetry Judging Form. The student must provide one judging form for state competition.',
  'Contestants who advance to the AACS national competition will compose their entries prior to the competition. See rules and procedures in the 2025 AACS National Competition Manual.'
];

var LEVEL_3_ESSAY_RULES = [
  'The prompt (topic) will be announced at least one week prior to writing.',
  'Previously written essays will not be acceptable.',
  'The student may create and refine his entry within the limits of the allotted contest period, but the work must be strictly his own.',
  "An essay will be defined as a written expression of the author's opinion: a. Stated in a thesis in the first paragraph. b. Supported and proven in three to four paragraphs in the body, each introduced by topic sentences that relate directly to the topic but each providing a different argument or fact. c. Concluded with a summarizing paragraph which restates the thesis.",
  'The essay is not to exceed 1,000 words.',
  'Essays may not make use of either first person or second person. Essays written in either first person or second person will be disqualified. However, essays that contain occasional or infrequent first or second person pronouns will receive a point deduction. Points or a fraction of a point will be deducted which will prevent an otherwise first-place winner from placing first, a second-place winner from placing second, or a third-place winner from placing third.',
  'No reference materials, except for a dictionary provided by the proctor, will be permissible.',
  'Each entry will be judged according to the criteria on the Creative Writing Essay Judging Form, in this manual. The student must provide one judging form for state competition.',
  'Contestants who advance to the AACS National Competition will compose their entries prior to the competition. See rules and procedures in the 2025 AACS National Competition Manual.'
];

// Level definitions shared by getLevels() (client bootstrap) and
// submitRegistration (server-side validation) — categories drives which
// checkboxes/entry cards render per level.
var LEVELS = [
  { key: 'L1A', label: 'Level 1a (Grades 1-3)', categories: ['Poetry', 'Short Story'], rules: LEVEL_1A_RULES, lengthNote: '', soa: SOA_STANDARD },
  { key: 'L1B', label: 'Elementary Level 1b (Grades 4-6)', categories: ['Poetry', 'Short Story'], rules: LEVEL_1B_RULES, lengthNote: '', soa: SOA_STANDARD },
  { key: 'L2', label: 'Level II (Grades 7-8)', categories: ['Poetry', 'Short Story'], rules: LEVEL_2_RULES, lengthNote: '', soa: SOA_STANDARD },
  {
    key: 'L3', label: 'Level III (Senior High Grades 9-12)', categories: ['Poetry', 'Essay'], rules: LEVEL_3_RULES, lengthNote: '', soa: SOA_LEVEL_III,
    categoryRules: { Poetry: LEVEL_3_POETRY_RULES, Essay: LEVEL_3_ESSAY_RULES }
  }
];

function getSs_() {
  return SpreadsheetApp.getActiveSpreadsheet();
}

function getOrCreateSheet_(name) {
  var ss = getSs_();
  var sheet = ss.getSheetByName(name);
  if (!sheet) sheet = ss.insertSheet(name);
  return sheet;
}

function setHeaderRow_(sheet, headers) {
  sheet.clear();
  sheet.getRange(1, 1, 1, headers.length).setValues([headers]);
  sheet.setFrozenRows(1);
}

/**
 * Repairs a sheet's header row in place (WITHOUT clearing existing data
 * rows, unlike setHeaderRow_) if it doesn't exactly match `headers` —
 * every write in this project is positional (by column index), so a
 * mismatched header silently shows the wrong data under the wrong label.
 */
function ensureHeaderRow_(sheet, headers) {
  var range = sheet.getRange(1, 1, 1, headers.length);
  var current = sheet.getLastRow() > 0 ? range.getValues()[0] : [];
  var matches = headers.every(function (h, i) { return current[i] === h; });
  if (!matches) {
    range.setValues([headers]);
    sheet.setFrozenRows(1);
  }
}

/**
 * SpreadsheetApp.getUi() throws when called from a web app request
 * (no UI context) — functions shared between the Sheet menu and the
 * web app must use this instead of calling getUi().alert directly.
 */
function safeAlert_(message) {
  try {
    SpreadsheetApp.getUi().alert(message);
  } catch (e) {
    Logger.log(message);
  }
}

function ensureSettingExists_(key, defaultValue) {
  var sheet = getOrCreateSheet_(SHEETS.SETTINGS);
  var data = sheet.getDataRange().getValues();
  for (var i = 1; i < data.length; i++) {
    if (String(data[i][0]).trim() === key) return;
  }
  sheet.appendRow([key, defaultValue]);
}

// A cell that Sheets auto-detected as a date/time (e.g. typing a date-like
// string into a Settings value) comes back from getValues() as a raw Date
// object. Passing a raw Date through google.script.run to an HtmlService
// page can fail to invoke either the success or the failure handler at
// all — the request just never resolves, and the page is left blank with
// no error shown. Every value read from Settings must go through this.
function valueToPlain_(v) {
  if (Object.prototype.toString.call(v) === '[object Date]') {
    return Utilities.formatDate(v, Session.getScriptTimeZone(), 'EEEE, MMMM d, yyyy');
  }
  return v;
}

function getSettingsMap_() {
  var sheet = getOrCreateSheet_(SHEETS.SETTINGS);
  var data = sheet.getDataRange().getValues();
  var map = {};
  for (var i = 1; i < data.length; i++) {
    var key = String(data[i][0] || '').trim();
    if (key) map[key] = valueToPlain_(data[i][1]);
  }
  return map;
}

/**
 * Validates a base64-encoded upload is actually a PDF (by header, not just
 * the browser-reported mimeType) and drops it in the given Drive folder as
 * a view-anyone-with-link file.
 */
function validateAndUploadPdf_(base64Data, filename, mimeType, folder) {
  if (mimeType !== 'application/pdf') {
    throw new Error('Only PDF files are accepted for "' + filename + '".');
  }
  var bytes = Utilities.base64Decode(base64Data);
  var header = bytes.slice(0, 5).map(function (b) { return String.fromCharCode(b < 0 ? b + 256 : b); }).join('');
  if (header !== '%PDF-') {
    throw new Error('"' + filename + '" is not a valid PDF file.');
  }
  var blob = Utilities.newBlob(bytes, 'application/pdf', filename);
  var file = folder.createFile(blob);
  file.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW);
  return { url: file.getUrl(), name: filename };
}

function getOrCreateDriveFolder_(name) {
  var folders = DriveApp.getFoldersByName(name);
  return folders.hasNext() ? folders.next() : DriveApp.createFolder(name);
}

function getOrCreateSubfolder_(parent, name) {
  var folders = parent.getFoldersByName(name);
  return folders.hasNext() ? folders.next() : parent.createFolder(name);
}

/**
 * Moves `file` into `folder`, removing it from every folder it's
 * currently in. Uses the classic addFile/removeFile pair instead of
 * File.moveTo() since that's supported everywhere DriveApp is, with no
 * dependency on the Advanced Drive Service being enabled.
 */
/**
 * Builds a plain-data copy of `sourceSs` with no Apps Script container.
 * file.makeCopy() duplicates the bound script into the copy too, which is
 * why old archives kept ending up with their own live Apps Script project —
 * SpreadsheetApp.create() never gets a bound script, so copying sheet-by-
 * sheet here keeps archives as data only.
 */
function archiveSheetsOnly_(sourceSs, name) {
  var archiveSs = SpreadsheetApp.create(name);
  sourceSs.getSheets().forEach(function (sheet) {
    sheet.copyTo(archiveSs).setName(sheet.getName());
  });
  var defaultSheet = archiveSs.getSheetByName('Sheet1');
  if (defaultSheet) archiveSs.deleteSheet(defaultSheet);
  return archiveSs;
}

function moveFileToFolder_(file, folder) {
  var parents = file.getParents();
  while (parents.hasNext()) {
    parents.next().removeFile(file);
  }
  folder.addFile(file);
}

/* ===== Code.js ===== */
/**
 * Public intake web app. One-time submission per school — once a school
 * has a row in Registrations, the form refuses further submissions and
 * tells them to email the admin for changes.
 */
function doGet(e) {
  return HtmlService.createHtmlOutputFromFile('Form')
    .setTitle('MACS Creative Writing — Registration')
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}

function getSchoolList() {
  var sheet = getOrCreateSheet_(SHEETS.SCHOOLS);
  var data = sheet.getDataRange().getValues();
  var out = [];
  for (var i = 1; i < data.length; i++) {
    if (!data[i][0]) continue;
    out.push({ code: String(data[i][0]), name: data[i][1] });
  }
  return out;
}

function getJudgingSheetMap_() {
  var sheet = getOrCreateSheet_(SHEETS.JUDGING_SHEETS);
  var data = sheet.getDataRange().getValues();
  var map = {};
  for (var i = 1; i < data.length; i++) {
    if (!data[i][0]) continue;
    map[data[i][0] + '|' + data[i][1]] = data[i][2] || '';
  }
  return map;
}

/**
 * Full level/category/rules definitions the registration form needs
 * client-side, with each category's judging-sheet-template URL merged in
 * from the Judging Sheets tab (so an admin can update those links without
 * touching code).
 */
function getLevels() {
  var judgingSheets = getJudgingSheetMap_();
  return LEVELS.map(function (level) {
    var categories = level.categories.map(function (cat) {
      return { name: cat, judgingSheetUrl: judgingSheets[level.key + '|' + cat] || '' };
    });
    return {
      key: level.key, label: level.label, rules: level.rules, lengthNote: level.lengthNote || '',
      soa: level.soa, categories: categories, categoryRules: level.categoryRules || null
    };
  });
}

function getGeneralRules() {
  return GENERAL_RULES;
}

function getPaymentInfo() {
  ensureSettingExists_('Payment PDF Link (MACS Schools)', '');
  ensureSettingExists_('Payment PDF Link (Non-MACS Schools)', '');
  ensureSettingExists_('Payment Mailing Address', '');
  ensureSettingExists_('Entry & Judging Sheet Deadline', '5:00 PM on December 5, 2025');
  var settings = getSettingsMap_();
  return {
    macsPaymentPdfLink: settings['Payment PDF Link (MACS Schools)'] || '',
    nonMacsPaymentPdfLink: settings['Payment PDF Link (Non-MACS Schools)'] || '',
    mailingAddress: settings['Payment Mailing Address'] || '',
    deadline: settings['Entry & Judging Sheet Deadline'] || ''
  };
}

function schoolAlreadySubmitted_(schoolCode) {
  var sheet = getOrCreateSheet_(SHEETS.REGISTRATIONS);
  var data = sheet.getDataRange().getValues();
  for (var i = 1; i < data.length; i++) {
    if (String(data[i][1]) === String(schoolCode)) return true;
  }
  return false;
}

function checkSchoolStatus(schoolCode) {
  return { alreadySubmitted: schoolAlreadySubmitted_(schoolCode) };
}

/**
 * Uploads a PDF (sent as base64 from the browser) to a dedicated Drive
 * folder, nested by school/level/category, and returns a shareable view
 * link. `kind` is 'entry' or 'judging-sheet', just used to name the file.
 */
function uploadEntryFile(base64Data, filename, mimeType, schoolName, levelKey, category, kind) {
  var root = getOrCreateDriveFolder_('MACS Creative Writing Uploads');
  var schoolFolder = getOrCreateSubfolder_(root, String(schoolName || 'Unknown School').trim());
  var levelFolder = getOrCreateSubfolder_(schoolFolder, levelKey);
  var categoryFolder = getOrCreateSubfolder_(levelFolder, category);
  return validateAndUploadPdf_(base64Data, kind + '_' + filename, mimeType, categoryFolder);
}

/**
 * contact: {firstName, lastName, phone, email}
 * levelsSelected: array of level keys the school checked
 * entries: array of {levelKey, category, studentFirst, studentLast, title,
 *   entryUrl, judgingSheetUrl} — exactly one per checked category.
 */
function submitRegistration(schoolCode, schoolName, contact, rulesAccepted, levelsSelected, entries) {
  if (schoolAlreadySubmitted_(schoolCode)) {
    throw new Error('This school has already submitted entries. To make a change, please email the competition admin directly — the form does not allow a second submission.');
  }
  if (!contact || !contact.firstName || !contact.lastName || !contact.phone || !contact.email) {
    throw new Error('Contact person, phone, and email are required.');
  }
  if (!rulesAccepted) {
    throw new Error('You must certify that you have read the MACS Creative Writing General Rules.');
  }
  if (!entries || entries.length === 0) {
    throw new Error('At least one entry must be provided.');
  }

  var levelByKey = {};
  LEVELS.forEach(function (l) { levelByKey[l.key] = l; });

  // Each school may only have one entry per category per level.
  var seenCategoryPerLevel = {};
  entries.forEach(function (e) {
    var level = levelByKey[e.levelKey];
    if (!level) throw new Error('Unknown level: ' + e.levelKey);
    if (level.categories.indexOf(e.category) === -1) throw new Error('Unknown category "' + e.category + '" for ' + level.label);
    var dupeKey = e.levelKey + '|' + e.category;
    if (seenCategoryPerLevel[dupeKey]) throw new Error('Only one entry per category per level is allowed (' + level.label + ' — ' + e.category + ').');
    seenCategoryPerLevel[dupeKey] = true;
    if (!e.studentFirst || !e.studentLast || !e.title || !e.entryUrl || !e.judgingSheetUrl) {
      throw new Error('Every entry needs a student name, title, entry PDF, and judging sheet PDF (' + level.label + ' — ' + e.category + ').');
    }
  });

  var timestamp = new Date();
  var regSheet = getOrCreateSheet_(SHEETS.REGISTRATIONS);
  ensureHeaderRow_(regSheet, REGISTRATIONS_HEADERS);
  regSheet.appendRow([
    timestamp, schoolCode, schoolName, contact.firstName, contact.lastName, contact.phone, contact.email,
    (levelsSelected || []).join(', '), rulesAccepted ? 'TRUE' : 'FALSE'
  ]);

  var sheet = getOrCreateSheet_(SHEETS.ENTRIES);
  ensureHeaderRow_(sheet, ENTRIES_HEADERS);
  var seq = 0;
  var rows = entries.map(function (e) {
    seq++;
    var entryId = e.levelKey + '-' + schoolCode + '-' + seq;
    return [
      entryId, timestamp, schoolCode, schoolName, e.levelKey, e.category,
      e.studentFirst, e.studentLast, e.title, e.entryUrl, e.judgingSheetUrl
    ];
  });
  sheet.getRange(sheet.getLastRow() + 1, 1, rows.length, ENTRIES_HEADERS.length).setValues(rows);

  return { success: true, count: rows.length };
}

/* ===== YearRollover.js ===== */
/**
 * Year-to-year rollover. Schools, Settings, and Judging Sheets are
 * competition setup that should carry forward untouched (Bootstrap.js
 * already only seeds these when empty — this file doesn't need to touch
 * them at all). Registrations, Entries, and Admin Edit Log are one
 * competition's worth of data — those get archived and wiped.
 */

// Tabs that hold one year's worth of competition data, not carried-forward
// setup. `headers` is restored after clearing so the live sheet looks
// freshly bootstrapped.
var YEAR_RESET_TABS = [
  { name: SHEETS.REGISTRATIONS, headers: REGISTRATIONS_HEADERS },
  { name: SHEETS.ENTRIES, headers: ENTRIES_HEADERS },
  { name: SHEETS.ADMIN_EDITS_LOG, headers: ['Timestamp', 'Admin', 'Entry ID', 'Change Description'] }
];

// Shared archive root across every MACS competition — Secondary, Spelling
// Bee, Creative Writing, and Elementary all archive into the same
// <year> folder under this root (competition name goes in the file name,
// not a subfolder), keyed by Drive folder ID so it always resolves to the
// admin's own Drive regardless of file ownership/location.
var YEAR_ROLLOVER_ROOT_FOLDER_ID = 'DEMO_DRIVE_ID';
var YEAR_ROLLOVER_ROOT_FOLDER = 'MACS Fine Arts Competition';
var YEAR_ROLLOVER_COMPETITION = 'Creative Writing';

/**
 * Archives a full copy of the live spreadsheet into "<root>/<year>/" in
 * Drive, then clears the competition-data tabs in the live sheet so it's
 * ready for next year. Returns the archive file's URL/name so the admin
 * can confirm/open it.
 */
function resetForNextYear_(archiveYearLabel) {
  archiveYearLabel = (archiveYearLabel || '').toString().trim();
  if (!archiveYearLabel) throw new Error('Enter the year being archived (e.g. "2027") before resetting.');

  var ss = getSs_();
  var file = DriveApp.getFileById(ss.getId());
  var rootFolder = DriveApp.getFolderById(YEAR_ROLLOVER_ROOT_FOLDER_ID);
  var yearFolder = getOrCreateSubfolder_(rootFolder, archiveYearLabel);
  var archiveName = YEAR_ROLLOVER_COMPETITION + ' — ' + archiveYearLabel + ' Archive';
  var archiveSs = archiveSheetsOnly_(ss, archiveName);
  var archiveFile = DriveApp.getFileById(archiveSs.getId());
  moveFileToFolder_(archiveFile, yearFolder);

  YEAR_RESET_TABS.forEach(function (t) {
    var sheet = ss.getSheetByName(t.name);
    if (!sheet) return;
    sheet.getRange(1, 1, sheet.getMaxRows(), sheet.getMaxColumns()).clearNote();
    sheet.clear();
    if (t.headers && t.headers.length) {
      sheet.getRange(1, 1, 1, t.headers.length).setValues([t.headers]);
      sheet.setFrozenRows(1);
    }
  });

  ensureSettingExists_('Competition Year', '');
  var nextYear = archiveYearLabel.match(/^\d+$/) ? String(Number(archiveYearLabel) + 1) : '';
  var settingsSheet = getOrCreateSheet_(SHEETS.SETTINGS);
  var settingsData = settingsSheet.getDataRange().getValues();
  for (var i = 1; i < settingsData.length; i++) {
    if (settingsData[i][0] === 'Competition Year') {
      settingsSheet.getRange(i + 1, 2).setValue(nextYear);
      break;
    }
  }

  // Move the live file itself into next year's folder so the admin never
  // has to go find it — next year, the file that opens from that folder
  // IS the live working sheet, already reset and ready.
  var movedTo = null;
  if (nextYear) {
    var nextYearFolder = getOrCreateSubfolder_(rootFolder, nextYear);
    moveFileToFolder_(file, nextYearFolder);
    movedTo = YEAR_ROLLOVER_ROOT_FOLDER + '/' + nextYear;
  }

  return { archiveUrl: archiveFile.getUrl(), archiveName: archiveName, nextYear: nextYear, movedTo: movedTo };
}

/**
 * Sheet-menu entry point (no admin web app in this project yet) — prompts
 * for the year being archived, runs the rollover, and reports the result.
 */
function menu_resetForNextYear() {
  var ui = SpreadsheetApp.getUi();
  var response = ui.prompt('Archive & Reset for Next Year', 'Enter the year being archived (e.g. "2027"):', ui.ButtonSet.OK_CANCEL);
  if (response.getSelectedButton() !== ui.Button.OK) return;
  try {
    var result = resetForNextYear_(response.getResponseText());
    var msg = 'Archived as "' + result.archiveName + '".';
    if (result.movedTo) msg += ' Live sheet moved to ' + result.movedTo + '.';
    ui.alert('Rollover Complete', msg, ui.ButtonSet.OK);
  } catch (e) {
    ui.alert('Rollover Failed', e.message, ui.ButtonSet.OK);
  }
}

  global.MACS_WRITING_LOGIC = {
    bind: function (env) { SpreadsheetApp = env.SpreadsheetApp; DriveApp = env.DriveApp; Utilities = env.Utilities; Session = env.Session; Logger = env.Logger; HtmlService = env.HtmlService; },
    getSchoolList: getSchoolList,
    getLevels: getLevels,
    getGeneralRules: getGeneralRules,
    getPaymentInfo: getPaymentInfo,
    checkSchoolStatus: checkSchoolStatus,
    uploadEntryFile: uploadEntryFile,
    submitRegistration: submitRegistration,
    resetForNextYear_: resetForNextYear_,
    getSettingsMap_: getSettingsMap_,
    SHEETS: SHEETS,
    REGISTRATIONS_HEADERS: REGISTRATIONS_HEADERS,
    ENTRIES_HEADERS: ENTRIES_HEADERS,
    SCHOOLS_HEADERS: SCHOOLS_HEADERS,
    JUDGING_SHEETS_HEADERS: JUDGING_SHEETS_HEADERS,
    DEFAULT_JUDGING_SHEETS: DEFAULT_JUDGING_SHEETS,
    DEFAULT_SETTINGS: DEFAULT_SETTINGS,
    DEFAULT_SCHOOLS: DEFAULT_SCHOOLS,
    LEVELS: LEVELS
  };
})(typeof window !== "undefined" ? window : globalThis);
