/* GENERATED by demos/macs/build-logic.mjs — do not edit.
   This is the SOURCE PROJECT'S OWN server code, verbatim (Config, Auth, Intake, MacsBridge, AdminBackend,
   MasterList, TestData, YearRollover) with the real domain, admin address, sibling-app URL and Drive ids
   scrubbed. The demo runs it in the browser over in-memory Google services (mock.js), so sign-in, entry ids,
   cross-references, the per-school caps and the one-time-submission rule are the app's real behaviour. */
(function (global) {
  var SpreadsheetApp, CacheService, PropertiesService, DriveApp, UrlFetchApp, LockService, Session, Utilities, Logger, HtmlService, MailApp;
/* ===== Config.js ===== */
/**
 * Sheet tab names and default seed data. All scheduling logic reads live
 * values from these sheets at runtime — nothing here is authoritative
 * once the sheet exists; this is only used to seed a fresh spreadsheet.
 */

var SHEETS = {
  SUBMISSIONS: 'Submissions',
  MASTER: 'Master',
  CATEGORY_COUNTS: 'List of Categories',
  SETTINGS: 'Settings',
  CATEGORY_CONFIG: 'Category Config',
  JUDGES: 'Judges',
  SCHOOLS: 'Schools',
  SCHEDULE: 'Schedule',
  ADMIN_EDITS_LOG: 'Admin Edit Log',
  REGISTRATIONS: 'Registrations',
  FIELD_TEMPLATES: 'Field Templates',
  JUDGING_SHEETS: 'Judging Sheets'
};

// Named judging-sheet PDF links — a category references one by name
// (Category Config's "Judging Sheet Name" column) instead of being
// auto-linked by Section, so one sheet can be shared across any set of
// categories regardless of section.
var JUDGING_SHEETS_HEADERS = ['Name', 'Url'];
var DEFAULT_JUDGING_SHEETS = [
  ['Bible', ''], ['Music', ''], ['Speech', ''], ['Art', '']
];

var REGISTRATIONS_HEADERS = ['Timestamp', 'School Code', 'School Name', 'Contact First Name', 'Contact Last Name', 'Phone Number', 'Email'];

// Column headers for the normalized Submissions tab — one row per
// student-or-group entry in a single category.
var SUBMISSIONS_HEADERS = [
  'Entry ID', 'Timestamp', 'School Code', 'School Name', 'Category Code',
  'Level', 'Student/Group ID#', 'Name', 'Title', 'Author/Composer',
  'Accompanist', 'Conductor', 'Attachment URL', 'Other Entry IDs (auto)', 'Roster JSON'
];

var JUDGES_HEADERS = ['Judge Name', 'Category Code', 'Notes'];

var SCHOOLS_HEADERS = ['School Code', 'School Name', 'Color Hex'];

// Default room -> building grouping. Lives on the Settings sheet so an
// admin can edit it; this is only the seed value for a fresh sheet.
var DEFAULT_BUILDINGS = {
  'Gym': 'HS Building',
  'HS Room 109': 'HS Building',
  'Mod 701A': 'HS Building',
  'Sanctuary': 'Elementary Building',
  'Band Room': 'Elementary Building',
  'Elem Room 106': 'Elementary Building',
  'Elem Room 200': 'Elementary Building',
  'Elem Room 209': 'Elementary Building'
};

// Default per-category config, seeded from the 2023-2024 zoning found in
// Master Schedule 2024 and the current JotForm. Editable afterward on the
// "Category Config" sheet — the scheduler always reads that sheet, not
// this array, once it exists.
var DEFAULT_CATEGORY_CONFIG_HEADERS = [
  'Category Code', 'Category Name', 'Section', 'Level', 'Default Room', 'Duration (15-min slots)',
  'Field Template', 'Group Roster', 'Max Per School (0 = unlimited)', 'Room Required', 'Judging Sheet Name'
];

// 'Section' groups categories on the registration form (Bible/Music/Art),
// matching the JotForm's page-section layout. 'Level' drives the
// Junior High / Senior High grouping within each section. 'Field Template'
// references a row on the "Field Templates" sheet, which controls the
// entry fields shown, whether Accompanist/Conductor appear, and whether
// the category gets a live time slot at all. 'Group Roster' is set
// per-category (TRUE/FALSE) — turns on the student roster + autofill for
// that specific category without needing a separate template.
// 'Max Per School' caps how many entries one school can submit in that
// category (0 = no limit) — enforced when the school submits.
// 'Room Required' (TRUE/FALSE) — when FALSE (the default), 'Default Room'
// is only a starting preference: the scheduler is free to place the
// category in ANY available room if the preferred one is busy. Set TRUE
// only for categories that genuinely need that specific room (e.g. an
// ensemble that needs the Gym or Sanctuary's space/instruments) — those
// entries will only ever be scheduled in 'Default Room'.
var DEFAULT_CATEGORY_CONFIG = [
  ['JBM', 'Bible Memory', 'Bible', 'Junior High', 'Mod 701A', 1, 'verse', false, 2, false, ''],
  ['SBM', 'Bible Memory', 'Bible', 'Senior High', 'Mod 701A', 1, 'verse', false, 2, false, ''],
  ['JBT', 'Bible Teaching', 'Bible', 'Junior High', 'Mod 701A', 1, 'sermon', false, 2, false, ''],
  ['SBT', 'Bible Teaching', 'Bible', 'Senior High', 'Mod 701A', 1, 'sermon', false, 2, false, ''],
  ['JEP', 'Expository Preaching', 'Bible', 'Junior High', 'Mod 701A', 1, 'sermon', false, 2, false, ''],
  ['SEP', 'Expository Preaching', 'Bible', 'Senior High', 'Mod 701A', 1, 'sermon', false, 2, false, ''],
  ['JEVP', 'Evangelistic Preaching', 'Bible', 'Junior High', 'Mod 701A', 1, 'sermon', false, 2, false, ''],
  ['SEVP', 'Evangelistic Preaching', 'Bible', 'Senior High', 'Mod 701A', 1, 'sermon', false, 2, false, ''],
  ['JTP', 'Topical Preaching', 'Bible', 'Junior High', 'Mod 701A', 1, 'sermon', false, 2, false, ''],
  ['STP', 'Topical Preaching', 'Bible', 'Senior High', 'Mod 701A', 1, 'sermon', false, 2, false, ''],
  ['JFVS', 'Female Vocal Solo', 'Music', 'Junior High', 'Elem Room 106', 1, 'music-acc', false, 2, false, ''],
  ['SFVS', 'Female Vocal Solo', 'Music', 'Senior High', 'Elem Room 106', 1, 'music-acc', false, 2, false, ''],
  ['JMVS', 'Male Vocal Solo', 'Music', 'Junior High', 'Elem Room 106', 1, 'music-acc', false, 2, false, ''],
  ['SMVS', 'Male Vocal Solo', 'Music', 'Senior High', 'Elem Room 106', 1, 'music-acc', false, 2, false, ''],
  ['JBS', 'Brass Solo', 'Music', 'Junior High', 'Elem Room 209', 1, 'music-acc', false, 2, false, ''],
  ['SBS', 'Brass Solo', 'Music', 'Senior High', 'Elem Room 209', 1, 'music-acc', false, 2, false, ''],
  ['JWS', 'Woodwind Solo', 'Music', 'Junior High', 'Elem Room 209', 1, 'music-acc', false, 2, false, ''],
  ['SWS', 'Woodwind Solo', 'Music', 'Senior High', 'Elem Room 209', 1, 'music-acc', false, 2, false, ''],
  ['JSS', 'String Solo', 'Music', 'Junior High', 'Band Room', 1, 'music-acc', false, 2, false, ''],
  ['SSS', 'String Solo', 'Music', 'Senior High', 'Band Room', 1, 'music-acc', false, 2, false, ''],
  ['JMPS', 'Percussion Solo', 'Music', 'Junior High', 'Band Room', 1, 'music-acc', false, 2, false, ''],
  ['SMPS', 'Percussion Solo', 'Music', 'Senior High', 'Band Room', 1, 'music-acc', false, 2, false, ''],
  ['JSP', 'Sacred Piano Solo', 'Music', 'Junior High', 'Elem Room 200', 1, 'music', false, 2, true, ''],
  ['SSP', 'Sacred Piano Solo', 'Music', 'Senior High', 'Elem Room 200', 1, 'music', false, 2, true, ''],
  ['JCP', 'Classical Piano Solo', 'Music', 'Junior High', 'Elem Room 200', 1, 'music', false, 2, true, ''],
  ['SCP', 'Classical Piano Solo', 'Music', 'Senior High', 'Elem Room 200', 1, 'music', false, 2, true, ''],
  ['JSPD', 'Sacred Piano Duet', 'Music', 'Junior High', 'Elem Room 200', 1, 'music', true, 2, true, ''],
  ['SSPD', 'Sacred Piano Duet', 'Music', 'Senior High', 'Elem Room 200', 1, 'music', true, 2, true, ''],
  ['JCPD', 'Classical Piano Duet', 'Music', 'Junior High', 'Elem Room 200', 1, 'music', true, 2, true, ''],
  ['SCPD', 'Classical Piano Duet', 'Music', 'Senior High', 'Elem Room 200', 1, 'music', true, 2, true, ''],
  ['JSVE', 'Small Vocal Ensemble', 'Music', 'Junior High', 'Band Room', 1, 'music-acc', true, 2, true, ''],
  ['SSVE', 'Small Vocal Ensemble', 'Music', 'Senior High', 'Band Room', 1, 'music-acc', true, 2, true, ''],
  ['JLVE', 'Large Vocal Ensemble', 'Music', 'Junior High', 'Sanctuary', 1, 'music-acc-cond', true, 2, true, ''],
  ['SLVE', 'Large Vocal Ensemble', 'Music', 'Senior High', 'Sanctuary', 1, 'music-acc-cond', true, 2, true, ''],
  ['JCG', 'Choral Group', 'Music', 'Junior High', 'Sanctuary', 1, 'music-acc-cond', true, 2, true, ''],
  ['SCG', 'Choral Group', 'Music', 'Senior High', 'Sanctuary', 1, 'music-acc-cond', true, 2, true, ''],
  ['JYC', 'Youth Choir', 'Music', 'Junior High', 'Sanctuary', 1, 'music-acc-cond', true, 2, true, ''],
  ['SYC', 'Youth Choir', 'Music', 'Senior High', 'Sanctuary', 1, 'music-acc-cond', true, 2, true, ''],
  ['JSIE', 'Small Instrument Ensemble', 'Music', 'Junior High', 'Band Room', 1, 'music-acc', true, 2, true, ''],
  ['SSIE', 'Small Instrument Ensemble', 'Music', 'Senior High', 'Band Room', 1, 'music-acc', true, 2, true, ''],
  ['JLIE', 'Large Instrument Ensemble', 'Music', 'Junior High', 'HS Room 109', 1, 'music-acc-cond', true, 2, true, ''],
  ['SLIE', 'Large Instrument Ensemble', 'Music', 'Senior High', 'HS Room 109', 1, 'music-acc-cond', true, 2, true, ''],
  ['JORBD', 'Orchestra/Band', 'Music', 'Junior High', 'Gym', 1, 'music-cond', true, 2, true, ''],
  ['SORBD', 'Orchestra/Band', 'Music', 'Senior High', 'Gym', 1, 'music-cond', true, 2, true, ''],
  ['JHBE', 'Handbell/Handchime Ensemble', 'Music', 'Junior High', 'Gym', 1, 'music-acc-cond', false, 2, true, ''],
  ['SHBE', 'Handbell/Handchime Ensemble', 'Music', 'Senior High', 'Gym', 1, 'music-acc-cond', false, 2, true, ''],
  ['JHBC', 'Handbell/Handchime Choir', 'Music', 'Junior High', 'Gym', 1, 'music-acc-cond', true, 2, true, ''],
  ['SHBC', 'Handbell/Handchime Choir', 'Music', 'Senior High', 'Gym', 1, 'music-acc-cond', true, 2, true, ''],
  // Not scheduled into the live grid — judged asynchronously.
  ['JAP', 'Art & Projects', 'Art', 'Junior High', 'Mod 701A', 0, 'art', false, 2, false, ''],
  ['SAP', 'Art & Projects', 'Art', 'Senior High', 'Mod 701A', 0, 'art', false, 2, false, ''],
  // Speech section — individual pieces use 'speech' (Title Only); the
  // group performance categories (Acting, Readers Theater, Choric
  // Speaking, Debate) use the SAME template with Group Roster on.
  ['JDI', 'Dramatic Interpretation', 'Speech', 'Junior High', 'Mod 701A', 1, 'speech', false, 2, false, ''],
  ['SDI', 'Dramatic Interpretation', 'Speech', 'Senior High', 'Mod 701A', 1, 'speech', false, 2, false, ''],
  ['JOIP', 'Oral Interpretation of Poetry', 'Speech', 'Junior High', 'Mod 701A', 1, 'speech', false, 2, false, ''],
  ['SOIP', 'Oral Interpretation of Poetry', 'Speech', 'Senior High', 'Mod 701A', 1, 'speech', false, 2, false, ''],
  ['JRR', 'Religious Reading', 'Speech', 'Junior High', 'Mod 701A', 1, 'speech', false, 2, false, ''],
  ['SRR', 'Religious Reading', 'Speech', 'Senior High', 'Mod 701A', 1, 'speech', false, 2, false, ''],
  ['JDC', 'Declamation', 'Speech', 'Junior High', 'Mod 701A', 1, 'speech', false, 2, false, ''],
  ['SDC', 'Declamation', 'Speech', 'Senior High', 'Mod 701A', 1, 'speech', false, 2, false, ''],
  ['JHI', 'Humorous Interpretation', 'Speech', 'Junior High', 'Elem Room 106', 1, 'speech', false, 2, false, ''],
  ['SHI', 'Humorous Interpretation', 'Speech', 'Senior High', 'Elem Room 106', 1, 'speech', false, 2, false, ''],
  ['JOPO', 'Original Persuasive Oratory', 'Speech', 'Junior High', 'Elem Room 106', 1, 'speech', false, 2, false, ''],
  ['SOPO', 'Original Persuasive Oratory', 'Speech', 'Senior High', 'Elem Room 106', 1, 'speech', false, 2, false, ''],
  ['SXSP', 'Extemporaneous Speaking', 'Speech', 'Senior High', 'Elem Room 209', 1, 'speech', false, 2, false, ''],
  ['JOIS', 'Oral Interpretation of Scripture', 'Speech', 'Junior High', 'Elem Room 209', 1, 'speech', false, 2, false, ''],
  ['SOIS', 'Oral Interpretation of Scripture', 'Speech', 'Senior High', 'Elem Room 209', 1, 'speech', false, 2, false, ''],
  ['JDA', 'Acting', 'Speech', 'Junior High', 'HS Room 109', 1, 'speech', true, 2, false, ''],
  ['SDA', 'Acting', 'Speech', 'Senior High', 'HS Room 109', 1, 'speech', true, 2, false, ''],
  ['JRT', 'Readers Theater', 'Speech', 'Junior High', 'HS Room 109', 1, 'speech', true, 2, false, ''],
  ['SRT', 'Readers Theater', 'Speech', 'Senior High', 'HS Room 109', 1, 'speech', true, 2, false, ''],
  ['JCS', 'Choric Speaking', 'Speech', 'Junior High', 'HS Room 109', 1, 'speech', true, 2, false, ''],
  ['SCS', 'Choric Speaking', 'Speech', 'Senior High', 'HS Room 109', 1, 'speech', true, 2, false, ''],
  ['JD', 'Debate', 'Speech', 'Junior High', 'HS Room 109', 1, 'speech', true, 2, false, ''],
  ['SD', 'Debate', 'Speech', 'Senior High', 'HS Room 109', 1, 'speech', true, 2, false, '']
];

// Field Templates sheet — the single source of truth for what a category's
// entry form looks like, referenced by Category Config's "Field Template"
// column. 'Fields JSON' is an array of {key, label, type, full}; type is
// "text", "textarea", or "file" (PDF upload); full means the field spans
// the full row width. 'Name Label' customizes the always-shown name field
// (e.g. "Student Name" for solos vs "Group Name" for ensembles) instead
// of a hardcoded "Student / Group Name". 'Scheduled' controls whether the
// category gets a live time slot. (Group roster is set per-category on
// Category Config, not here — one template can serve both group and
// non-group categories.)
var FIELD_TEMPLATES_HEADERS = ['Template Key', 'Label', 'Name Label', 'Fields JSON', 'Scheduled'];

var DEFAULT_FIELD_TEMPLATES = [
  ['music', 'Music — Title + Composer', 'Student Name',
    '[{"key":"title","label":"Title"},{"key":"authorComposer","label":"Composer"}]', true],
  ['music-acc', 'Music — Title + Composer + Accompanist', 'Student Name',
    '[{"key":"title","label":"Title"},{"key":"authorComposer","label":"Composer"},{"key":"accompanist","label":"Accompanist"}]', true],
  ['music-cond', 'Music — Title + Composer + Conductor', 'Group Name',
    '[{"key":"title","label":"Title"},{"key":"authorComposer","label":"Composer"},{"key":"conductor","label":"Conductor"}]', true],
  ['music-acc-cond', 'Music — Title + Composer + Accompanist + Conductor', 'Group Name',
    '[{"key":"title","label":"Title"},{"key":"authorComposer","label":"Composer"},{"key":"accompanist","label":"Accompanist"},{"key":"conductor","label":"Conductor"}]', true],
  ['sermon', 'Sermon — Title Only', 'Student Name',
    '[{"key":"title","label":"Title","full":true}]', true],
  ['verse', 'Bible Verse — Title Only', 'Student Name',
    '[{"key":"title","label":"Title","full":true}]', true],
  ['speech', 'Speech — Title Only', 'Student Name',
    '[{"key":"title","label":"Title","full":true}]', true],
  ['simple', 'Simple — Title Only (not scheduled)', 'Student Name',
    '[{"key":"title","label":"Title","full":true}]', false],
  ['art', 'Art — Title + PDF Upload (not scheduled)', 'Student Name',
    '[{"key":"title","label":"Title"},{"key":"attachment","label":"Upload PDF","type":"file","full":true}]', false]
];

// Default general settings — key/value pairs, seeded once, editable after.
var DEFAULT_SETTINGS = [
  ['Competition Year', ''],
  ['Admin Emails', 'admin@example.edu'],
  ['Payment PDF Link (MACS Schools)', ''],
  ['Payment PDF Link (Non-MACS Schools)', ''],
  ['Day Start Time', '08:30'],
  ['Day End Time', '14:45'],
  ['Slot Length (minutes)', '15'],
  ['Lunch Start Time', '11:00'],
  ['Lunch End Time', '13:30'],
  ['Lunch Room', 'Gym'],
  ['Gym Pre-Lunch Blackout (minutes)', '30'],
  ['Gym Closed (TRUE/FALSE)', 'FALSE'],
  ['Gym Closed After Time (blank = no partial closure)', ''],
  ['Opening Ceremony Room', 'Sanctuary'],
  ['Opening Ceremony Start Time', '08:30'],
  ['Opening Ceremony Duration (minutes)', '30'],
  ['Closing Ceremony Room', 'Gym'],
  ['Closing Ceremony Start Time', '14:30'],
  ['Closing Ceremony Duration (minutes)', '15'],
  ['Cross-Building Travel Buffer (minutes)', '15']
];

function getSs_() {
  return SpreadsheetApp.getActiveSpreadsheet();
}

function getOrCreateSheet_(name) {
  var ss = getSs_();
  var sheet = ss.getSheetByName(name);
  if (!sheet) sheet = ss.insertSheet(name);
  return sheet;
}

function setHeaderRow_(sheet, headers) {
  sheet.clear();
  sheet.getRange(1, 1, 1, headers.length).setValues([headers]);
  sheet.setFrozenRows(1);
}

// A cell typed as a time-of-day or date (e.g. "08:30", or anything Sheets
// auto-converts) comes back from getValues() as a raw Date object. Passing
// a raw Date through google.script.run to an HtmlService page can fail to
// invoke either the success or the failure handler at all — the request
// just never resolves, and the page is left blank with no error shown.
// Any admin_get* function whose payload reaches AdminApp.html must run its
// values through this first.
function timeOfDayToString_(v) {
  if (Object.prototype.toString.call(v) === '[object Date]') {
    return Utilities.formatDate(v, Session.getScriptTimeZone(), 'HH:mm');
  }
  return v;
}
function timestampToString_(v) {
  if (Object.prototype.toString.call(v) === '[object Date]') {
    return Utilities.formatDate(v, Session.getScriptTimeZone(), 'yyyy-MM-dd HH:mm:ss');
  }
  return v;
}

/**
 * Repairs a sheet's header row in place (WITHOUT clearing existing data
 * rows, unlike setHeaderRow_) if it doesn't exactly match `headers` — a
 * mismatched header is what causes columns to silently show the wrong
 * data under the wrong label, since every write in this project is
 * positional (by column index), not by header name.
 */
function ensureHeaderRow_(sheet, headers) {
  var range = sheet.getRange(1, 1, 1, headers.length);
  var current = sheet.getLastRow() > 0 ? range.getValues()[0] : [];
  var matches = headers.every(function (h, i) { return current[i] === h; });
  if (!matches) {
    range.setValues([headers]);
    sheet.setFrozenRows(1);
  }
}

/**
 * SpreadsheetApp.getUi() throws when called from a web app request
 * (no UI context) — functions shared between the Sheet menu and the
 * Admin web app must use this instead of calling getUi().alert directly.
 */
function safeAlert_(message) {
  try {
    SpreadsheetApp.getUi().alert(message);
  } catch (e) {
    Logger.log(message);
  }
}

/**
 * Validates a base64-encoded upload is actually a PDF (by header, not just
 * the browser-reported mimeType) and drops it in the given Drive folder as
 * a view-anyone-with-link file. Shared by the public intake form's Art PDF
 * uploads and the Admin app's Judging Sheet uploads.
 */
function validateAndUploadPdf_(base64Data, filename, mimeType, folder) {
  if (mimeType !== 'application/pdf') {
    throw new Error('Only PDF files are accepted for "' + filename + '".');
  }
  var bytes = Utilities.base64Decode(base64Data);
  var header = bytes.slice(0, 5).map(function (b) { return String.fromCharCode(b < 0 ? b + 256 : b); }).join('');
  if (header !== '%PDF-') {
    throw new Error('"' + filename + '" is not a valid PDF file.');
  }
  var blob = Utilities.newBlob(bytes, 'application/pdf', filename);
  var file = folder.createFile(blob);
  file.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW);
  return { url: file.getUrl(), name: filename };
}

function getOrCreateDriveFolder_(name) {
  var folders = DriveApp.getFoldersByName(name);
  return folders.hasNext() ? folders.next() : DriveApp.createFolder(name);
}

/**
 * Same as getOrCreateDriveFolder_ but nested inside `parent` instead of My
 * Drive's root — used to build the MACS Fine Arts Competition / <year> /
 * <competition> archive hierarchy without creating duplicate same-named
 * folders scattered across Drive.
 */
function getOrCreateSubfolder_(parent, name) {
  var folders = parent.getFoldersByName(name);
  return folders.hasNext() ? folders.next() : parent.createFolder(name);
}

/**
 * Moves `file` into `folder`, removing it from every folder it's
 * currently in. Uses the classic addFile/removeFile pair instead of
 * File.moveTo() since that's supported everywhere DriveApp is, with no
 * dependency on the Advanced Drive Service being enabled.
 */
function moveFileToFolder_(file, folder) {
  var parents = file.getParents();
  while (parents.hasNext()) {
    parents.next().removeFile(file);
  }
  folder.addFile(file);
}

/**
 * Builds a plain-data copy of `sourceSs` with no Apps Script container.
 * file.makeCopy() duplicates the bound script into the copy too, which is
 * why old archives kept ending up with their own live Apps Script project —
 * SpreadsheetApp.create() never gets a bound script, so copying sheet-by-
 * sheet here keeps archives as data only.
 */
function archiveSheetsOnly_(sourceSs, name) {
  var archiveSs = SpreadsheetApp.create(name);
  sourceSs.getSheets().forEach(function (sheet) {
    sheet.copyTo(archiveSs).setName(sheet.getName());
  });
  var defaultSheet = archiveSs.getSheetByName('Sheet1');
  if (defaultSheet) archiveSs.deleteSheet(defaultSheet);
  return archiveSs;
}

/**
 * Appends a Settings row for `key` (with `defaultValue`) if it doesn't
 * already exist. Needed because Bootstrap.js only seeds DEFAULT_SETTINGS
 * into a completely empty Settings sheet — a setting added to that array
 * after a spreadsheet has already been set up (like 'Competition Year')
 * would otherwise never appear for existing users.
 */
function ensureSettingExists_(key, defaultValue) {
  var sheet = getOrCreateSheet_(SHEETS.SETTINGS);
  var data = sheet.getDataRange().getValues();
  for (var i = 1; i < data.length; i++) {
    if (data[i][0] === key) return;
  }
  sheet.appendRow([key, defaultValue]);
}

/* ===== Auth.js ===== */
/**
 * Auth.js — school sign-in for the public registration form.
 *
 * Identity comes from MACS Forms' _System!MACS_Schools allowlist, which this project cannot
 * read: it's a different GAS project with a different Drive owner. So MacsBridge.js proxies
 * the OTP to runner-macs (which owns that sheet), and this file does the two crypto jobs on
 * this side:
 *
 *   AppHandoffLogic — the short-lived ticket that proves to runner-macs WHICH APP is calling.
 *                     Same mechanism as the PTC Scheduling handoff, shared APP_HANDOFF_SECRET.
 *   TokenLogic      — this app's OWN session token, minted after runner-macs confirms a code.
 *                     MACS's token is signed with MACS's secret and unverifiable here, so we
 *                     never borrow it — same reasoning as PTC's ssoLogin.
 *
 * Both IIFEs are VERBATIM copies of hcs-custom-forms' canonical logic/app-handoff.js and
 * logic/token.js. Two GAS projects cannot share a file, so this duplication is by design (see
 * that repo's docs/AppHandoffTemplate.js, which exists to be copied). Do not "improve" either
 * module locally: tests/app_handoff.test.js pins a cross-repo parity vector, and any drift
 * breaks every call between the projects. Fix the canonical copy, then re-copy here.
 *
 * Those tests are Node-only and are excluded from `clasp push` by .claspignore — they must never
 * reach the Apps Script project. Apps Script evaluates every file's top-level scope on every
 * execution, and each test file opens with `require(...)`, which is a ReferenceError there: one
 * stray test file breaks every server call in the project, not just itself. Run them with
 * `npm test` from the repo root.
 */

// ---------- pure: app-handoff ticket (verbatim from hcs-custom-forms/logic/app-handoff.js) ----------

var AppHandoffLogic = (function () {
  var VERSION = 'v1';
  var TTL_MS = 2 * 60 * 1000; // 2 minutes — short enough that no single-use tracking is needed
  var ALPHA = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';

  function bytesToB64url(bytes) {
    var out = '';
    for (var i = 0; i < bytes.length; i += 3) {
      var b1 = bytes[i] & 255;
      var b2 = i + 1 < bytes.length ? bytes[i + 1] & 255 : 0;
      var b3 = i + 2 < bytes.length ? bytes[i + 2] & 255 : 0;
      out += ALPHA[b1 >> 2] + ALPHA[((b1 & 3) << 4) | (b2 >> 4)];
      out += i + 1 < bytes.length ? ALPHA[((b2 & 15) << 2) | (b3 >> 6)] : '';
      out += i + 2 < bytes.length ? ALPHA[b3 & 63] : '';
    }
    return out;
  }
  function b64urlEncode(str) {
    var bytes = [];
    for (var i = 0; i < str.length; i++) {
      var c = str.charCodeAt(i);
      if (c < 128) bytes.push(c);
      else if (c < 2048) bytes.push(192 | (c >> 6), 128 | (c & 63));
      else bytes.push(224 | (c >> 12), 128 | ((c >> 6) & 63), 128 | (c & 63));
    }
    return bytesToB64url(bytes);
  }
  function b64urlDecodeToString(b64) {
    var bytes = [], buffer = 0, bits = 0;
    for (var i = 0; i < b64.length; i++) {
      var v = ALPHA.indexOf(b64[i]);
      if (v === -1) throw new Error('bad b64url');
      buffer = (buffer << 6) | v; bits += 6;
      if (bits >= 8) { bits -= 8; bytes.push((buffer >> bits) & 255); }
    }
    var out = '';
    for (var j = 0; j < bytes.length; j++) {
      var b = bytes[j];
      if (b < 128) out += String.fromCharCode(b);
      else if ((b & 224) === 192) out += String.fromCharCode(((b & 31) << 6) | (bytes[++j] & 63));
      else out += String.fromCharCode(((b & 15) << 12) | ((bytes[++j] & 63) << 6) | (bytes[++j] & 63));
    }
    return out;
  }
  function constantTimeEqual(a, b) {
    if (a.length !== b.length) return false;
    var diff = 0;
    for (var i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
    return diff === 0;
  }

  function mint(email, role, aud, opts) {
    var payload = { e: email, role: role, aud: aud, exp: opts.nowMs + TTL_MS };
    var payloadB64 = b64urlEncode(JSON.stringify(payload));
    var sig = bytesToB64url(opts.hmacFn(VERSION + '.' + payloadB64, opts.secret));
    return VERSION + '.' + payloadB64 + '.' + sig;
  }
  function verify(ticket, opts) {
    try {
      if (typeof ticket !== 'string') return { ok: false, code: 'TICKET_INVALID' };
      var parts = ticket.split('.');
      if (parts.length !== 3 || parts[0] !== VERSION) return { ok: false, code: 'TICKET_INVALID' };
      var expectedSig = bytesToB64url(opts.hmacFn(parts[0] + '.' + parts[1], opts.secret));
      if (!constantTimeEqual(expectedSig, parts[2])) return { ok: false, code: 'TICKET_INVALID' };
      var payload = JSON.parse(b64urlDecodeToString(parts[1]));
      if (!payload || typeof payload.e !== 'string' || typeof payload.role !== 'string' || typeof payload.aud !== 'string' || typeof payload.exp !== 'number') return { ok: false, code: 'TICKET_INVALID' };
      if (payload.exp <= opts.nowMs) return { ok: false, code: 'TICKET_EXPIRED' };
      return { ok: true, email: payload.e, role: payload.role, aud: payload.aud };
    } catch (err) { return { ok: false, code: 'TICKET_INVALID' }; }
  }

  return { mint: mint, verify: verify, TTL_MS: TTL_MS };
})();

// ---------- pure: session token (verbatim from hcs-custom-forms/logic/token.js) ----------

var TokenLogic = (function () {
  var VERSION = 'v1';
  var DEFAULT_TTL_MS = 14 * 24 * 60 * 60 * 1000; // 14 days
  var ALPHA = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';

  function bytesToB64url(bytes) {
    var out = '';
    for (var i = 0; i < bytes.length; i += 3) {
      var b1 = bytes[i] & 255;
      var b2 = i + 1 < bytes.length ? bytes[i + 1] & 255 : 0;
      var b3 = i + 2 < bytes.length ? bytes[i + 2] & 255 : 0;
      out += ALPHA[b1 >> 2] + ALPHA[((b1 & 3) << 4) | (b2 >> 4)];
      out += i + 1 < bytes.length ? ALPHA[((b2 & 15) << 2) | (b3 >> 6)] : '';
      out += i + 2 < bytes.length ? ALPHA[b3 & 63] : '';
    }
    return out;
  }
  function b64urlEncode(str) {
    var bytes = [];
    for (var i = 0; i < str.length; i++) {
      var c = str.charCodeAt(i);
      if (c < 128) bytes.push(c);
      else if (c < 2048) bytes.push(192 | (c >> 6), 128 | (c & 63));
      else bytes.push(224 | (c >> 12), 128 | ((c >> 6) & 63), 128 | (c & 63));
    }
    return bytesToB64url(bytes);
  }
  function b64urlDecodeToString(b64) {
    var bytes = [], buffer = 0, bits = 0;
    for (var i = 0; i < b64.length; i++) {
      var v = ALPHA.indexOf(b64[i]);
      if (v === -1) throw new Error('bad b64url');
      buffer = (buffer << 6) | v; bits += 6;
      if (bits >= 8) { bits -= 8; bytes.push((buffer >> bits) & 255); }
    }
    var out = '';
    for (var j = 0; j < bytes.length; j++) {
      var b = bytes[j];
      if (b < 128) out += String.fromCharCode(b);
      else if ((b & 224) === 192) out += String.fromCharCode(((b & 31) << 6) | (bytes[++j] & 63));
      else out += String.fromCharCode(((b & 15) << 12) | ((bytes[++j] & 63) << 6) | (bytes[++j] & 63));
    }
    return out;
  }
  function constantTimeEqual(a, b) {
    if (a.length !== b.length) return false;
    var diff = 0;
    for (var i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
    return diff === 0;
  }
  function mint(email, opts) {
    var payload = { e: email, iat: opts.nowMs, exp: opts.nowMs + (opts.ttlMs || DEFAULT_TTL_MS), ep: opts.epoch };
    if (opts.claims) for (var k in opts.claims) if (Object.prototype.hasOwnProperty.call(opts.claims, k) && !(k in payload)) payload[k] = opts.claims[k];
    var payloadB64 = b64urlEncode(JSON.stringify(payload));
    var sig = bytesToB64url(opts.hmacFn(VERSION + '.' + payloadB64, opts.secret));
    return VERSION + '.' + payloadB64 + '.' + sig;
  }
  function verify(token, opts) {
    try {
      if (typeof token !== 'string') return { ok: false, code: 'AUTH_INVALID' };
      var parts = token.split('.');
      if (parts.length !== 3 || parts[0] !== VERSION) return { ok: false, code: 'AUTH_INVALID' };
      var expectedSig = bytesToB64url(opts.hmacFn(parts[0] + '.' + parts[1], opts.secret));
      if (!constantTimeEqual(expectedSig, parts[2])) return { ok: false, code: 'AUTH_INVALID' };
      var payload = JSON.parse(b64urlDecodeToString(parts[1]));
      if (!payload || typeof payload.e !== 'string') return { ok: false, code: 'AUTH_INVALID' };
      if (payload.ep !== opts.epoch) return { ok: false, code: 'AUTH_EXPIRED' };
      if (typeof payload.exp !== 'number' || payload.exp <= opts.nowMs) return { ok: false, code: 'AUTH_EXPIRED' };
      return { ok: true, email: payload.e, claims: payload };
    } catch (err) { return { ok: false, code: 'AUTH_INVALID' }; }
  }
  return { mint: mint, verify: verify, DEFAULT_TTL_MS: DEFAULT_TTL_MS };
})();

// ---------- GAS layer: secrets, epoch, and this app's session ----------

var SCHOOL_SESSION_TTL_MS_ = 12 * 60 * 60 * 1000; // matches MACS's PARENT_SESSION_TTL_HOURS default
var CALLER_IDENTITY_ = 'fine-arts';               // the 'who' in our caller ticket — an app, not a user
var CALLER_AUDIENCE_ = 'runner-macs';             // must match verifyCallerTicket_ in runner-macs' Router.js

function authHmacBytes_(msg, secret) {
  return Utilities.computeHmacSha256Signature(msg, secret);
}

/** The secret shared with hcs-custom-forms. Generated there by setupAppHandoffSecret_() and
 *  copied by hand into this project's Script Properties under the same key name — there is no
 *  sync between GAS projects. Throws rather than returning '' so a misconfigured install fails
 *  loudly in the log instead of minting tickets nobody can verify. */
function appHandoffSecret_() {
  var s = PropertiesService.getScriptProperties().getProperty('APP_HANDOFF_SECRET');
  if (!s) throw new Error('APP_HANDOFF_SECRET not set — copy it from hcs-custom-forms\' Script Properties');
  return s;
}

/** This app's OWN session-signing secret. Never shared with anything. */
function authSecret_() {
  var s = PropertiesService.getScriptProperties().getProperty('AUTH_HMAC_SECRET');
  if (!s) throw new Error('AUTH_HMAC_SECRET not set — run bootstrapSecondaryAuth()');
  return s;
}

/**
 * Bump the 'Session Epoch' Settings row to invalidate every outstanding session at once.
 *
 * Read fresh every time, deliberately NOT cached. A cache here would mean tokens kept
 * verifying against the old epoch for the cache's lifetime after a bump — an identity control
 * whose whole documented purpose is instant mass revocation must not honor revoked sessions on
 * a delay. The read it saves is negligible against this form's traffic (roughly one submission
 * per school per year) and the Settings sheet is a handful of rows.
 */
function authEpoch_() {
  ensureSettingExists_('Session Epoch', '1');
  var data = getOrCreateSheet_(SHEETS.SETTINGS).getDataRange().getValues();
  for (var i = 1; i < data.length; i++) {
    if (data[i][0] === 'Session Epoch') return Number(data[i][1]) || 1;
  }
  return 1;
}

/** A fresh 2-minute ticket proving to runner-macs that THIS APP is calling. Minted per
 *  request, so no long-lived bearer credential is ever in flight. */
function mintCallerTicket_() {
  return AppHandoffLogic.mint(CALLER_IDENTITY_, 'app', CALLER_AUDIENCE_, {
    hmacFn: authHmacBytes_, secret: appHandoffSecret_(), nowMs: new Date().getTime()
  });
}

/** Our own session, minted only after runner-macs confirms the code. The school travels
 *  inside the signed payload, so no later call has to trust a school code from the client. */
function mintSchoolSession_(email, schoolCode, schoolName) {
  return TokenLogic.mint(email, {
    hmacFn: authHmacBytes_, secret: authSecret_(), nowMs: new Date().getTime(),
    epoch: authEpoch_(), ttlMs: SCHOOL_SESSION_TTL_MS_,
    claims: { sch: String(schoolName), code: String(schoolCode) }
  });
}

/**
 * The one guard every school-scoped endpoint calls, before doing anything. Returns the
 * verified identity or throws — never returns a partial result, so a caller cannot accidentally
 * proceed on a failed check. The school code comes from here and NOWHERE else: the form's
 * dropdown is UI only, and google.script.run is callable directly with any arguments.
 *
 * This only verifies the token itself (signature, expiry, session epoch) — it does NOT
 * re-resolve the MACS_Schools allowlist on every call. So removing an address from that sheet
 * does not immediately invalidate a session already minted for it: that session stays valid
 * until it expires (up to SCHOOL_SESSION_TTL_MS_, currently 12h) or the 'Session Epoch' Settings
 * row is bumped, which revokes every outstanding session at once. That tradeoff is intentional
 * and must not change; this comment previously overstated the guarantee.
 */
function requireSchoolSession_(token) {
  var r = TokenLogic.verify(token, {
    hmacFn: authHmacBytes_, secret: authSecret_(), nowMs: new Date().getTime(), epoch: authEpoch_()
  });
  if (!r.ok) throw new Error(r.code);
  var claims = r.claims || {};
  if (!claims.sch || !claims.code) throw new Error('AUTH_INVALID');
  return { email: r.email, schoolCode: String(claims.code), schoolName: String(claims.sch) };
}

/**
 * Guard for every admin/maintenance endpoint. Fails closed: Session.getActiveUser() is blank on
 * the public registration deployment ("Execute as: Me"), so these functions are unreachable from
 * the anonymous form even though google.script.run can name any top-level function in the
 * project. Only the separate admin deployment ("Execute as: User accessing the web app", see
 * doGet's comment in Intake.js) yields a real identity for isAuthorizedAdmin_ to check.
 */
function requireAdmin_() {
  var email = String((Session.getActiveUser() && Session.getActiveUser().getEmail()) || '');
  if (!isAuthorizedAdmin_(email)) {
    throw new Error('AUTH_REQUIRED — admin functions need the admin deployment (Execute as: User accessing the web app). See doGet in Intake.js.');
  }
  return email;
}

// Exported for the Node tests (no-op in GAS).

/* ===== Intake.js ===== */
/**
 * Public intake web app. One-time submission per school — once a school
 * has a row in Submissions, the form refuses further submissions and
 * tells them to email the admin for changes.
 */
function doGet(e) {
  var page = e && e.parameter && e.parameter.page;
  if (page === 'admin') {
    var email = Session.getActiveUser().getEmail();
    if (!isAuthorizedAdmin_(email)) {
      return HtmlService.createHtmlOutput(
        '<div style="font-family:sans-serif;max-width:480px;margin:80px auto;text-align:center;color:#333;">' +
        '<h2>Access Denied</h2>' +
        (email
          ? '<p>Your Google account (' + email + ') is not on the admin allowlist. Ask the competition admin to add it under Settings &rarr; Admin Emails.</p>'
          : '<p>Please sign in with an authorized Google account to view this page.</p>') +
        '</div>'
      ).setTitle('MACS Scheduling — Admin');
    }
    return HtmlService.createHtmlOutputFromFile('AdminApp')
      .setTitle('MACS Scheduling — Admin')
      .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
  }
  return HtmlService.createHtmlOutputFromFile('Form')
    .setTitle('MACS Secondary Fine Arts Competition — Registration')
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}

/**
 * Admin page access control. This only works when the request comes
 * through a deployment configured with "Execute as: User accessing the
 * web app" — the public registration form's deployment stays "Execute
 * as: Me" (so schools never need a Google login), which means
 * Session.getActiveUser() returns blank there and this always denies.
 * A separate deployment (see HANDOFF/README) is required for admin
 * access with the right execution settings.
 */
function isAuthorizedAdmin_(email) {
  if (!email) return false;
  ensureSettingExists_('Admin Emails', 'admin@example.edu');
  var sheet = getOrCreateSheet_(SHEETS.SETTINGS);
  var data = sheet.getDataRange().getValues();
  for (var i = 1; i < data.length; i++) {
    if (data[i][0] === 'Admin Emails') {
      var allowed = String(data[i][1] || '').split(',').map(function (s) { return s.trim().toLowerCase(); }).filter(Boolean);
      return allowed.indexOf(email.toLowerCase()) !== -1;
    }
  }
  return false;
}

/**
 * MACS Forms' MACS_Schools sheet tab is the master ROSTER (names only — that sheet also
 * carries auth allowlist emails, none of this app's business). This app's own Schools sheet
 * stays the source of truth for numeric school CODE + display color: those are baked into
 * every entry ID (submitSchoolEntries_) and every historical record, so they must never
 * change once assigned, and MACS_Schools has no such columns to give us anyway. Reconciles
 * by name (case-insensitive): a master name already in the local sheet keeps its existing
 * code/color; a brand-new name gets one provisioned (nextSchoolCode_/nextSchoolColor_) and
 * appended, under a lock so two concurrent first-loads can't double-provision it. A name
 * dropped from MACS_Schools just stops appearing here — its historical rows are untouched.
 * If MACS Forms is unreachable, serves the local sheet as-is (today's behavior).
 * It also tells us, per school, whether an allowlist entry exists (`otp`) — the addresses
 * themselves never cross the bridge.
 */
function getSchoolList() {
  var sheet = getOrCreateSheet_(SHEETS.SCHOOLS);
  var local = readSchoolsSheet_(sheet.getDataRange().getValues());

  var remote = fetchMacsFormsMaster_();
  var master = (remote && remote.schools && remote.schools.length) ? remote.schools : null;
  // No master roster (MACS Forms unreachable) -> serve the local sheet, with otp:false. That
  // makes every school unable to SIGN IN rather than able to submit unverified, which is the
  // right way for an identity check to degrade.
  if (!master) return local.map(function (s) { return { code: s.code, name: s.name, otp: false }; });

  var byNameLower = {};
  local.forEach(function (s) { byNameLower[s.name.trim().toLowerCase()] = s; });

  var newNames = master.map(function (s) { return s.name; })
    .filter(function (name) { return !byNameLower[String(name).trim().toLowerCase()]; });

  if (newNames.length) {
    var lock = LockService.getScriptLock();
    lock.waitLock(10000);
    try {
      // Re-read fresh — another concurrent execution may have appended rows while we waited.
      var fresh = readSchoolsSheet_(sheet.getDataRange().getValues());
      var existingCodes = {}, usedColors = {};
      fresh.forEach(function (s) {
        existingCodes[s.code] = true;
        if (s.colorHex) usedColors[s.colorHex] = true;
        byNameLower[s.name.trim().toLowerCase()] = s;
      });
      var newRows = [];
      newNames.forEach(function (name) {
        var key = String(name).trim().toLowerCase();
        if (byNameLower[key]) return; // provisioned by a concurrent execution while we waited
        var code = nextSchoolCode_(existingCodes);
        existingCodes[code] = true;
        var color = nextSchoolColor_(usedColors);
        usedColors[color] = true;
        newRows.push([code, name, color]);
        byNameLower[key] = { code: code, name: name, colorHex: color };
      });
      if (newRows.length) sheet.getRange(sheet.getLastRow() + 1, 1, newRows.length, 3).setValues(newRows);
    } finally {
      lock.releaseLock();
    }
  }

  return master.map(function (m) {
    var s = byNameLower[String(m.name).trim().toLowerCase()];
    return { code: s.code, name: s.name, otp: !!m.otp };
  });
}

function readSchoolsSheet_(data) {
  var out = [];
  for (var i = 1; i < data.length; i++) {
    if (!data[i][0]) continue;
    out.push({ code: String(data[i][0]), name: String(data[i][1] || ''), colorHex: data[i][2] || '' });
  }
  return out;
}

/** One higher than the current max existing code — codes are baked into every entry ID
 *  (submitSchoolEntries_), so a fresh one must never collide with one already in use,
 *  including ones just reserved earlier in the same provisioning pass. */
function nextSchoolCode_(existingCodes) {
  var max = 999;
  Object.keys(existingCodes).forEach(function (c) { var n = Number(c); if (n > max) max = n; });
  var next = max + 1;
  while (existingCodes[String(next)]) next++;
  return String(next);
}

var SCHOOL_COLOR_PALETTE_ = ['#e74c3c', '#f1c40f', '#2ecc71', '#3498db', '#e67e22', '#9b59b6',
  '#8e44ad', '#1abc9c', '#34495e', '#7f8c8d', '#c0392b', '#16a085', '#2980b9', '#d35400', '#27ae60'];

function nextSchoolColor_(usedColors) {
  for (var i = 0; i < SCHOOL_COLOR_PALETTE_.length; i++) {
    if (!usedColors[SCHOOL_COLOR_PALETTE_[i]]) return SCHOOL_COLOR_PALETTE_[i];
  }
  return '#888888';
}

/** {theme, brand} from MACS Forms, or null if it's unreachable — caller keeps this app's own
 *  hardcoded CSS colors/title in that case (see Form.html's applyMacsBranding_). */
function getBranding() {
  var remote = fetchMacsFormsMaster_();
  return remote ? { theme: remote.theme, brand: remote.brand } : null;
}

var MACS_FORMS_URL_ = 'https://example.invalid/macs-forms/exec';

/** {schools, theme, brand} from MACS Forms' fineArtsConfig endpoint, or null on any failure
 *  (network error, non-200, bad JSON) — callers must treat null as "use local fallback". */
function fetchMacsFormsMaster_() {
  var cache = CacheService.getScriptCache();
  var hit = cache.get('macsFormsMaster');
  if (hit) { try { return JSON.parse(hit); } catch (e) {} }
  try {
    var resp = UrlFetchApp.fetch(MACS_FORMS_URL_ + '?api=fineArtsConfig', { muteHttpExceptions: true });
    if (resp.getResponseCode() !== 200) return null;
    var parsed = JSON.parse(resp.getContentText());
    cache.put('macsFormsMaster', JSON.stringify(parsed), 600);
    return parsed;
  } catch (e) {
    return null;
  }
}

/**
 * Full category config for the registration form, grouped by Section
 * (Bible/Music/Art) and Level (Junior High/Senior High) — drives the
 * JotForm-style sectioned layout instead of a flat category dropdown.
 */
function getCategoryList() {
  var config = readCategoryConfig_();
  return Object.keys(config).map(function (code) {
    var c = config[code];
    return {
      code: c.code, name: c.name, section: c.section || 'Other', level: c.level || '',
      fieldTemplate: c.fieldTemplate || 'music', isGroupRoster: !!c.isGroupRoster,
      maxPerSchool: c.maxPerSchool || 0, judgingSheetName: c.judgingSheetName || ''
    };
  });
}

/**
 * Template definitions the registration form needs client-side: which
 * fields to render for each Field Template key. Group roster is now
 * per-category (see getCategoryList), not per-template.
 */
function getJudgingSheets() {
  var sheet = getOrCreateSheet_(SHEETS.JUDGING_SHEETS);
  var data = sheet.getDataRange().getValues();
  var map = {};
  for (var i = 1; i < data.length; i++) {
    if (!data[i][0]) continue;
    map[data[i][0]] = data[i][1] || '';
  }
  return map;
}

/**
 * The two payment PDF links shown on the public form's Payment tab (MACS
 * member schools and non-MACS schools use different fee sheets) — added
 * to Settings after this project's Settings sheet was already
 * bootstrapped, so ensureSettingExists_ backfills the rows on read
 * instead of relying on Bootstrap.js (which only seeds a completely
 * empty sheet).
 */
function getPaymentInfo() {
  ensureSettingExists_('Payment PDF Link (MACS Schools)', '');
  ensureSettingExists_('Payment PDF Link (Non-MACS Schools)', '');
  var sheet = getOrCreateSheet_(SHEETS.SETTINGS);
  var data = sheet.getDataRange().getValues();
  var out = { macsPaymentPdfLink: '', nonMacsPaymentPdfLink: '' };
  for (var i = 1; i < data.length; i++) {
    if (data[i][0] === 'Payment PDF Link (MACS Schools)') out.macsPaymentPdfLink = data[i][1] || '';
    if (data[i][0] === 'Payment PDF Link (Non-MACS Schools)') out.nonMacsPaymentPdfLink = data[i][1] || '';
  }
  return out;
}

function getFieldTemplateDefs() {
  var templates = readFieldTemplates_();
  var out = {};
  Object.keys(templates).forEach(function (key) {
    out[key] = { fields: templates[key].fields };
  });
  return out;
}

function schoolAlreadySubmitted_(schoolCode) {
  var sheet = getOrCreateSheet_(SHEETS.SUBMISSIONS);
  var data = sheet.getDataRange().getValues();
  for (var i = 1; i < data.length; i++) {
    if (String(data[i][2]) === String(schoolCode)) return true;
  }
  return false;
}

/** Takes a session token, not a school code — see requireSchoolSession_ in Auth.js for why
 *  a client-supplied code can't be trusted here. */
function checkSchoolStatus(token) {
  var session = requireSchoolSession_(token);
  return { alreadySubmitted: schoolAlreadySubmitted_(session.schoolCode) };
}

/**
 * Public entry point. Requires a verified school session (see Auth.js): the school comes from
 * the token, never from the caller. Form.html's dropdown is UI only — google.script.run is
 * callable directly with any arguments, so before this guard anyone with the URL could submit
 * as any school.
 */
function submitSchoolEntries(token, entries, contact) {
  var session = requireSchoolSession_(token);
  return submitSchoolEntries_(session.schoolCode, session.schoolName, entries, contact);
}

/**
 * The actual write. Trailing-underscore private: it takes a school code on trust, so the ONLY
 * legitimate callers are submitSchoolEntries (which just verified a session) and TestData.js's
 * server-side seeding, which runs from the editor as the owner and has no session to present.
 * Never expose this to the client.
 *
 * entries: array of {categoryCode, studentName, title, authorComposer,
 *   accompanist, conductor}
 * Auto-populates each entry's "Other Entry IDs" by matching studentName
 * (case-insensitive, trimmed) against every other entry in the SAME
 * submission — this replaces the old free-text "list your other events"
 * field entirely.
 */
function submitSchoolEntries_(schoolCode, schoolName, entries, contact) {
  if (schoolAlreadySubmitted_(schoolCode)) {
    throw new Error('This school has already submitted entries. To make a change, please email the competition admin directly — the form does not allow a second submission.');
  }
  if (!entries || entries.length === 0) {
    throw new Error('No entries were provided.');
  }
  if (!contact || !contact.firstName || !contact.lastName || !contact.phone || !contact.email) {
    throw new Error('Contact person, phone, and email are required on the Register tab.');
  }

  var config = readCategoryConfig_();
  var countsByCategory = {};
  entries.forEach(function (e) { countsByCategory[e.categoryCode] = (countsByCategory[e.categoryCode] || 0) + 1; });
  var violations = Object.keys(countsByCategory).filter(function (code) {
    var cfg = config[code];
    return cfg && cfg.maxPerSchool > 0 && countsByCategory[code] > cfg.maxPerSchool;
  });
  if (violations.length > 0) {
    var msg = violations.map(function (code) {
      var cfg = config[code];
      return cfg.name + ' (' + code + '): ' + countsByCategory[code] + ' entered, max ' + cfg.maxPerSchool + ' per school';
    }).join('; ');
    throw new Error('Too many entries in: ' + msg + '. Remove some entries before submitting.');
  }

  var timestamp = new Date();
  var regSheet = getOrCreateSheet_(SHEETS.REGISTRATIONS);
  regSheet.appendRow([timestamp, schoolCode, schoolName, contact.firstName, contact.lastName, contact.phone, contact.email]);

  var sheet = getOrCreateSheet_(SHEETS.SUBMISSIONS);
  ensureHeaderRow_(sheet, SUBMISSIONS_HEADERS);
  var seqByCategory = {};
  var rows = [];
  // normalized name -> [entryId,...] — an entry is indexed under its OWN
  // studentName AND under every one of its roster members' names, so a
  // roster member who also has their own solo entry (or is on another
  // group's roster) shows up in "Other Entry IDs (auto)" on BOTH sides,
  // matching what the scheduler's conflict graph already links.
  var entryIdByStudentKey = {};

  function keysForEntry(entry) {
    var keys = [normalizeName_(entry.studentName)];
    (entry.roster || []).forEach(function (r) {
      if (r && r.studentName) keys.push(normalizeName_(r.studentName));
    });
    return keys;
  }

  entries.forEach(function (entry) {
    var code = entry.categoryCode;
    seqByCategory[code] = (seqByCategory[code] || 0) + 1;
    var entryId = code + (Number(schoolCode) + seqByCategory[code]);
    entry._entryId = entryId;
    keysForEntry(entry).forEach(function (key) {
      if (!entryIdByStudentKey[key]) entryIdByStudentKey[key] = [];
      entryIdByStudentKey[key].push(entryId);
    });
  });

  entries.forEach(function (entry) {
    var otherSet = {};
    keysForEntry(entry).forEach(function (key) {
      entryIdByStudentKey[key].forEach(function (id) { if (id !== entry._entryId) otherSet[id] = true; });
    });
    var others = Object.keys(otherSet);
    rows.push([
      entry._entryId,
      timestamp,
      schoolCode,
      schoolName,
      entry.categoryCode,
      entry.categoryCode.charAt(0) === 'J' ? 'Junior High' : 'Senior High',
      entry._entryId,
      entry.studentName,
      entry.title || '',
      entry.authorComposer || '',
      entry.accompanist || '',
      entry.conductor || '',
      entry.attachment || '',
      others.join(', '),
      JSON.stringify(entry.roster || [])
    ]);
  });

  sheet.getRange(sheet.getLastRow() + 1, 1, rows.length, SUBMISSIONS_HEADERS.length).setValues(rows);
  return { success: true, count: rows.length };
}

/**
 * Uploads a PDF (sent as base64 from the browser) to a dedicated Drive
 * folder and returns a shareable view link — used by 'file' type fields
 * (e.g. Art & Projects PDF submissions).
 */
/** The Drive subfolder is chosen by the VERIFIED school name — otherwise a caller could write
 *  a file into another school's folder just by passing its name. */
function uploadEntryFile(base64Data, filename, mimeType, token) {
  var session = requireSchoolSession_(token);
  return validateAndUploadPdf_(base64Data, filename, mimeType, getOrCreateSchoolUploadsFolder_(session.schoolName));
}

function getOrCreateSchoolUploadsFolder_(schoolName) {
  var root = getOrCreateDriveFolder_('MACS Art Uploads');
  var name = String(schoolName || 'Unknown School').trim();
  var subFolders = root.getFoldersByName(name);
  return subFolders.hasNext() ? subFolders.next() : root.createFolder(name);
}

function normalizeName_(name) {
  return String(name || '').trim().toLowerCase().replace(/\s+/g, ' ');
}

/* ===== MacsBridge.js ===== */
/**
 * MacsBridge.js — the only file in this project that talks to MACS Forms.
 *
 * MACS's _System!MACS_Schools tab is the single master allowlist of which email addresses may
 * register on behalf of which school. This is a different GAS project with a different Drive
 * owner, so we can't read that sheet — and we deliberately don't want a local mirror of it to
 * drift. Instead runner-macs exposes its own macsRequestOtp/macsVerifyOtp over two
 * authenticated POST endpoints, and this file proxies to them.
 *
 * What we send: which app is calling (a 2-minute AppHandoffLogic ticket, see Auth.js), plus
 * the school, email, and code the visitor typed. What we trust back: only {ok, school, email}.
 * MACS's own session token is never returned to us and could not be verified here anyway, so
 * verifySchoolCode mints OUR session instead — the same thing PTC Scheduling's ssoLogin does.
 */

/** Post a signed request to runner-macs. Returns the parsed JSON, or a MACS_UNREACHABLE
 *  envelope on ANY failure (no secret, network error, non-200, unparseable body). Fails
 *  closed: sign-in must never degrade into the old unverified dropdown. Note the contrast
 *  with fetchMacsFormsMaster_ in Intake.js, which fails OPEN on purpose — that one fetches
 *  cosmetic config (school names, theme), this one is the identity check. */
function macsFormsPost_(api, fields) {
  var payload = { api: api };
  try {
    payload.caller = mintCallerTicket_();
  } catch (err) {
    Logger.log('[macsFormsPost_] cannot mint caller ticket: ' + (err && err.message || err));
    return { ok: false, code: 'MACS_UNREACHABLE' };
  }
  Object.keys(fields).forEach(function (k) { payload[k] = fields[k]; });

  var resp;
  try {
    resp = UrlFetchApp.fetch(MACS_FORMS_URL_, { method: 'post', payload: payload, muteHttpExceptions: true });
  } catch (err) {
    Logger.log('[macsFormsPost_] ' + api + ' fetch threw: ' + (err && err.message || err));
    return { ok: false, code: 'MACS_UNREACHABLE' };
  }
  if (resp.getResponseCode() !== 200) {
    Logger.log('[macsFormsPost_] ' + api + ' HTTP ' + resp.getResponseCode());
    return { ok: false, code: 'MACS_UNREACHABLE' };
  }
  try {
    return JSON.parse(resp.getContentText());
  } catch (err) {
    Logger.log('[macsFormsPost_] ' + api + ' unparseable response');
    return { ok: false, code: 'MACS_UNREACHABLE' };
  }
}

var SIGNIN_UNAVAILABLE_MSG_ = 'Sign-in is temporarily unavailable. Please try again in a few minutes, or contact the competition admin.';
var SCHOOL_NOT_CONFIGURED_MSG_ = 'This school isn\'t set up to submit yet — contact the competition admin to get your email added.';

/**
 * { status: 'OK' | 'NOT_CONFIGURED' | 'UNKNOWN_SCHOOL', name } for a school name against the
 * master roster. `name` is the roster's OWN spelling of the matched school (undefined when
 * status is UNKNOWN_SCHOOL) — callers must send that canonical spelling on to MACS Forms
 * instead of whatever spelling arrived from the client, because macsRequestOtp/macsVerifyOtp
 * match by exact string equality against the master roster. getSchoolList() reconciles by name
 * case-insensitively but keeps the LOCAL Schools sheet's spelling, so a hand-typed local row
 * that differs from the master's spelling in case or surrounding whitespace would otherwise
 * silently fail to match on the far side — the anti-enumeration design means no error surfaces
 * anywhere when that happens.
 *
 * Stricter than MACS Forms' own gate, deliberately: there, a school with no allowlist entry
 * is open and needs no code. Here a submission must provably come from the school it claims,
 * so no entry means no submission. Pure, so tests/school_gate.test.js can pin it.
 */
function schoolSignInStatus_(remoteSchools, schoolName) {
  var key = String(schoolName || '').trim().toLowerCase();
  if (!key) return { status: 'UNKNOWN_SCHOOL' };
  var match = (remoteSchools || []).filter(function (s) {
    return String(s && s.name || '').trim().toLowerCase() === key;
  })[0];
  if (!match) return { status: 'UNKNOWN_SCHOOL' };
  return { status: match.otp ? 'OK' : 'NOT_CONFIGURED', name: match.name };
}

/** The local school CODE for a master-roster NAME. Same trimmed/case-insensitive matching
 *  getSchoolList() reconciles by. Returns '' on a miss — never a wrong-but-plausible code,
 *  since codes are baked into every entry ID and historical record. Pure. */
function matchSchoolCode_(localSchools, schoolName) {
  var key = String(schoolName || '').trim().toLowerCase();
  if (!key) return '';
  var match = (localSchools || []).filter(function (s) {
    return String(s && s.name || '').trim().toLowerCase() === key;
  })[0];
  return match ? String(match.code) : '';
}

/** getSchoolList() provisions a code for any brand-new master name, so by the time a school
 *  can be picked in the gate it always has one. */
function resolveSchoolCodeByName_(schoolName) {
  return matchSchoolCode_(getSchoolList(), schoolName);
}

/** One ops mail per school per hour — an anonymous form must not be usable to flood the
 *  inbox. Same throttle shape as runner-macs' getMacsSchools_ notify. */
function notifyUnconfiguredSchool_(schoolName) {
  try {
    var cache = CacheService.getScriptCache();
    var key = 'unconfiguredNotified:' + String(schoolName).trim().toLowerCase();
    if (cache.get(key)) return;
    cache.put(key, '1', 3600);
    MailApp.sendEmail(getAdminNotifyAddress_(),
      'MACS Fine Arts: "' + schoolName + '" cannot sign in',
      'Someone at "' + schoolName + '" tried to sign in to the Fine Arts registration form, but that ' +
      'school has no allowlist entry in MACS\'s _System spreadsheet, so it cannot submit.\n\n' +
      'Fix: add a row to the MACS_Schools tab of _System ' +
      '(DEMO_DRIVE_ID) — SchoolName | Entry | Notes, where Entry is ' +
      'the address that should be allowed to register for them, or a bare "@theirdomain.org" to ' +
      'admit any address at their domain.\n\nRun bootstrapSecondaryAuth() to list every school ' +
      'still missing an entry.');
  } catch (err) {
    Logger.log('[notifyUnconfiguredSchool_] notify failed for ' + schoolName + ': ' + (err && err.message || err));
  }
}

/** First address on the Admin Emails setting — the same allowlist the admin page uses. */
function getAdminNotifyAddress_() {
  ensureSettingExists_('Admin Emails', 'admin@example.edu');
  var data = getOrCreateSheet_(SHEETS.SETTINGS).getDataRange().getValues();
  for (var i = 1; i < data.length; i++) {
    if (data[i][0] === 'Admin Emails') {
      var first = String(data[i][1] || '').split(',')[0].trim();
      if (first) return first;
    }
  }
  return 'admin@example.edu';
}

// ---------- public endpoints (called from Form.html) ----------

/**
 * Step 1 of sign-in: mail a 6-digit code to `email` if it's on `schoolName`'s allowlist.
 * The success response is deliberately identical whether or not the address was allowlisted —
 * that's macsRequestOtp's anti-enumeration behavior, kept intact so this form can't be used to
 * probe which addresses are on file for a school.
 */
function requestSchoolCode(schoolName, email) {
  var remote = fetchMacsFormsMaster_();
  if (!remote || !remote.schools) return { ok: false, code: 'MACS_UNREACHABLE', msg: SIGNIN_UNAVAILABLE_MSG_ };

  var gate = schoolSignInStatus_(remote.schools, schoolName);
  if (gate.status === 'NOT_CONFIGURED') {
    notifyUnconfiguredSchool_(schoolName);
    return { ok: false, code: 'SCHOOL_NOT_CONFIGURED', msg: SCHOOL_NOT_CONFIGURED_MSG_ };
  }
  if (gate.status === 'UNKNOWN_SCHOOL') {
    return { ok: false, code: 'UNKNOWN_SCHOOL', msg: 'Please choose your school from the list again.' };
  }

  // Send the master's OWN spelling of the name, not whatever the client sent — MACS Forms
  // matches by exact string equality, so a local spelling that merely case/whitespace-differs
  // from the master's would otherwise silently fail to match on the far side.
  var res = macsFormsPost_('macsRequestOtp', { school: gate.name, email: email });
  if (res.code === 'MACS_UNREACHABLE' || res.code === 'CALLER_INVALID' || res.code === 'SERVER_ERROR') {
    return { ok: false, code: res.code, msg: SIGNIN_UNAVAILABLE_MSG_ };
  }
  return res;
}

/**
 * Step 2 of sign-in: check the code, then mint OUR session. The returned token is what every
 * later school-scoped call passes; the school code inside it is resolved here, server-side,
 * from this project's own Schools sheet, and is never accepted from the browser again.
 */
function verifySchoolCode(schoolName, email, code) {
  // Same canonicalization as requestSchoolCode: send the master's own spelling on to MACS
  // Forms' exact-match check, falling back to the raw input only when the roster is
  // unreachable or the name genuinely doesn't match anything (macsVerifyOtp will then reject
  // it itself, same as before this fix).
  var remote = fetchMacsFormsMaster_();
  var gate = (remote && remote.schools) ? schoolSignInStatus_(remote.schools, schoolName) : { status: 'UNKNOWN_SCHOOL' };
  var canonicalName = gate.name || schoolName;

  var res = macsFormsPost_('macsVerifyOtp', { school: canonicalName, email: email, code: code });
  if (res.code === 'MACS_UNREACHABLE' || res.code === 'CALLER_INVALID' || res.code === 'SERVER_ERROR') {
    return { ok: false, code: res.code, msg: SIGNIN_UNAVAILABLE_MSG_ };
  }
  if (!res.ok) return res;

  var schoolCode = resolveSchoolCodeByName_(res.school);
  if (!schoolCode) {
    Logger.log('[verifySchoolCode] verified "' + res.school + '" but no local Schools row resolved');
    return { ok: false, code: 'SCHOOL_NOT_IN_LOCAL_LIST', msg: SIGNIN_UNAVAILABLE_MSG_ };
  }
  return {
    ok: true,
    token: mintSchoolSession_(res.email, schoolCode, res.school),
    schoolCode: schoolCode,
    schoolName: res.school,
    email: res.email
  };
}

// Exported for the Node tests (no-op in GAS) — the two pure matchers only.

/**
 * Run this from the Apps Script editor when sign-in reports "temporarily unavailable".
 * That message is deliberately generic for visitors, so it can't say WHICH of several causes
 * fired; this prints the answer instead of making you read the Executions log.
 *
 * The round-trip probe is side-effect free: it POSTs macsVerifyOtp with a junk code, so it never
 * sends mail and never mints a session. What matters is which failure comes back —
 * CALLER_INVALID means the two projects' APP_HANDOFF_SECRET values disagree, while CODE_EXPIRED
 * means the ticket was ACCEPTED and the whole bridge works (there's simply no pending code to
 * check, which is the expected answer for a code nobody requested).
 */
function diagnoseSignIn() {
  requireAdmin_();
  var out = [];
  var props = PropertiesService.getScriptProperties();

  var handoff = props.getProperty('APP_HANDOFF_SECRET');
  out.push('APP_HANDOFF_SECRET: ' + (handoff
    ? 'set (' + String(handoff).length + ' chars)'
    : 'MISSING -> this alone breaks sign-in. Copy it from hcs-custom-forms\' Script Properties, same key name.'));
  out.push('AUTH_HMAC_SECRET:   ' + (props.getProperty('AUTH_HMAC_SECRET')
    ? 'set' : 'MISSING -> run bootstrapSecondaryAuth()'));

  try {
    mintCallerTicket_();
    out.push('mint caller ticket:  OK');
  } catch (err) {
    out.push('mint caller ticket:  FAILED -> ' + (err && err.message || err));
    Logger.log(out.join('\n'));
    return out.join('\n');
  }

  var cfg = fetchMacsFormsMaster_();
  out.push('GET fineArtsConfig:  ' + (cfg && cfg.schools
    ? 'OK, ' + cfg.schools.length + ' school(s): ' + cfg.schools.map(function (s) {
        return s.name + (s.otp ? '' : ' [NO ALLOWLIST ENTRY - cannot submit]');
      }).join(', ')
    : 'FAILED (MACS Forms unreachable, or returned no schools)'));

  var probe = macsFormsPost_('macsVerifyOtp', { school: '__diagnostic__', email: 'probe@example.invalid', code: '000000' });
  var code = probe && probe.code;
  if (code === 'CODE_EXPIRED' || code === 'CODE_INVALID') {
    out.push('POST round trip:     OK - caller ticket accepted, bridge healthy (got ' + code + ', expected for a code nobody requested)');
  } else if (code === 'CALLER_INVALID') {
    out.push('POST round trip:     CALLER_INVALID -> runner-macs rejected our caller ticket.\n' +
      '  Its verifier returns the same answer whether the secret is MISSING or DIFFERENT, and missing is\n' +
      '  the usual cause: APP_HANDOFF_SECRET must live in the Script Properties of the runner-macs\n' +
      '  SCRIPT PROJECT ITSELF (id DEMO_DRIVE_ID), not the\n' +
      '  hcs-custom-forms root project (DEMO_DRIVE_ID) where\n' +
      '  setupAppHandoffSecret_() is normally run. They are separate projects with separate properties.\n' +
      '  Set the SAME value in both, then re-run this check.');
  } else if (code === 'MACS_UNREACHABLE') {
    out.push('POST round trip:     MACS_UNREACHABLE -> could not POST to runner-macs at all. Check MACS_FORMS_URL_ and that its deployment is live.');
  } else {
    out.push('POST round trip:     unexpected response ' + JSON.stringify(probe));
  }

  var report = out.join('\n');
  Logger.log(report);
  return report;
}

/* ===== AdminBackend.js ===== */
/**
 * Server-side functions backing the Admin web app (AdminApp.html) —
 * lets an admin manage Category Config, Building Map, Settings, Judges,
 * and Schools without opening the raw spreadsheet.
 */

function admin_getCategoryConfig() {
  requireAdmin_();
  var sheet = getOrCreateSheet_(SHEETS.CATEGORY_CONFIG);
  var data = sheet.getDataRange().getValues();
  var rows = [];
  for (var i = 1; i < data.length; i++) {
    if (!data[i][0]) continue;
    rows.push({
      code: data[i][0], name: data[i][1], section: data[i][2], level: data[i][3],
      room: data[i][4], durationSlots: data[i][5], fieldTemplate: data[i][6] || 'music',
      isGroupRoster: !!data[i][7], maxPerSchool: data[i][8], roomRequired: !!data[i][9],
      judgingSheetName: data[i][10] || ''
    });
  }
  return rows;
}

function admin_saveCategoryConfig(rows) {
  requireAdmin_();
  var sheet = getOrCreateSheet_(SHEETS.CATEGORY_CONFIG);
  setHeaderRow_(sheet, DEFAULT_CATEGORY_CONFIG_HEADERS);
  var values = rows.map(function (r) {
    return [r.code, r.name, r.section, r.level, r.room, Number(r.durationSlots) || 1, r.fieldTemplate || 'music',
      !!r.isGroupRoster, Number(r.maxPerSchool) || 0, !!r.roomRequired, r.judgingSheetName || ''];
  });
  if (values.length > 0) sheet.getRange(2, 1, values.length, values[0].length).setValues(values);
  logAdminEdit_('Category Config saved (' + values.length + ' rows)');
  return { success: true };
}

function admin_getFieldTemplates() {
  requireAdmin_();
  var templates = readFieldTemplates_();
  return Object.keys(templates).map(function (key) {
    var t = templates[key];
    return {
      key: t.key, label: t.label, nameLabel: t.nameLabel, fieldsJson: JSON.stringify(t.fields),
      scheduled: t.scheduled
    };
  });
}

function admin_saveFieldTemplates(rows) {
  requireAdmin_();
  var sheet = getOrCreateSheet_(SHEETS.FIELD_TEMPLATES);
  setHeaderRow_(sheet, FIELD_TEMPLATES_HEADERS);
  var values = rows.map(function (r) {
    var fields = [];
    try { fields = JSON.parse(r.fieldsJson || '[]'); } catch (e) { fields = []; }
    return [r.key, r.label, r.nameLabel || 'Student / Group Name', JSON.stringify(fields), !!r.scheduled];
  });
  if (values.length > 0) sheet.getRange(2, 1, values.length, values[0].length).setValues(values);
  logAdminEdit_('Field Templates saved (' + values.length + ' rows)');
  return { success: true };
}

function admin_getBuildingMap() {
  requireAdmin_();
  var sheet = getOrCreateSheet_('Building Map');
  var data = sheet.getDataRange().getValues();
  var rows = [];
  for (var i = 1; i < data.length; i++) {
    if (!data[i][0]) continue;
    rows.push({ room: data[i][0], building: data[i][1] });
  }
  return rows;
}

function admin_saveBuildingMap(rows) {
  requireAdmin_();
  var sheet = getOrCreateSheet_('Building Map');
  setHeaderRow_(sheet, ['Room', 'Building']);
  var values = rows.map(function (r) { return [r.room, r.building]; });
  if (values.length > 0) sheet.getRange(2, 1, values.length, 2).setValues(values);
  logAdminEdit_('Building Map saved (' + values.length + ' rows)');
  return { success: true };
}

function admin_getJudgingSheets() {
  requireAdmin_();
  var sheet = getOrCreateSheet_(SHEETS.JUDGING_SHEETS);
  var data = sheet.getDataRange().getValues();
  var rows = [];
  for (var i = 1; i < data.length; i++) {
    if (!data[i][0]) continue;
    rows.push({ name: data[i][0], url: data[i][1] || '' });
  }
  return rows;
}

/**
 * A pasted Drive link comes in all kinds of shapes depending on where the
 * admin copied it from (a folder listing's address bar, the "Share"
 * dialog, an /open?id= link, etc.) — several of those open the file's
 * *location* in Drive instead of previewing the file itself. Rewriting
 * to the canonical /file/d/<id>/view form always opens an inline preview
 * as long as sharing is "Anyone with the link." Non-Drive URLs (or a
 * link with no recognizable file ID) pass through unchanged.
 */
function normalizeDriveViewUrl_(url) {
  url = (url || '').trim();
  if (!url) return url;
  var match = url.match(/\/file\/d\/([-\w]{20,})/) || url.match(/[?&]id=([-\w]{20,})/);
  if (!match) return url;
  return 'https://drive.google.com/file/d/' + match[1] + '/view';
}

function admin_saveJudgingSheets(rows) {
  requireAdmin_();
  var sheet = getOrCreateSheet_(SHEETS.JUDGING_SHEETS);
  setHeaderRow_(sheet, JUDGING_SHEETS_HEADERS);
  var values = rows.map(function (r) { return [r.name, normalizeDriveViewUrl_(r.url)]; });
  if (values.length > 0) sheet.getRange(2, 1, values.length, 2).setValues(values);
  logAdminEdit_('Judging Sheets saved (' + values.length + ' rows)');
  return { success: true };
}

/**
 * Lets an admin upload a judging sheet as a PDF instead of pasting a link
 * — the returned URL just gets typed into the same "url" field as a
 * pasted link would, so nothing downstream needs to know the difference.
 */
function admin_uploadJudgingSheetFile(base64Data, filename, mimeType) {
  requireAdmin_();
  return validateAndUploadPdf_(base64Data, filename, mimeType, getOrCreateDriveFolder_('MACS Judging Sheets'));
}

function admin_getSettings() {
  requireAdmin_();
  ensureSettingExists_('Competition Year', '');
  ensureSettingExists_('Admin Emails', 'admin@example.edu');
  ensureSettingExists_('Payment PDF Link (MACS Schools)', '');
  ensureSettingExists_('Payment PDF Link (Non-MACS Schools)', '');
  var sheet = getOrCreateSheet_(SHEETS.SETTINGS);
  var data = sheet.getDataRange().getValues();
  var rows = [];
  for (var i = 1; i < data.length; i++) {
    if (!data[i][0]) continue;
    rows.push({ key: data[i][0], value: timeOfDayToString_(data[i][1]) });
  }
  return rows;
}

function admin_saveSettings(rows) {
  requireAdmin_();
  var sheet = getOrCreateSheet_(SHEETS.SETTINGS);
  setHeaderRow_(sheet, ['Setting', 'Value']);
  var values = rows.map(function (r) { return [r.key, r.value]; });
  if (values.length > 0) sheet.getRange(2, 1, values.length, 2).setValues(values);
  logAdminEdit_('Settings saved (' + values.length + ' rows)');
  return { success: true };
}

function admin_getJudges() {
  requireAdmin_();
  var sheet = getOrCreateSheet_(SHEETS.JUDGES);
  var data = sheet.getDataRange().getValues();
  var rows = [];
  for (var i = 1; i < data.length; i++) {
    if (!data[i][0]) continue;
    rows.push({ judgeName: data[i][0], categoryCode: data[i][1], notes: data[i][2] || '' });
  }
  return rows;
}

function admin_saveJudges(rows) {
  requireAdmin_();
  var sheet = getOrCreateSheet_(SHEETS.JUDGES);
  setHeaderRow_(sheet, JUDGES_HEADERS);
  var values = rows.map(function (r) { return [r.judgeName, r.categoryCode, r.notes || '']; });
  if (values.length > 0) sheet.getRange(2, 1, values.length, 3).setValues(values);
  logAdminEdit_('Judges saved (' + values.length + ' rows)');
  return { success: true };
}

function admin_getSchools() {
  requireAdmin_();
  var sheet = getOrCreateSheet_(SHEETS.SCHOOLS);
  var data = sheet.getDataRange().getValues();
  var rows = [];
  for (var i = 1; i < data.length; i++) {
    if (!data[i][0]) continue;
    rows.push({ code: data[i][0], name: data[i][1], colorHex: data[i][2] || '#888888' });
  }
  return rows;
}

function admin_saveSchools(rows) {
  requireAdmin_();
  var sheet = getOrCreateSheet_(SHEETS.SCHOOLS);
  setHeaderRow_(sheet, SCHOOLS_HEADERS);
  var values = rows.map(function (r) { return [r.code, r.name, r.colorHex]; });
  if (values.length > 0) sheet.getRange(2, 1, values.length, 3).setValues(values);
  logAdminEdit_('Schools saved (' + values.length + ' rows)');
  return { success: true };
}

/**
 * Admin-only view of Submissions with the ability to edit or delete a
 * single row — the school-facing form is one-time/read-only, so any
 * correction a school emails in gets applied here instead.
 */
function admin_getRegistrations() {
  requireAdmin_();
  var sheet = getOrCreateSheet_(SHEETS.REGISTRATIONS);
  var data = sheet.getDataRange().getValues();
  var out = [];
  for (var i = 1; i < data.length; i++) {
    if (!data[i][1]) continue;
    out.push({
      timestamp: timestampToString_(data[i][0]), schoolCode: data[i][1], schoolName: data[i][2],
      contactFirst: data[i][3], contactLast: data[i][4], phone: data[i][5], email: data[i][6]
    });
  }
  return out;
}

function admin_getSubmissions() {
  requireAdmin_();
  return readSubmissions_();
}

function admin_updateSubmissionEntry(entryId, updatedFields) {
  requireAdmin_();
  var sheet = getOrCreateSheet_(SHEETS.SUBMISSIONS);
  var data = sheet.getDataRange().getValues();
  for (var i = 1; i < data.length; i++) {
    if (data[i][0] === entryId) {
      SUBMISSIONS_HEADERS.forEach(function (h, idx) {
        if (updatedFields.hasOwnProperty(h)) sheet.getRange(i + 1, idx + 1).setValue(updatedFields[h]);
      });
      logAdminEdit_('Updated entry ' + entryId);
      return { success: true };
    }
  }
  throw new Error('Entry ID not found: ' + entryId);
}

function admin_deleteSubmissionEntry(entryId) {
  requireAdmin_();
  var sheet = getOrCreateSheet_(SHEETS.SUBMISSIONS);
  var data = sheet.getDataRange().getValues();
  for (var i = 1; i < data.length; i++) {
    if (data[i][0] === entryId) {
      sheet.deleteRow(i + 1);
      logAdminEdit_('Deleted entry ' + entryId);
      return { success: true };
    }
  }
  throw new Error('Entry ID not found: ' + entryId);
}

function logAdminEdit_(description) {
  var sheet = getOrCreateSheet_(SHEETS.ADMIN_EDITS_LOG);
  var user = Session.getActiveUser().getEmail() || 'unknown';
  sheet.appendRow([new Date(), user, '', description]);
}

function admin_runSeedHistoricalTestData() { requireAdmin_(); return seedHistoricalTestData(); }
function admin_runClearTestData() { requireAdmin_(); return clearTestData_(); }
function admin_resetForNextYear(archiveYearLabel) { requireAdmin_(); return resetForNextYear_(archiveYearLabel); }

/* ===== MasterList.js ===== */
/**
 * Rebuilds the Master sheet (all entries) and List of Categories counts
 * sheet from Submissions. Safe to re-run any time — fully regenerates
 * both from scratch, since Submissions is the source of truth.
 */
function generateMasterList() {
  requireAdmin_();
  var entries = readSubmissions_();

  var master = getOrCreateSheet_(SHEETS.MASTER);
  setHeaderRow_(master, SUBMISSIONS_HEADERS);
  if (entries.length > 0) {
    var rows = entries.map(function (e) { return SUBMISSIONS_HEADERS.map(function (h) { return e[h]; }); });
    master.getRange(2, 1, rows.length, SUBMISSIONS_HEADERS.length).setValues(rows);
  }

  generateCategoryCounts_(entries);
  safeAlert_('Master List regenerated: ' + entries.length + ' entries.');
}

/**
 * Returns array of entry objects keyed by SUBMISSIONS_HEADERS, read from
 * the Submissions sheet.
 */
function readSubmissions_() {
  var sheet = getOrCreateSheet_(SHEETS.SUBMISSIONS);
  var data = sheet.getDataRange().getValues();
  var out = [];
  for (var i = 1; i < data.length; i++) {
    if (!data[i][0]) continue;
    var entry = {};
    SUBMISSIONS_HEADERS.forEach(function (h, idx) {
      entry[h] = h === 'Timestamp' ? timestampToString_(data[i][idx]) : data[i][idx];
    });
    out.push(entry);
  }
  return out;
}

/**
 * Field Templates are the source of truth for a category's entry fields,
 * whether it needs a roster, and whether it's scheduled at all — Category
 * Config just references a template by key.
 */
function readFieldTemplates_() {
  var sheet = getOrCreateSheet_(SHEETS.FIELD_TEMPLATES);
  var data = sheet.getDataRange().getValues();
  var byKey = {};
  if (data.length === 0) return byKey;

  // Older sheets (from before "Name Label" was added, or from before
  // "Is Group Roster" was removed) have different column meanings at the
  // same index. Detect by header text so existing rows a school already
  // customized keep showing up instead of silently reading as blank.
  var header = data[0] || [];
  var fieldsJsonCol = 3, scheduledCol = 4, nameLabelCol = 2, hasNameLabel = true;
  if (header[2] !== 'Name Label') {
    // Old layout: Key, Label, Fields JSON, Is Group Roster, Scheduled.
    hasNameLabel = false;
    fieldsJsonCol = 2;
    scheduledCol = 4;
  }

  for (var i = 1; i < data.length; i++) {
    if (!data[i][0]) continue;
    var fields = [];
    try { fields = JSON.parse(data[i][fieldsJsonCol] || '[]'); } catch (e) { fields = []; }
    byKey[data[i][0]] = {
      key: data[i][0],
      label: data[i][1],
      nameLabel: (hasNameLabel && data[i][nameLabelCol]) || 'Student / Group Name',
      fields: fields,
      scheduled: data[i][scheduledCol] === true || data[i][scheduledCol] === 'TRUE'
    };
  }
  return byKey;
}

function readCategoryConfig_() {
  var sheet = getOrCreateSheet_(SHEETS.CATEGORY_CONFIG);
  var data = sheet.getDataRange().getValues();
  var templates = readFieldTemplates_();
  var byCode = {};
  for (var i = 1; i < data.length; i++) {
    if (!data[i][0]) continue;
    var templateKey = data[i][6] || 'music';
    var template = templates[templateKey];
    byCode[data[i][0]] = {
      code: data[i][0],
      name: data[i][1],
      section: data[i][2],
      level: data[i][3],
      room: data[i][4],
      durationSlots: Number(data[i][5]) || 1,
      fieldTemplate: templateKey,
      scheduled: template ? template.scheduled : true,
      isGroupRoster: data[i][7] === true || data[i][7] === 'TRUE',
      maxPerSchool: Number(data[i][8]) || 0,
      roomRequired: data[i][9] === true || data[i][9] === 'TRUE',
      judgingSheetName: data[i][10] || ''
    };
  }
  return byCode;
}

function generateCategoryCounts_(entries) {
  var config = readCategoryConfig_();
  var counts = {}; // code -> {jh: n, sh: n}
  Object.keys(config).forEach(function (code) { counts[code] = { jh: 0, sh: 0 }; });

  entries.forEach(function (e) {
    var code = e['Category Code'];
    if (!counts[code]) counts[code] = { jh: 0, sh: 0 };
    if (e['Level'] === 'Junior High') counts[code].jh++;
    else counts[code].sh++;
  });

  var sheet = getOrCreateSheet_(SHEETS.CATEGORY_COUNTS);
  setHeaderRow_(sheet, ['Category Code', 'Category Name', 'Junior High Count', 'Senior High Count', 'Total']);
  var rows = Object.keys(counts).sort().map(function (code) {
    var name = config[code] ? config[code].name : '';
    var jh = counts[code].jh, sh = counts[code].sh;
    return [code, name, jh, sh, jh + sh];
  });
  if (rows.length > 0) sheet.getRange(2, 1, rows.length, 5).setValues(rows);
}

/* ===== TestData.js ===== */
/**
 * Seeds one fake school's worth of entries across every configured
 * category, using the real submitSchoolEntries_() write path (the same one the public,
 * session-guarded submitSchoolEntries calls) — so testing the
 * scheduler/admin views doesn't require filling out the live form by hand.
 * Safe to re-run: clears any prior TEST-school rows first.
 */
function seedTestData() {
  requireAdmin_();
  var TEST_CODE = 'TEST';
  var TEST_NAME = 'Test Christian School';

  ensureTestSchool_(TEST_CODE, TEST_NAME);
  clearPriorTestRows_(TEST_CODE);

  var config = readCategoryConfig_();
  var sampleNames = ['Alex Carter', 'Jordan Lee', 'Taylor Morgan', 'Riley Brooks', 'Casey Quinn', 'Morgan Ellis'];
  var nameIdx = 0;
  function nextName() {
    var n = sampleNames[nameIdx % sampleNames.length];
    nameIdx++;
    return n;
  }

  var entries = [];
  Object.keys(config).forEach(function (code) {
    var cat = config[code];
    var count = cat.maxPerSchool > 0 ? Math.min(cat.maxPerSchool, 2) : 1;
    for (var i = 0; i < count; i++) {
      var entry = {
        categoryCode: code,
        studentName: cat.isGroupRoster ? cat.name + ' Group ' + (i + 1) : nextName(),
        title: 'Sample ' + cat.name + ' Entry ' + (i + 1),
        authorComposer: 'Sample Composer',
        accompanist: 'Sample Accompanist',
        conductor: 'Sample Conductor',
        attachment: '',
        roster: []
      };
      if (cat.isGroupRoster) {
        entry.roster = [
          { studentName: nextName(), participatingIn: cat.name },
          { studentName: nextName(), participatingIn: cat.name }
        ];
      }
      entries.push(entry);
    }
  });

  var contact = {
    firstName: 'Pat', lastName: 'Sample', phone: '555-010-1234', email: 'test@example.com'
  };

  var result = submitSchoolEntries_(TEST_CODE, TEST_NAME, entries, contact);
  safeAlert_('Seeded ' + result.count + ' test entries for "' + TEST_NAME + '".');
  return result;
}

/**
 * Seeds STRICTLY the real 2023-2024 Jr./Sr. Master List data — no random
 * pools, no invented names, no synthetic scenarios. Every entry's
 * category/name/title/composer/accompanist/conductor comes verbatim
 * from HISTORICAL_ENTRIES, and every group act's roster (with each
 * member's real "also participating in" cross-references) comes
 * verbatim from HISTORICAL_ROSTERS — both transcribed from the actual
 * workbook (Master sheet + the per-school "_Groups" roster sheets).
 * A group act with no roster sheet in the source workbook (2 known
 * cases — see the comment on HISTORICAL_ROSTERS) is seeded with an
 * empty roster rather than invented names.
 * Each record's original ID# groups it into a school by its first 2
 * digits (e.g. "3414" -> school code "3400"); HISTORICAL_SCHOOL_NAMES
 * gives the real, verified school name for each such code.
 * Safe to re-run: clears prior submissions for those derived schools first.
 */
function seedHistoricalTestData() {
  requireAdmin_();
  var config = readCategoryConfig_();

  var bySchool = {};
  HISTORICAL_ENTRIES.forEach(function (rec) {
    var schoolCode = rec.id.slice(0, 2) + '00';
    if (!bySchool[schoolCode]) bySchool[schoolCode] = [];
    bySchool[schoolCode].push(rec);
  });

  var schoolCodes = Object.keys(bySchool);
  var existingSchools = {};
  getSchoolList().forEach(function (s) { existingSchools[s.code] = s.name; });
  schoolCodes.forEach(function (code) {
    if (!existingSchools[code]) {
      var name = HISTORICAL_SCHOOL_NAMES[code] || ('School ' + code);
      ensureTestSchool_(code, name);
      existingSchools[code] = name;
    }
  });

  clearPriorTestRows_(schoolCodes);

  var totalEntries = 0;
  var skippedOrphaned = [];
  var missingRosters = [];

  schoolCodes.forEach(function (schoolCode) {
    var schoolName = existingSchools[schoolCode];
    var countByCategory = {};
    var entries = [];

    bySchool[schoolCode].forEach(function (rec) {
      var cat = config[rec.code];
      if (!cat) { skippedOrphaned.push(rec.code + '/' + rec.id); return; }

      countByCategory[rec.code] = (countByCategory[rec.code] || 0) + 1;
      if (cat.maxPerSchool > 0 && countByCategory[rec.code] > cat.maxPerSchool) return; // respect the live cap

      var roster = [];
      if (cat.isGroupRoster) {
        var rosterKey = rec.code + '|' + rec.id;
        roster = HISTORICAL_ROSTERS[rosterKey] || [];
        if (roster.length === 0) missingRosters.push(rosterKey + ' (' + rec.name + ')');
      }

      entries.push({
        categoryCode: rec.code,
        studentName: rec.name || ('Entry ' + rec.id),
        title: rec.title || '',
        authorComposer: rec.composer || '',
        accompanist: rec.accompanist || '',
        conductor: rec.conductor || '',
        attachment: '',
        roster: roster
      });
    });

    if (entries.length === 0) return;
    var contact = {
      firstName: 'Contact', lastName: schoolName.split(' ')[0], phone: '555-010-' + schoolCode,
      email: 'registrar+' + schoolCode + '@example.com'
    };
    submitSchoolEntries_(schoolCode, schoolName, entries, contact);
    totalEntries += entries.length;
  });

  var msg = 'Seeded ' + totalEntries + ' real historical entries across ' + schoolCodes.length + ' schools into the Submissions tab. ' +
    'Run "Generate Master List" to see them on the Master tab.';
  if (skippedOrphaned.length > 0) msg += ' Skipped ' + skippedOrphaned.length + ' entries with unrecognized category codes: ' + skippedOrphaned.join(', ') + '.';
  if (missingRosters.length > 0) msg += ' No roster data exists in the source workbook for: ' + missingRosters.join(', ') + '.';
  safeAlert_(msg);
  return { success: true, totalEntries: totalEntries, schoolCount: schoolCodes.length, skippedOrphaned: skippedOrphaned, missingRosters: missingRosters };
}

/**
 * Run this directly from the Apps Script editor (select it in the
 * function dropdown, then Run) to repair the Submissions sheet's header
 * row in place — without clearing existing rows — if columns look
 * misaligned (e.g. Text/Attachment/Other Entry IDs showing wrong data).
 */
function repairSubmissionsHeader() {
  requireAdmin_();
  var sheet = getOrCreateSheet_(SHEETS.SUBMISSIONS);
  ensureHeaderRow_(sheet, SUBMISSIONS_HEADERS);
  safeAlert_('Submissions header checked/repaired.');
}

/**
 * Same repair for the Master sheet. Note: generateMasterList() already
 * fully rebuilds Master (header + rows) from Submissions every time it
 * runs, so this is only useful if you want to fix Master's header
 * without waiting to regenerate the whole list.
 */
function repairMasterHeader() {
  requireAdmin_();
  var sheet = getOrCreateSheet_(SHEETS.MASTER);
  ensureHeaderRow_(sheet, SUBMISSIONS_HEADERS);
  safeAlert_('Master header checked/repaired.');
}

/**
 * Overwrites the LIVE Category Config sheet with DEFAULT_CATEGORY_CONFIG
 * (Config.js) — a full replace, not a merge, since this is meant for
 * pushing an updated room assignment / duration / cap plan onto a
 * spreadsheet that already has data (Bootstrap's setupSpreadsheet only
 * seeds Category Config if it's empty, so it never re-applies updates
 * to an existing one). Run this after editing DEFAULT_CATEGORY_CONFIG
 * to match a new room-assignment plan.
 */
function repairCategoryConfig() {
  requireAdmin_();
  var sheet = getOrCreateSheet_(SHEETS.CATEGORY_CONFIG);
  setHeaderRow_(sheet, DEFAULT_CATEGORY_CONFIG_HEADERS);
  sheet.getRange(2, 1, DEFAULT_CATEGORY_CONFIG.length, DEFAULT_CATEGORY_CONFIG_HEADERS.length)
    .setValues(DEFAULT_CATEGORY_CONFIG);
  safeAlert_('Category Config replaced with ' + DEFAULT_CATEGORY_CONFIG.length + ' rows from the updated room-assignment plan.');
  return { success: true, count: DEFAULT_CATEGORY_CONFIG.length };
}

/**
 * Fills the Judges sheet by ROOM, not section: every scheduled category
 * that shares a Default Room gets the SAME `panelSize` (default 3)
 * judges — matching how a real panel actually works (3 people sit in
 * the Sanctuary all day judging every choir/ensemble that comes through
 * it, not a different 3 per category). Judges are named after the room
 * (e.g. "Sanctuary Judge 1/2/3"). Categories without a Default Room are
 * grouped under "Unassigned". Safe to re-run: replaces all rows each time.
 */
function seedGenericJudges(panelSize) {
  requireAdmin_();
  panelSize = panelSize || 3;
  var config = readCategoryConfig_();
  var byRoom = {};
  Object.keys(config).forEach(function (code) {
    var cfg = config[code];
    if (!cfg.scheduled) return;
    var room = cfg.room || 'Unassigned';
    if (!byRoom[room]) byRoom[room] = [];
    byRoom[room].push(code);
  });

  var rows = [];
  Object.keys(byRoom).forEach(function (room) {
    var codes = byRoom[room];
    var judgeNames = [];
    for (var j = 0; j < panelSize; j++) judgeNames.push(room + ' Judge ' + (j + 1));
    codes.forEach(function (code) {
      judgeNames.forEach(function (judgeName) {
        rows.push([judgeName, code, 'Auto-generated placeholder judge']);
      });
    });
  });

  var sheet = getOrCreateSheet_(SHEETS.JUDGES);
  setHeaderRow_(sheet, JUDGES_HEADERS);
  if (rows.length > 0) sheet.getRange(2, 1, rows.length, JUDGES_HEADERS.length).setValues(rows);
  safeAlert_('Seeded ' + rows.length + ' judge assignments — ' + panelSize + ' judges per room, across ' + Object.keys(byRoom).length + ' rooms.');
  return { success: true, count: rows.length };
}

function pickRandom_(list) { return list[Math.floor(Math.random() * list.length)]; }

function ensureTestSchool_(code, name) {
  var sheet = getOrCreateSheet_(SHEETS.SCHOOLS);
  var data = sheet.getDataRange().getValues();
  for (var i = 1; i < data.length; i++) {
    if (String(data[i][0]) === code) return;
  }
  sheet.appendRow([code, name, '#888888']);
}

function clearPriorTestRows_(codeOrCodes) {
  var codes = Array.isArray(codeOrCodes) ? codeOrCodes : [codeOrCodes];
  // One deleteRow() call per matching row was extremely slow on a sheet
  // with lots of accumulated test rows (each is a separate Sheets API
  // call). Filtering in memory and writing back once is a single call.
  // School Code lives at a different column index in each sheet.
  [[SHEETS.SUBMISSIONS, 2], [SHEETS.REGISTRATIONS, 1]].forEach(function (pair) {
    var sheet = getOrCreateSheet_(pair[0]);
    var codeCol = pair[1];
    var data = sheet.getDataRange().getValues();
    if (data.length <= 1) return;
    var header = data[0];
    var kept = data.slice(1).filter(function (row) { return codes.indexOf(String(row[codeCol])) === -1; });
    if (kept.length === data.length - 1) return; // nothing to remove
    sheet.clearContents();
    sheet.getRange(1, 1, 1, header.length).setValues([header]);
    if (kept.length > 0) sheet.getRange(2, 1, kept.length, header.length).setValues(kept);
  });
}

/**
 * Reverses everything the seed functions above put in the spreadsheet:
 * removes the TEST school's and every seeded historical school's rows
 * from Submissions, Registrations, and Schools, strips auto-generated
 * placeholder judges from Judges (identified by their Notes marker, so
 * any judge an admin has since hand-edited is left alone), and rebuilds
 * Master from the now-clean Submissions data. Real schools that happen
 * to reuse a historical school code are NOT distinguishable from seeded
 * ones, so this should only be run before real registrations start.
 */
function clearTestData_() {
  var TEST_CODE = 'TEST';
  var historicalCodes = {};
  HISTORICAL_ENTRIES.forEach(function (rec) { historicalCodes[rec.id.slice(0, 2) + '00'] = true; });
  var codes = [TEST_CODE].concat(Object.keys(historicalCodes));

  clearPriorTestRows_(codes);

  var schoolsSheet = getOrCreateSheet_(SHEETS.SCHOOLS);
  var schoolsData = schoolsSheet.getDataRange().getValues();
  if (schoolsData.length > 1) {
    var schoolsHeader = schoolsData[0];
    var keptSchools = schoolsData.slice(1).filter(function (row) { return codes.indexOf(String(row[0])) === -1; });
    if (keptSchools.length !== schoolsData.length - 1) {
      schoolsSheet.clearContents();
      schoolsSheet.getRange(1, 1, 1, schoolsHeader.length).setValues([schoolsHeader]);
      if (keptSchools.length > 0) schoolsSheet.getRange(2, 1, keptSchools.length, schoolsHeader.length).setValues(keptSchools);
    }
  }

  var judgesSheet = getOrCreateSheet_(SHEETS.JUDGES);
  var judgesData = judgesSheet.getDataRange().getValues();
  var judgesRemoved = 0;
  if (judgesData.length > 1) {
    var judgesHeader = judgesData[0];
    var keptJudges = judgesData.slice(1).filter(function (row) { return row[2] !== 'Auto-generated placeholder judge'; });
    judgesRemoved = judgesData.length - 1 - keptJudges.length;
    if (judgesRemoved > 0) {
      judgesSheet.clearContents();
      judgesSheet.getRange(1, 1, 1, judgesHeader.length).setValues([judgesHeader]);
      if (keptJudges.length > 0) judgesSheet.getRange(2, 1, keptJudges.length, judgesHeader.length).setValues(keptJudges);
    }
  }

  generateMasterList();

  var msg = 'Cleared test data: TEST school plus ' + (codes.length - 1) + ' seeded historical school codes removed from ' +
    'Submissions, Registrations, and Schools. ' + judgesRemoved + ' auto-generated judge rows removed. Master regenerated.';
  safeAlert_(msg);
  return { success: true };
}

/* ===== YearRollover.js ===== */
/**
 * Year-to-year rollover. Category Config, Field Templates, Settings,
 * Building Map, Schools, Judges, and Judging Sheets are competition setup
 * that should carry forward untouched (Bootstrap.js already only seeds
 * these when empty — this file doesn't need to touch them at all).
 * Submissions/Registrations/Master/Schedule/Admin Edit Log are one
 * competition's worth of data — those get archived and wiped.
 */

// Tabs that hold one year's worth of competition data, not carried-forward
// setup. `headers` is restored after clearing so the live sheet looks
// freshly bootstrapped; Master/Schedule/Category Counts are left header-less
// since Generate Master List/Generate Schedule always rewrite their own
// header on the next run, same as a brand-new spreadsheet.
var YEAR_RESET_TABS = [
  { name: SHEETS.SUBMISSIONS, headers: SUBMISSIONS_HEADERS },
  { name: SHEETS.REGISTRATIONS, headers: REGISTRATIONS_HEADERS },
  { name: SHEETS.ADMIN_EDITS_LOG, headers: ['Timestamp', 'Admin', 'Entry ID', 'Change Description'] },
  { name: SHEETS.MASTER, headers: null },
  { name: SHEETS.SCHEDULE, headers: null },
  { name: SHEETS.CATEGORY_COUNTS, headers: null }
];

// This Apps Script project only automates the Secondary (Jr./Sr. High)
// competition — Elementary, Spelling Bee, and Creative Writing are run
// from separate spreadsheets today. They all archive into the same
// <year> folder under this root (competition name goes in the file name,
// not a subfolder), keyed by Drive folder ID so it always resolves to the
// admin's own Drive regardless of file ownership/location.
var YEAR_ROLLOVER_ROOT_FOLDER_ID = 'DEMO_DRIVE_ID';
var YEAR_ROLLOVER_ROOT_FOLDER = 'MACS Fine Arts Competition';
var YEAR_ROLLOVER_COMPETITION = 'Secondary';

/**
 * Archives a full copy of the live spreadsheet into "<root>/<year>/" in
 * Drive, then clears the competition-data tabs in the live sheet so it's
 * ready for next year. Returns the archive file's URL/name so the admin
 * can confirm/open it.
 */
function resetForNextYear_(archiveYearLabel) {
  archiveYearLabel = (archiveYearLabel || '').toString().trim();
  if (!archiveYearLabel) throw new Error('Enter the year being archived (e.g. "2027") before resetting.');

  var ss = getSs_();
  var file = DriveApp.getFileById(ss.getId());
  var rootFolder = DriveApp.getFolderById(YEAR_ROLLOVER_ROOT_FOLDER_ID);
  var yearFolder = getOrCreateSubfolder_(rootFolder, archiveYearLabel);
  var archiveName = YEAR_ROLLOVER_COMPETITION + ' — ' + archiveYearLabel + ' Archive';
  var archiveSs = archiveSheetsOnly_(ss, archiveName);
  var archiveFile = DriveApp.getFileById(archiveSs.getId());
  moveFileToFolder_(archiveFile, yearFolder);

  YEAR_RESET_TABS.forEach(function (t) {
    var sheet = ss.getSheetByName(t.name);
    if (!sheet) return;
    sheet.getRange(1, 1, sheet.getMaxRows(), sheet.getMaxColumns()).clearNote();
    sheet.clear();
    if (t.headers && t.headers.length) {
      sheet.getRange(1, 1, 1, t.headers.length).setValues([t.headers]);
      sheet.setFrozenRows(1);
    }
  });

  ensureSettingExists_('Competition Year', '');
  var nextYear = archiveYearLabel.match(/^\d+$/) ? String(Number(archiveYearLabel) + 1) : '';
  var settingsSheet = getOrCreateSheet_(SHEETS.SETTINGS);
  var settingsData = settingsSheet.getDataRange().getValues();
  for (var i = 1; i < settingsData.length; i++) {
    if (settingsData[i][0] === 'Competition Year') {
      settingsSheet.getRange(i + 1, 2).setValue(nextYear);
      break;
    }
  }

  // Move the live file itself into next year's folder so the admin never
  // has to go find it — next year, the file that opens from that folder
  // IS the live working sheet, already reset and ready.
  var movedTo = null;
  if (nextYear) {
    var nextYearFolder = getOrCreateSubfolder_(rootFolder, nextYear);
    moveFileToFolder_(file, nextYearFolder);
    movedTo = YEAR_ROLLOVER_ROOT_FOLDER + '/' + nextYear;
  }

  return { archiveUrl: archiveFile.getUrl(), archiveName: archiveName, nextYear: nextYear, movedTo: movedTo };
}

  global.MACS_LOGIC = {
    bind: function (env) { SpreadsheetApp = env.SpreadsheetApp; CacheService = env.CacheService; PropertiesService = env.PropertiesService; DriveApp = env.DriveApp; UrlFetchApp = env.UrlFetchApp; LockService = env.LockService; Session = env.Session; Utilities = env.Utilities; Logger = env.Logger; HtmlService = env.HtmlService; MailApp = env.MailApp; },
    getSchoolList: getSchoolList,
    getBranding: getBranding,
    getCategoryList: getCategoryList,
    getJudgingSheets: getJudgingSheets,
    getPaymentInfo: getPaymentInfo,
    getFieldTemplateDefs: getFieldTemplateDefs,
    checkSchoolStatus: checkSchoolStatus,
    submitSchoolEntries: submitSchoolEntries,
    uploadEntryFile: uploadEntryFile,
    requestSchoolCode: requestSchoolCode,
    verifySchoolCode: verifySchoolCode,
    admin_getCategoryConfig: admin_getCategoryConfig,
    admin_saveCategoryConfig: admin_saveCategoryConfig,
    admin_getFieldTemplates: admin_getFieldTemplates,
    admin_saveFieldTemplates: admin_saveFieldTemplates,
    admin_getBuildingMap: admin_getBuildingMap,
    admin_saveBuildingMap: admin_saveBuildingMap,
    admin_getJudgingSheets: admin_getJudgingSheets,
    admin_saveJudgingSheets: admin_saveJudgingSheets,
    admin_uploadJudgingSheetFile: admin_uploadJudgingSheetFile,
    admin_getSettings: admin_getSettings,
    admin_saveSettings: admin_saveSettings,
    admin_getJudges: admin_getJudges,
    admin_saveJudges: admin_saveJudges,
    admin_getSchools: admin_getSchools,
    admin_saveSchools: admin_saveSchools,
    admin_getRegistrations: admin_getRegistrations,
    admin_getSubmissions: admin_getSubmissions,
    admin_updateSubmissionEntry: admin_updateSubmissionEntry,
    admin_deleteSubmissionEntry: admin_deleteSubmissionEntry,
    admin_runClearTestData: admin_runClearTestData,
    admin_resetForNextYear: admin_resetForNextYear,
    submitSchoolEntries_: submitSchoolEntries_,
    seedTestData: seedTestData,
    clearTestData_: clearTestData_,
    readSubmissions_: readSubmissions_,
    readCategoryConfig_: readCategoryConfig_,
    generateMasterList: generateMasterList,
    requireAdmin_: requireAdmin_,
    requireSchoolSession_: requireSchoolSession_,
    isAuthorizedAdmin_: isAuthorizedAdmin_,
    ensureSettingExists_: ensureSettingExists_,
    getOrCreateSheet_: getOrCreateSheet_,
    setHeaderRow_: setHeaderRow_,
    schoolSignInStatus_: schoolSignInStatus_,
    matchSchoolCode_: matchSchoolCode_,
    resetForNextYear_: resetForNextYear_,
    SHEETS: SHEETS,
    SUBMISSIONS_HEADERS: SUBMISSIONS_HEADERS,
    REGISTRATIONS_HEADERS: REGISTRATIONS_HEADERS,
    JUDGES_HEADERS: JUDGES_HEADERS,
    SCHOOLS_HEADERS: SCHOOLS_HEADERS,
    JUDGING_SHEETS_HEADERS: JUDGING_SHEETS_HEADERS,
    FIELD_TEMPLATES_HEADERS: FIELD_TEMPLATES_HEADERS,
    DEFAULT_CATEGORY_CONFIG_HEADERS: DEFAULT_CATEGORY_CONFIG_HEADERS,
    DEFAULT_CATEGORY_CONFIG: DEFAULT_CATEGORY_CONFIG,
    DEFAULT_FIELD_TEMPLATES: DEFAULT_FIELD_TEMPLATES,
    DEFAULT_SETTINGS: DEFAULT_SETTINGS,
    DEFAULT_BUILDINGS: DEFAULT_BUILDINGS,
    DEFAULT_JUDGING_SHEETS: DEFAULT_JUDGING_SHEETS
  };
})(typeof window !== "undefined" ? window : globalThis);
